// Code generated by tgo. DO NOT EDIT.

package tgolint

import (
	"go/constant"
	"go/token"
	"go/types"

	"tgo/internal/sourcefacts"
	"tgo/pkg/syntax"
)

// checkPayloadAccessor requires a proof for each generated payload accessor.
func (c *checker) checkPayloadAccessor(
	expression *syntax.Expression,
	selector *syntax.SelectorExpression,
	model *model,
	tag int,
) {
	if c.earlyExitPayloadProof(expression, selector.Expression, model, tag) {
		c.syntaxSafe[expression] = true
		return
	}
	c.syntaxHandled[expression] = true
	c.pass.Reportf(
		selector.Start,
		"%s: %s requires proof of %s",
		modelName(model), selector.Selector.Name, tagConstant(model, tag),
	)
}

// earlyExitPayloadProof finds a preceding guard that stops for other tags.
func (c *checker) earlyExitPayloadProof(
	expression *syntax.Expression,
	receiver *syntax.Expression,
	model *model,
	tag int,
) bool {
	access := syntax.ExpressionPosition(expression)
	for node := c.parents[syntax.ExpressionNode(expression)]; node != nil; node = c.parents[*node] {
		if _, nested := syntax.FunctionLiteralOf(node); nested {
			return false
		}
		statement, ok := syntax.StatementOf(node)
		if !ok {
			continue
		}
		block := syntax.BlockStatementOf(statement)
		if block == nil {
			continue
		}
		index := containingStatement(block.List, access)
		for candidate := index - 1; candidate >= 0; candidate-- {
			proofReceiver, proofModel, proofTag, proof := c.earlyExitTagGuard(
				block.List[candidate],
			)
			if !proof || !sameModel(proofModel, model) || proofTag != tag ||
				!sameReceiver(c.facts, receiver, proofReceiver) {
				continue
			}
			return c.enumReceiverStableBetween(
				expression, receiver,
				syntax.StatementPosition(block.List[candidate]), access,
			)
		}
	}
	return false
}

func containingStatement(statements []*syntax.Statement, position token.Pos) int {
	for index, statement := range statements {
		if syntax.StatementPosition(statement) <= position &&
			position < syntax.StatementEnd(statement) {
			return index
		}
	}
	return len(statements)
}

func (c *checker) earlyExitTagGuard(
	statement *syntax.Statement,
) (*syntax.Expression, *model, int, bool) {
	guard := syntax.IfStatementOf(statement)
	if guard == nil || guard.Init != nil || guard.Else != nil ||
		!c.statementsTerminate(c.file, guard.Body.List) {
		return nil, nil, 0, false
	}
	condition := syntax.BinaryExpressionOf(guard.Condition)
	if condition == nil || condition.Operator != token.NEQ {
		return nil, nil, 0, false
	}
	if receiver, model, tag, ok := c.tagGuardSides(condition.Left, condition.Right); ok {
		return receiver, model, tag, true
	}
	return c.tagGuardSides(condition.Right, condition.Left)
}

func (c *checker) tagGuardSides(
	tagCall *syntax.Expression,
	constantExpression *syntax.Expression,
) (*syntax.Expression, *model, int, bool) {
	receiver, _, _, model, tagType := c.tagCall(tagCall)
	if model == nil || !c.tagExpression(constantExpression, model, tagType) {
		return nil, nil, 0, false
	}
	value := c.facts.Constant(constantExpression)
	if value == nil {
		return nil, nil, 0, false
	}
	tag64, exact := constant.Int64Val(value)
	if !exact || tag64 < 1 || tag64 > int64(len(modelVariants(model))) {
		return nil, nil, 0, false
	}
	return receiver, model, int(tag64), true
}

// enumReceiverStableBefore checks the proof from a switch tag to an accessor.
func (c *checker) enumReceiverStableBefore(
	file *syntax.File,
	clause *syntax.CaseClause,
	expression *syntax.Expression,
	receiver *syntax.Expression,
	proof token.Pos,
) bool {
	_ = file
	access := syntax.ExpressionPosition(expression)
	_, body := c.enclosingEnumFunction(expression)
	if body == nil || !c.enumReceiverLocalToFunction(expression, receiver) ||
		c.enumGotoEntersClause(body, clause, access) {
		return false
	}
	if c.enumReceiverEscapedBefore(expression, receiver, proof) {
		return false
	}
	root, _, ok := receiverPath(c.facts, receiver)
	if !ok {
		return false
	}
	stable := true
	for _, statement := range clause.Body {
		if syntax.StatementPosition(statement) >= access {
			break
		}
		syntax.InspectStatement(statement, func(node *syntax.Node) bool {
			if !stable || syntax.NodePosition(node) >= access {
				return false
			}
			if literal, nested := syntax.FunctionLiteralOf(node); nested {
				if capturesObject(c.facts, literal.Body, root) {
					stable = false
				}
				return false
			}
			if c.enumReceiverEscapesAt(node, receiver) {
				stable = false
				return false
			}
			if syntax.NodePosition(node) > proof && c.enumReceiverChangesAt(node, receiver) {
				stable = false
			}
			return stable
		})
		if !stable {
			return false
		}
	}
	if c.enumLoopCanInvalidate(expression, receiver, proof, access) {
		return false
	}
	clauseBody := &syntax.BlockStatement{List: clause.Body}
	return !c.enumGotoCanInvalidate(clauseBody, receiver, proof, access)
}

// enumGotoEntersClause reports a jump into a proved switch clause.
func (c *checker) enumGotoEntersClause(
	body *syntax.BlockStatement,
	clause *syntax.CaseClause,
	access token.Pos,
) bool {
	labels := make(map[string]bool)
	for _, statement := range clause.Body {
		if syntax.StatementPosition(statement) >= access {
			break
		}
		syntax.InspectStatement(statement, func(node *syntax.Node) bool {
			if _, nested := syntax.FunctionLiteralOf(node); nested {
				return false
			}
			value, ok := syntax.StatementOf(node)
			if !ok {
				return true
			}
			labeled := syntax.LabeledStatementOf(value)
			if labeled != nil && labeled.Label != nil {
				labels[labeled.Label.Name] = true
			}
			return true
		})
	}
	if len(labels) == 0 {
		return false
	}
	invalid := false
	wrapped := syntax.StatementBlock{Value: body}.Statement()
	syntax.InspectStatement(&wrapped, func(node *syntax.Node) bool {
		if invalid {
			return false
		}
		if _, nested := syntax.FunctionLiteralOf(node); nested {
			return false
		}
		statement, ok := syntax.StatementOf(node)
		if !ok {
			return true
		}
		branch := syntax.BranchStatementOf(statement)
		if branch == nil || branch.Token != token.GOTO || branch.Label == nil ||
			!labels[branch.Label.Name] {
			return true
		}
		position := syntax.StatementPosition(statement)
		invalid = position < clause.Start || clause.Stop <= position
		return !invalid
	})
	return invalid
}

// enumReceiverStableBetween rejects a proof after a write or writable escape.
func (c *checker) enumReceiverStableBetween(
	expression *syntax.Expression,
	receiver *syntax.Expression,
	proof token.Pos,
	access token.Pos,
) bool {
	_, body := c.enclosingEnumFunction(expression)
	if body == nil || !c.enumReceiverLocalToFunction(expression, receiver) {
		return false
	}
	if c.enumReceiverEscapedBefore(expression, receiver, access) {
		return false
	}
	if c.enumGotoBypassesProof(body, proof, access) {
		return false
	}
	stable := true
	wrapped := syntax.StatementBlock{Value: body}.Statement()
	syntax.InspectStatement(&wrapped, func(node *syntax.Node) bool {
		if !stable || syntax.NodePosition(node) >= access {
			return false
		}
		if syntax.NodePosition(node) > proof && c.enumReceiverChangesAt(node, receiver) {
			stable = false
			return false
		}
		return true
	})
	if !stable {
		return false
	}
	if c.enumLoopCanInvalidate(expression, receiver, proof, access) {
		return false
	}
	return !c.enumGotoCanInvalidate(body, receiver, proof, access)
}

// enumGotoBypassesProof reports a jump into the proved source region.
func (c *checker) enumGotoBypassesProof(
	body *syntax.BlockStatement,
	proof token.Pos,
	access token.Pos,
) bool {
	labels := make(map[string]token.Pos)
	wrapped := syntax.StatementBlock{Value: body}.Statement()
	syntax.InspectStatement(&wrapped, func(node *syntax.Node) bool {
		if _, nested := syntax.FunctionLiteralOf(node); nested {
			return false
		}
		statement, ok := syntax.StatementOf(node)
		if !ok {
			return true
		}
		labeled := syntax.LabeledStatementOf(statement)
		if labeled != nil && labeled.Label != nil {
			labels[labeled.Label.Name] = labeled.Label.Start
		}
		return true
	})
	invalid := false
	syntax.InspectStatement(&wrapped, func(node *syntax.Node) bool {
		if invalid {
			return false
		}
		if _, nested := syntax.FunctionLiteralOf(node); nested {
			return false
		}
		statement, ok := syntax.StatementOf(node)
		if !ok {
			return true
		}
		branch := syntax.BranchStatementOf(statement)
		if branch == nil || branch.Token != token.GOTO || branch.Label == nil {
			return true
		}
		label := labels[branch.Label.Name]
		invalid = label != token.NoPos && proof < label && label < access
		return !invalid
	})
	return invalid
}

func (c *checker) enumReceiverEscapedBefore(
	expression *syntax.Expression,
	receiver *syntax.Expression,
	access token.Pos,
) bool {
	root, _, ok := receiverPath(c.facts, receiver)
	if !ok {
		return true
	}
	_, body := c.enclosingEnumFunction(expression)
	if body == nil {
		return true
	}
	escaped := false
	wrapped := syntax.StatementBlock{Value: body}.Statement()
	syntax.InspectStatement(&wrapped, func(node *syntax.Node) bool {
		if escaped || syntax.NodePosition(node) >= access {
			return false
		}
		if literal, nested := syntax.FunctionLiteralOf(node); nested {
			escaped = capturesObject(c.facts, literal.Body, root)
			return false
		}
		if c.enumReceiverEscapesAt(node, receiver) {
			escaped = true
		}
		return !escaped
	})
	return escaped
}

func (c *checker) enclosingEnumFunction(
	expression *syntax.Expression,
) (*syntax.Node, *syntax.BlockStatement) {
	if expression == nil {
		return nil, nil
	}
	node := syntax.ExpressionNode(expression)
	for parent := c.parents[node]; parent != nil; parent = c.parents[*parent] {
		if declaration, ok := syntax.FunctionDeclarationOf(parent); ok {
			return parent, declaration.Body
		}
		if literal, ok := syntax.FunctionLiteralOf(parent); ok {
			return parent, literal.Body
		}
	}
	return nil, nil
}

func (c *checker) enumReceiverLocalToFunction(
	expression *syntax.Expression,
	receiver *syntax.Expression,
) bool {
	root, _, ok := receiverPath(c.facts, receiver)
	if !ok {
		return false
	}
	function, _ := c.enclosingEnumFunction(expression)
	if function == nil || c.file == nil {
		return false
	}
	local := false
	found := false
	syntax.Inspect(c.file, func(node *syntax.Node) bool {
		if found {
			return false
		}
		identifier, ok := syntax.IdentifierOf(node)
		if !ok || c.facts.DefinitionName(identifier) != root {
			return true
		}
		found = true
		for parent := c.parents[*node]; parent != nil; parent = c.parents[*parent] {
			if _, ok := syntax.FunctionDeclarationOf(parent); ok {
				local = *parent == *function
				break
			}
			if _, ok := syntax.FunctionLiteralOf(parent); ok {
				local = *parent == *function
				break
			}
		}
		return false
	})
	return local
}

func (c *checker) enumReceiverChangesAt(
	node *syntax.Node,
	receiver *syntax.Expression,
) bool {
	statement, ok := syntax.StatementOf(node)
	if !ok {
		return false
	}
	if assignment := syntax.AssignmentStatementOf(statement); assignment != nil {
		for _, target := range assignment.Left {
			if receiverOverlaps(c.facts, target, receiver) {
				return true
			}
		}
	}
	if increment := syntax.IncrementStatementOf(statement); increment != nil {
		return receiverOverlaps(c.facts, increment.Expression, receiver)
	}
	if ranged := syntax.RangeStatementOf(statement); ranged != nil {
		return receiverOverlaps(c.facts, ranged.Key, receiver) ||
			receiverOverlaps(c.facts, ranged.Value, receiver)
	}
	return false
}

func (c *checker) enumReceiverEscapesAt(
	node *syntax.Node,
	receiver *syntax.Expression,
) bool {
	expression, ok := syntax.ExpressionOf(node)
	if !ok {
		return false
	}
	if unary := syntax.UnaryExpressionOf(expression); unary != nil &&
		unary.Operator == token.AND && receiverOverlaps(c.facts, unary.Expression, receiver) {
		return true
	}
	if selector := syntax.SelectorExpressionOf(expression); selector != nil &&
		c.pointerMethodSelection(expression) &&
		receiverOverlaps(c.facts, selector.Expression, receiver) {
		return true
	}
	call := syntax.CallExpressionOf(expression)
	if call == nil {
		return false
	}
	for _, argument := range call.Args {
		typ := c.facts.Type(argument)
		if typ == nil {
			continue
		}
		if _, pointer := types.Unalias(typ).(*types.Pointer); pointer &&
			receiverOverlaps(c.facts, argument, receiver) {
			return true
		}
	}
	return false
}

func (c *checker) enumReceiverInvalidatedAt(
	node *syntax.Node,
	receiver *syntax.Expression,
) bool {
	if c.enumReceiverChangesAt(node, receiver) || c.enumReceiverEscapesAt(node, receiver) {
		return true
	}
	literal, nested := syntax.FunctionLiteralOf(node)
	if !nested {
		return false
	}
	root, _, ok := receiverPath(c.facts, receiver)
	return ok && capturesObject(c.facts, literal.Body, root)
}

func receiverOverlaps(
	facts *sourcefacts.Index,
	left *syntax.Expression,
	right *syntax.Expression,
) bool {
	return receiverWrite(facts, left, right) || receiverWrite(facts, right, left)
}

func (c *checker) enumLoopCanInvalidate(
	expression *syntax.Expression,
	receiver *syntax.Expression,
	proof token.Pos,
	access token.Pos,
) bool {
	if expression == nil {
		return false
	}
	for node := c.parents[syntax.ExpressionNode(expression)]; node != nil; node = c.parents[*node] {
		statement, ok := syntax.StatementOf(node)
		if !ok {
			continue
		}
		if syntax.StatementPosition(statement) <= proof {
			continue
		}
		if syntax.StatementPosition(statement) >= access {
			continue
		}
		if syntax.ForStatementOf(statement) == nil && syntax.RangeStatementOf(statement) == nil {
			continue
		}
		changed := false
		syntax.InspectStatement(statement, func(child *syntax.Node) bool {
			if c.enumReceiverInvalidatedAt(child, receiver) {
				changed = true
			}
			return !changed
		})
		if changed {
			return true
		}
	}
	return false
}

func (c *checker) enumGotoCanInvalidate(
	body *syntax.BlockStatement,
	receiver *syntax.Expression,
	proof token.Pos,
	access token.Pos,
) bool {
	changedAfter := false
	invalid := false
	wrapped := syntax.StatementBlock{Value: body}.Statement()
	syntax.InspectStatement(&wrapped, func(node *syntax.Node) bool {
		if invalid {
			return false
		}
		position := syntax.NodePosition(node)
		if position > access && c.enumReceiverInvalidatedAt(node, receiver) {
			changedAfter = true
		}
		statement, ok := syntax.StatementOf(node)
		if !ok {
			return true
		}
		branch := syntax.BranchStatementOf(statement)
		if !changedAfter || branch == nil || branch.Token != token.GOTO || branch.Label == nil {
			return true
		}
		label := c.facts.Object(branch.Label)
		invalid = label != nil && label.Pos() > proof && label.Pos() < access
		return !invalid
	})
	return invalid
}
