// Code generated by tgo. DO NOT EDIT.
//tgo:v2 "generic_scalar.tgo"

package tgolint

import __tgo_json "encoding/json"
import __tgo_jsonv2 "encoding/json/v2"
import __tgo_jsontext "encoding/json/jsontext"
import __tgo_fmt "fmt"

import (
	"go/constant"
	"go/token"
	"go/types"

	"tgo/pkg/syntax"
	"tgo/pkg/syntax/cfg"
)

func __tgo_scalarValue_external_json_to[T interface{}](out *__tgo_jsontext.Encoder, name string, payload T) error {
	if err := out.WriteToken(__tgo_jsontext.BeginObject); err != nil {
		return err
	}
	if err := out.WriteToken(__tgo_jsontext.String(name)); err != nil {
		return err
	}
	if err := __tgo_jsonv2.MarshalEncode(out, payload); err != nil {
		return err
	}
	return out.WriteToken(__tgo_jsontext.EndObject)
}

// scalarValue requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type scalarValueTag uint8

const (
	scalarValueTagBoolean scalarValueTag = iota + 1
	scalarValueTagInteger
	scalarValueTagBooleanParameter
	scalarValueTagIntegerParameter
)

type scalarValue struct {
	tgoTag              scalarValueTag
	tgoBoolean          scalarValueBoolean
	tgoInteger          scalarValueInteger
	tgoBooleanParameter scalarValueBooleanParameter
	tgoIntegerParameter scalarValueIntegerParameter
}

// Tag returns the active tag.
func (v scalarValue) Tag() scalarValueTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v scalarValue) UnknownTag() string {
	return __tgo_fmt.Sprintf("scalarValue: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// scalarValueBoolean is the Boolean payload.
type scalarValueBoolean struct {
	Value bool
}

// scalarValue constructs scalarValue. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value scalarValueBoolean) scalarValue() scalarValue {
	return scalarValue{tgoTag: scalarValueTagBoolean, tgoBoolean: value}
}

// BooleanPayload requires Boolean. No tag check.
func (v scalarValue) BooleanPayload() scalarValueBoolean { return v.tgoBoolean }

// scalarValueInteger is the Integer payload.
type scalarValueInteger struct {
	Value int64
}

// scalarValue constructs scalarValue. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value scalarValueInteger) scalarValue() scalarValue {
	return scalarValue{tgoTag: scalarValueTagInteger, tgoInteger: value}
}

// IntegerPayload requires Integer. No tag check.
func (v scalarValue) IntegerPayload() scalarValueInteger { return v.tgoInteger }

// scalarValueBooleanParameter is the BooleanParameter payload.
type scalarValueBooleanParameter struct {
	Index   int
	Negated bool
}

// scalarValue constructs scalarValue. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value scalarValueBooleanParameter) scalarValue() scalarValue {
	return scalarValue{tgoTag: scalarValueTagBooleanParameter, tgoBooleanParameter: value}
}

// BooleanParameterPayload requires BooleanParameter. No tag check.
func (v scalarValue) BooleanParameterPayload() scalarValueBooleanParameter {
	return v.tgoBooleanParameter
}

// scalarValueIntegerParameter is the IntegerParameter payload.
type scalarValueIntegerParameter struct {
	Index int
}

// scalarValue constructs scalarValue. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value scalarValueIntegerParameter) scalarValue() scalarValue {
	return scalarValue{tgoTag: scalarValueTagIntegerParameter, tgoIntegerParameter: value}
}

// IntegerParameterPayload requires IntegerParameter. No tag check.
func (v scalarValue) IntegerParameterPayload() scalarValueIntegerParameter {
	return v.tgoIntegerParameter
}

func (v scalarValue) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case scalarValueTagBoolean:
		payload := v.BooleanPayload()
		return __tgo_json.Marshal(struct {
			Payload scalarValueBoolean `json:"Boolean"`
		}{Payload: payload})
	case scalarValueTagInteger:
		payload := v.IntegerPayload()
		return __tgo_json.Marshal(struct {
			Payload scalarValueInteger `json:"Integer"`
		}{Payload: payload})
	case scalarValueTagBooleanParameter:
		payload := v.BooleanParameterPayload()
		return __tgo_json.Marshal(struct {
			Payload scalarValueBooleanParameter `json:"BooleanParameter"`
		}{Payload: payload})
	case scalarValueTagIntegerParameter:
		payload := v.IntegerParameterPayload()
		return __tgo_json.Marshal(struct {
			Payload scalarValueIntegerParameter `json:"IntegerParameter"`
		}{Payload: payload})
	default:
		return nil, __tgo_fmt.Errorf("invalid scalarValue JSON tag")
	}
}

func (v scalarValue) MarshalJSONTo(out *__tgo_jsontext.Encoder) error {
	switch v.tgoTag {
	case scalarValueTagBoolean:
		payload := v.BooleanPayload()
		return __tgo_scalarValue_external_json_to(out, "Boolean", payload)
	case scalarValueTagInteger:
		payload := v.IntegerPayload()
		return __tgo_scalarValue_external_json_to(out, "Integer", payload)
	case scalarValueTagBooleanParameter:
		payload := v.BooleanParameterPayload()
		return __tgo_scalarValue_external_json_to(out, "BooleanParameter", payload)
	case scalarValueTagIntegerParameter:
		payload := v.IntegerParameterPayload()
		return __tgo_scalarValue_external_json_to(out, "IntegerParameter", payload)
	default:
		return __tgo_fmt.Errorf("invalid scalarValue JSON tag")
	}
}

func (v *scalarValue) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]__tgo_json.RawMessage
	if err := __tgo_json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return __tgo_fmt.Errorf("expected one scalarValue JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Boolean":
		var payload scalarValueBoolean
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.scalarValue()
		return nil
	case "Integer":
		var payload scalarValueInteger
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.scalarValue()
		return nil
	case "BooleanParameter":
		var payload scalarValueBooleanParameter
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.scalarValue()
		return nil
	case "IntegerParameter":
		var payload scalarValueIntegerParameter
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.scalarValue()
		return nil
	default:
		return __tgo_fmt.Errorf("unknown scalarValue JSON variant %q", variant)
	}
}

func (v *scalarValue) UnmarshalJSONFrom(in *__tgo_jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return __tgo_fmt.Errorf("expected one scalarValue JSON variant")
	}
	var payloadData __tgo_jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Boolean":
			current = 1
		case "Integer":
			current = 2
		case "BooleanParameter":
			current = 3
		case "IntegerParameter":
			current = 4
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return __tgo_fmt.Errorf("expected one scalarValue JSON variant")
	}
	if selected == 0 {
		return __tgo_fmt.Errorf("unknown scalarValue JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload scalarValueBoolean
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.scalarValue()
		return nil
	case 2:
		var payload scalarValueInteger
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.scalarValue()
		return nil
	case 3:
		var payload scalarValueBooleanParameter
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.scalarValue()
		return nil
	case 4:
		var payload scalarValueIntegerParameter
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.scalarValue()
		return nil
	default:
		return __tgo_fmt.Errorf("invalid scalarValue JSON tag")
	}
}

type scalarState map[types.Object]scalarValue

type scalarFlow struct {
	before map[syntax.Node]scalarState
}

// scalarValueAt returns a proven scalar value before the expression runs.
func (c *checker) scalarValueAt(
	node *syntax.Node,
	expression *syntax.Expression,
) (scalarValue, bool) {
	if c == nil || node == nil || expression == nil {
		return scalarValueBoolean{Value: false}.scalarValue(), false
	}
	root := c.enclosingFunction(node)
	if root == nil {
		return scalarValueBoolean{Value: false}.scalarValue(), false
	}
	flow := c.scalarFlows[*root]
	if flow == nil {
		flow = c.buildScalarFlow(root)
		c.scalarFlows[*root] = flow
	}
	if flow == nil {
		return scalarValueBoolean{Value: false}.scalarValue(), false
	}
	state := flow.before[syntax.ExpressionNode(expression)]
	if state == nil {
		state = flow.before[*node]
	}
	return c.evaluateScalar(expression, state)
}

// enclosingFunction finds the declaration or literal that owns a node.
func (c *checker) enclosingFunction(node *syntax.Node) *syntax.Node {
	var current *syntax.Node = node
	for current != nil {
		if _, declaration := syntax.FunctionDeclarationOf(current); declaration {
			return current
		}
		if _, literal := syntax.FunctionLiteralOf(current); literal {
			return current
		}
		parent := c.parents[*current]
		if parent == nil {
			return nil
		}
		current = parent
	}
	return nil
}

// buildScalarFlow solves scalar facts over the function control-flow graph.
func (c *checker) buildScalarFlow(root *syntax.Node) *scalarFlow {
	body := genericFunctionBody(root)
	flow := &scalarFlow{before: make(map[syntax.Node]scalarState)}
	if body == nil {
		return flow
	}
	graph := cfg.New(body, c.callMayReturn)
	owned := c.ownedScalars(root, body)
	entries := c.solveScalarEntries(graph, c.scalarEntryState(root), owned)
	c.recordScalarEntries(flow, graph, entries, owned)
	return flow
}

// solveScalarEntries computes stable input facts for every live CFG block.
func (c *checker) solveScalarEntries(
	graph *cfg.CFG,
	entry scalarState,
	owned map[types.Object]bool,
) []scalarState {
	entries := make([]scalarState, len(graph.Blocks))
	entries[0] = entry
	queued := make([]bool, len(graph.Blocks))
	queue := []*cfg.Block{graph.Blocks[0]}
	queued[0] = true
	for len(queue) != 0 {
		block := queue[0]
		queue = queue[1:]
		queued[block.Index] = false
		state := c.transferScalarBlock(entries[block.Index], block, owned)
		for _, successor := range c.scalarSuccessors(block, state) {
			joined, changed := joinScalarState(entries[successor.Index], state)
			if !changed {
				continue
			}
			entries[successor.Index] = joined
			if !queued[successor.Index] {
				queue = append(queue, successor)
				queued[successor.Index] = true
			}
		}
	}
	return entries
}

// transferScalarBlock applies every scalar write and escape in one block.
func (c *checker) transferScalarBlock(
	entry scalarState,
	block *cfg.Block,
	owned map[types.Object]bool,
) scalarState {
	state := cloneScalarState(entry)
	c.clearRangeScalars(state, block)
	for _, node := range block.Nodes {
		c.transferScalarNode(state, node, owned)
	}
	return state
}

// scalarSuccessors removes an edge when the block condition is constant.
func (c *checker) scalarSuccessors(
	block *cfg.Block,
	state scalarState,
) []*cfg.Block {
	if len(block.Succs) != 2 || len(block.Nodes) == 0 {
		return block.Succs
	}
	condition, ok := syntax.ExpressionOf(&block.Nodes[len(block.Nodes)-1])
	if !ok || condition == nil {
		return block.Succs
	}
	value, known := c.evaluateScalar(condition, state)
	if !known {
		return block.Succs
	}
	boolean, booleanKnown := scalarBoolean(value)
	if !booleanKnown {
		return block.Succs
	}
	if boolean {
		return block.Succs[:1]
	}
	return block.Succs[1:]
}

// recordScalarEntries saves final facts before each syntax node.
func (c *checker) recordScalarEntries(
	flow *scalarFlow,
	graph *cfg.CFG,
	entries []scalarState,
	owned map[types.Object]bool,
) {
	for _, block := range graph.Blocks {
		if entries[block.Index] == nil {
			continue
		}
		state := cloneScalarState(entries[block.Index])
		c.clearRangeScalars(state, block)
		for _, node := range block.Nodes {
			recordScalarState(flow.before, node, state)
			c.transferScalarNode(state, node, owned)
		}
	}
}

// ownedScalars limits facts to parameters and variables from this function.
func (c *checker) ownedScalars(
	root *syntax.Node,
	body *syntax.BlockStatement,
) map[types.Object]bool {
	owned := make(map[types.Object]bool)
	if signature := c.functionSignature(root); signature != nil {
		for index := 0; index < signature.Params().Len(); index++ {
			owned[signature.Params().At(index)] = true
		}
	}
	inspectGenericBlock(body, func(node *syntax.Node) bool {
		if _, nested := syntax.FunctionLiteralOf(node); nested {
			return false
		}
		name, ok := syntax.IdentifierOf(node)
		if !ok {
			return true
		}
		if variable, ok := c.facts.DefinitionName(name).(*types.Var); ok {
			owned[variable] = true
		}
		return true
	})
	return owned
}

// scalarEntryState maps stable Boolean and integer parameters to call arguments.
func (c *checker) scalarEntryState(
	root *syntax.Node,
) scalarState {
	state := make(scalarState)
	signature := c.functionSignature(root)
	if signature == nil {
		return state
	}
	for index := 0; index < signature.Params().Len(); index++ {
		parameter := signature.Params().At(index)
		if isBoolean(parameter.Type()) {
			state[parameter] = scalarValueBooleanParameter{
				Index: index, Negated: false,
			}.scalarValue()
			continue
		}
		if isInteger(parameter.Type()) {
			state[parameter] = scalarValueIntegerParameter{
				Index: index,
			}.scalarValue()
		}
	}
	return state
}

func (c *checker) functionSignature(root *syntax.Node) *types.Signature {
	if function, ok := syntax.FunctionDeclarationOf(root); ok {
		object, _ := c.facts.DefinitionName(function.Name).(*types.Func)
		if object != nil {
			signature, _ := object.Type().(*types.Signature)
			return signature
		}
	}
	return c.facts.FunctionSignature(syntax.NodePosition(root))
}

func isInteger(typ types.Type) bool {
	basic, ok := coreType(typ).(*types.Basic)
	return ok && basic.Info()&types.IsInteger != 0
}

func (c *checker) clearRangeScalars(
	state scalarState,
	block *cfg.Block,
) {
	if block.Kind != cfg.KindRangeBody {
		return
	}
	statement := syntax.RangeStatementOf(block.Stmt)
	if statement == nil {
		return
	}
	for _, expression := range []*syntax.Expression{statement.Key, statement.Value} {
		name := syntax.IdentifierExpressionOf(expression)
		if name != nil && name.Name != "_" {
			delete(state, c.facts.Object(name))
		}
	}
}

func (c *checker) transferScalarNode(
	state scalarState,
	node syntax.Node,
	owned map[types.Object]bool,
) {
	if statement, ok := syntax.StatementOf(&node); ok {
		if assignment := syntax.AssignmentStatementOf(statement); assignment != nil {
			c.transferScalarAssignment(state, assignment, owned)
		}
		if declaration := syntax.DeclarationStatementOf(statement); declaration != nil {
			general := syntax.GeneralDeclarationOf(declaration.Declaration)
			if general != nil {
				for _, specification := range general.Specs {
					values := syntax.ValueSpecificationOf(specification)
					if values == nil {
						continue
					}
					c.transferScalarValues(state, values.Names, values.Values, owned)
				}
			}
		}
		if increment := syntax.IncrementStatementOf(statement); increment != nil {
			if name := syntax.IdentifierExpressionOf(increment.Expression); name != nil {
				delete(state, c.facts.Object(name))
			}
		}
	}
	if specification, ok := syntax.SpecificationOf(&node); ok {
		if values := syntax.ValueSpecificationOf(specification); values != nil {
			c.transferScalarValues(
				state, values.Names, values.Values, owned,
			)
		}
	}
	c.invalidateScalarEscapes(state, &node)
}

// transferScalarAssignment evaluates all right sides before it changes state.
func (c *checker) transferScalarAssignment(
	state scalarState,
	statement *syntax.AssignmentStatement,
	owned map[types.Object]bool,
) {
	if statement.Operator != token.ASSIGN && statement.Operator != token.DEFINE ||
		len(statement.Left) != len(statement.Right) {
		for _, target := range statement.Left {
			if name := syntax.IdentifierExpressionOf(target); name != nil {
				delete(state, c.facts.Object(name))
			}
		}
		return
	}
	values := make([]scalarValue, 0, len(statement.Right))
	known := make([]bool, 0, len(statement.Right))
	for _, expression := range statement.Right {
		value, valueKnown := c.evaluateScalar(expression, state)
		values = append(values, value)
		known = append(known, valueKnown)
	}
	for index, target := range statement.Left {
		name := syntax.IdentifierExpressionOf(target)
		if name == nil || name.Name == "_" {
			continue
		}
		object := c.facts.Object(name)
		if !owned[object] || !known[index] {
			delete(state, object)
		} else {
			state[object] = values[index]
		}
	}
}

func (c *checker) transferScalarValues(
	state scalarState,
	names []*syntax.Identifier,
	values []*syntax.Expression,
	owned map[types.Object]bool,
) {
	if len(names) != len(values) {
		for _, name := range names {
			delete(state, c.facts.Object(name))
		}
		return
	}
	for index, name := range names {
		object := c.facts.Object(name)
		value, known := c.evaluateScalar(values[index], state)
		if !owned[object] || !known {
			delete(state, object)
		} else {
			state[object] = value
		}
	}
}

// invalidateScalarEscapes drops facts after an address or closure captures a value.
func (c *checker) invalidateScalarEscapes(state scalarState, root *syntax.Node) {
	inspectGenericNode(root, func(node *syntax.Node) bool {
		if expression, ok := syntax.ExpressionOf(node); ok {
			if unary := syntax.UnaryExpressionOf(expression); unary != nil &&
				unary.Operator == token.AND {
				if name := syntax.IdentifierExpressionOf(unary.Expression); name != nil {
					delete(state, c.facts.Object(name))
				}
			}
			if selector := syntax.SelectorExpressionOf(expression); selector != nil &&
				c.pointerMethodSelection(expression) {
				if name := syntax.IdentifierExpressionOf(selector.Expression); name != nil {
					delete(state, c.facts.Object(name))
				}
			}
		}
		literal, ok := syntax.FunctionLiteralOf(node)
		if !ok {
			return true
		}
		inspectGenericBlock(literal.Body, func(nested *syntax.Node) bool {
			name, ok := syntax.IdentifierOf(nested)
			if ok {
				delete(state, c.facts.Object(name))
			}
			return true
		})
		return false
	})
}

// evaluateScalar reduces constants, aliases, and supported Boolean expressions.
func (c *checker) evaluateScalar(
	expression *syntax.Expression,
	state scalarState,
) (scalarValue, bool) {
	if expression == nil {
		return scalarValueBoolean{Value: false}.scalarValue(), false
	}
	if exact, known := exactScalar(c.facts.Constant(expression)); known {
		return exact, true
	}
	if parentheses := syntax.ParenthesizedExpressionOf(expression); parentheses != nil {
		return c.evaluateScalar(parentheses.Expression, state)
	}
	if identifier := syntax.IdentifierExpressionOf(expression); identifier != nil {
		if value, ok := state[c.facts.Object(identifier)]; ok {
			return value, true
		}
		return scalarValueBoolean{Value: false}.scalarValue(), false
	}
	if unary := syntax.UnaryExpressionOf(expression); unary != nil {
		value, ok := c.evaluateScalar(unary.Expression, state)
		if !ok || unary.Operator != token.NOT {
			return scalarValueBoolean{Value: false}.scalarValue(), false
		}
		return negateScalarBoolean(value)
	}
	if binary := syntax.BinaryExpressionOf(expression); binary != nil {
		return c.evaluateScalarBinary(binary, state)
	}
	if call := syntax.CallExpressionOf(expression); call != nil {
		if c.valuePreservingConversion(expression, call) {
			return c.evaluateScalar(call.Args[0], state)
		}
	}
	return scalarValueBoolean{Value: false}.scalarValue(), false
}

func exactScalar(value constant.Value) (scalarValue, bool) {
	if value == nil {
		return scalarValueBoolean{Value: false}.scalarValue(), false
	}
	switch value.Kind() {
	case constant.Bool:
		return scalarValueBoolean{Value: constant.BoolVal(value)}.scalarValue(), true
	case constant.Int:
		integer, ok := constant.Int64Val(value)
		return scalarValueInteger{Value: integer}.scalarValue(), ok
	default:
		return scalarValueBoolean{Value: false}.scalarValue(), false
	}
}

func (c *checker) valuePreservingConversion(
	expression *syntax.Expression,
	call *syntax.CallExpression,
) bool {
	return len(call.Args) == 1 && c.facts.IsType(call.Callee) &&
		types.Identical(
			c.facts.Type(expression),
			c.facts.Type(call.Args[0]),
		)
}

// evaluateScalarBinary evaluates safe Boolean operations and equality.
func (c *checker) evaluateScalarBinary(
	expression *syntax.BinaryExpression,
	state scalarState,
) (scalarValue, bool) {
	left, leftKnown := c.evaluateScalar(expression.Left, state)
	right, rightKnown := c.evaluateScalar(expression.Right, state)
	if !leftKnown || !rightKnown {
		return scalarValueBoolean{Value: false}.scalarValue(), false
	}
	leftBoolean, leftBooleanKnown := scalarBoolean(left)
	rightBoolean, rightBooleanKnown := scalarBoolean(right)
	switch expression.Operator {
	case token.LAND:
		return scalarLogicalAnd(
			left, leftBoolean, leftBooleanKnown,
			right, rightBoolean, rightBooleanKnown,
		)
	case token.LOR:
		return scalarLogicalOr(
			left, leftBoolean, leftBooleanKnown,
			right, rightBoolean, rightBooleanKnown,
		)
	case token.EQL, token.NEQ:
		if scalarValuesEqual(left, right) {
			equal := expression.Operator == token.EQL
			return scalarValueBoolean{Value: equal}.scalarValue(), true
		}
	}
	return scalarValueBoolean{Value: false}.scalarValue(), false
}

func scalarLogicalAnd(
	left scalarValue,
	leftBoolean bool,
	leftKnown bool,
	right scalarValue,
	rightBoolean bool,
	rightKnown bool,
) (scalarValue, bool) {
	if leftKnown && !leftBoolean || rightKnown && !rightBoolean {
		return scalarValueBoolean{Value: false}.scalarValue(), true
	}
	if leftKnown && leftBoolean {
		return right, true
	}
	if rightKnown && rightBoolean {
		return left, true
	}
	return scalarValueBoolean{Value: false}.scalarValue(), false
}

func scalarLogicalOr(
	left scalarValue,
	leftBoolean bool,
	leftKnown bool,
	right scalarValue,
	rightBoolean bool,
	rightKnown bool,
) (scalarValue, bool) {
	if leftKnown && leftBoolean || rightKnown && rightBoolean {
		return scalarValueBoolean{Value: true}.scalarValue(), true
	}
	if leftKnown && !leftBoolean {
		return right, true
	}
	if rightKnown && !rightBoolean {
		return left, true
	}
	return scalarValueBoolean{Value: false}.scalarValue(), false
}

func scalarBoolean(value scalarValue) (bool, bool) {
	switch enumValue7 := value; enumValue7.Tag() {
	case scalarValueTagBoolean:
		boolean := enumValue7.BooleanPayload()
		return boolean.Value, true
	case scalarValueTagInteger:
		return false, false
	case scalarValueTagBooleanParameter:
		return false, false
	case scalarValueTagIntegerParameter:
		return false, false
	default:
		panic(enumValue7.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func scalarInteger(value scalarValue) (int64, bool) {
	switch enumValue8 := value; enumValue8.Tag() {
	case scalarValueTagBoolean:
		return 0, false
	case scalarValueTagInteger:
		integer := enumValue8.IntegerPayload()
		return integer.Value, true
	case scalarValueTagBooleanParameter:
		return 0, false
	case scalarValueTagIntegerParameter:
		return 0, false
	default:
		panic(enumValue8.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func scalarParameter(value scalarValue) (int, bool, bool) {
	switch enumValue9 := value; enumValue9.Tag() {
	case scalarValueTagBoolean:
		return 0, false, false
	case scalarValueTagInteger:
		return 0, false, false
	case scalarValueTagBooleanParameter:
		parameter := enumValue9.BooleanParameterPayload()
		return parameter.Index, parameter.Negated, true
	case scalarValueTagIntegerParameter:
		parameter := enumValue9.IntegerParameterPayload()
		return parameter.Index, false, true
	default:
		panic(enumValue9.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func negateScalarBoolean(value scalarValue) (scalarValue, bool) {
	switch enumValue10 := value; enumValue10.Tag() {
	case scalarValueTagBoolean:
		boolean := enumValue10.BooleanPayload()
		return scalarValueBoolean{Value: !boolean.Value}.scalarValue(), true
	case scalarValueTagInteger:
		return scalarValueBoolean{Value: false}.scalarValue(), false
	case scalarValueTagBooleanParameter:
		parameter := enumValue10.BooleanParameterPayload()
		return scalarValueBooleanParameter{
			Index: parameter.Index, Negated: !parameter.Negated,
		}.scalarValue(), true
	case scalarValueTagIntegerParameter:
		return scalarValueBoolean{Value: false}.scalarValue(), false
	default:
		panic(enumValue10.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func scalarValuesEqual(left scalarValue, right scalarValue) bool {
	if leftBoolean, ok := scalarBoolean(left); ok {
		rightBoolean, rightOK := scalarBoolean(right)
		return rightOK && leftBoolean == rightBoolean
	}
	if leftInteger, ok := scalarInteger(left); ok {
		rightInteger, rightOK := scalarInteger(right)
		return rightOK && leftInteger == rightInteger
	}
	if leftIndex, leftNegated, ok := scalarBooleanParameter(left); ok {
		rightIndex, rightNegated, rightOK := scalarBooleanParameter(right)
		return rightOK && leftIndex == rightIndex && leftNegated == rightNegated
	}
	leftIndex, leftOK := scalarIntegerParameter(left)
	rightIndex, rightOK := scalarIntegerParameter(right)
	return leftOK && rightOK && leftIndex == rightIndex
}

func scalarBooleanParameter(value scalarValue) (int, bool, bool) {
	switch enumValue11 := value; enumValue11.Tag() {
	case scalarValueTagBoolean:
		return 0, false, false
	case scalarValueTagInteger:
		return 0, false, false
	case scalarValueTagBooleanParameter:
		parameter := enumValue11.BooleanParameterPayload()
		return parameter.Index, parameter.Negated, true
	case scalarValueTagIntegerParameter:
		return 0, false, false
	default:
		panic(enumValue11.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func scalarIntegerParameter(value scalarValue) (int, bool) {
	switch enumValue12 := value; enumValue12.Tag() {
	case scalarValueTagBoolean:
		return 0, false
	case scalarValueTagInteger:
		return 0, false
	case scalarValueTagBooleanParameter:
		return 0, false
	case scalarValueTagIntegerParameter:
		parameter := enumValue12.IntegerParameterPayload()
		return parameter.Index, true
	default:
		panic(enumValue12.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func cloneScalarState(state scalarState) scalarState {
	cloned := make(scalarState, len(state))
	for object, value := range state {
		cloned[object] = value
	}
	return cloned
}

// joinScalarState keeps facts that are equal on every incoming path.
func joinScalarState(current scalarState, incoming scalarState) (scalarState, bool) {
	if current == nil {
		return cloneScalarState(incoming), true
	}
	joined := make(scalarState)
	for object, value := range current {
		if other, ok := incoming[object]; ok {
			if scalarValuesEqual(value, other) {
				joined[object] = value
			}
		}
	}
	if scalarStatesEqual(current, joined) {
		return current, false
	}
	return joined, true
}

func scalarStatesEqual(left scalarState, right scalarState) bool {
	if len(left) != len(right) {
		return false
	}
	for object, value := range left {
		if other, ok := right[object]; ok {
			if !scalarValuesEqual(value, other) {
				return false
			}
		} else {
			return false
		}
	}
	return true
}

func recordScalarState(
	target map[syntax.Node]scalarState,
	root syntax.Node,
	state scalarState,
) {
	inspectGenericNode(&root, func(node *syntax.Node) bool {
		if _, nested := syntax.FunctionLiteralOf(node); nested {
			return false
		}
		target[*node] = cloneScalarState(state)
		return true
	})
}
