// Code generated by tgo. DO NOT EDIT.
//tgo:v1 "generic_values.tgo" 40a86d3f648134609fb5450a139a5f15e5b02fc06d8abe169609fc7aeba9f10f

package tgolint

import (
	"go/ast"
	"go/token"
	"go/types"
	__tgo_runtime "tgo/internal/tgoruntime"
)

type genericValue struct {
	function          *types.Func
	fact              *genericEffectSet
	receiverArguments []types.Type
	typeArguments     []types.Type
	conditionCall     *ast.CallExpr
	returned          bool
}
type tgogenericValueValidationError string

func (e tgogenericValueValidationError) Error() string { return string(e) }

// ValidategenericValue checks and reconstructs one foreign genericValue graph.
func ValidategenericValue(value genericValue) (genericValue, error) {
	return __tgo_runtime.RebuildAs(value, __tgo_runtime.NewContext())
}
func (v genericValue) TgoReconstruct(context *__tgo_runtime.Context) (any, error) {
	result := v
	field0, err := __tgo_runtime.RebuildAs(v.function, context)
	if err != nil {
		return result, err
	}
	result.function = field0
	field1, err := __tgo_runtime.RebuildAs(v.fact, context)
	if err != nil {
		return result, err
	}
	result.fact = field1
	field2, err := __tgo_runtime.RebuildAs(v.receiverArguments, context)
	if err != nil {
		return result, err
	}
	result.receiverArguments = field2
	field3, err := __tgo_runtime.RebuildAs(v.typeArguments, context)
	if err != nil {
		return result, err
	}
	result.typeArguments = field3
	field4, err := __tgo_runtime.RebuildAs(v.conditionCall, context)
	if err != nil {
		return result, err
	}
	result.conditionCall = field4
	field5, err := __tgo_runtime.RebuildAs(v.returned, context)
	if err != nil {
		return result, err
	}
	result.returned = field5
	return result, nil
}

type genericValueBinding struct {
	value     genericValue
	source    ast.Expr
	ambiguous bool
}
type tgogenericValueBindingValidationError string

func (e tgogenericValueBindingValidationError) Error() string { return string(e) }

// ValidategenericValueBinding checks and reconstructs one foreign genericValueBinding graph.
func ValidategenericValueBinding(value genericValueBinding) (genericValueBinding, error) {
	return __tgo_runtime.RebuildAs(value, __tgo_runtime.NewContext())
}
func (v genericValueBinding) TgoReconstruct(context *__tgo_runtime.Context) (any, error) {
	result := v
	field0, err := __tgo_runtime.RebuildAs(v.value, context)
	if err != nil {
		return result, err
	}
	result.value = field0
	field1, err := __tgo_runtime.RebuildAs(v.source, context)
	if err != nil {
		return result, err
	}
	result.source = field1
	field2, err := __tgo_runtime.RebuildAs(v.ambiguous, context)
	if err != nil {
		return result, err
	}
	result.ambiguous = field2
	return result, nil
}

func (c *checker) collectGenericValueBindings(
	summaries map[*types.Func]*genericEffectSummary,
) (map[types.Object]*genericValueBinding, map[ast.Expr]bool) {
	bindings := make(map[types.Object]*genericValueBinding)
	sources := make(map[ast.Expr]bool)
	for _, file := range c.pass.Files {
		if c.generated[file] {
			continue
		}
		c.collectFileGenericValueBindings(file, summaries, bindings, sources)
	}
	for _, file := range c.pass.Files {
		c.markAmbiguousGenericValueBindings(file, bindings)
	}
	return bindings, sources
}

func (c *checker) collectFileGenericValueBindings(
	file *ast.File,
	summaries map[*types.Func]*genericEffectSummary,
	bindings map[types.Object]*genericValueBinding,
	sources map[ast.Expr]bool,
) {
	ast.Inspect(file, func(node ast.Node) bool {
		switch node := node.(type) {
		case *ast.AssignStmt:
			if node.Tok == token.DEFINE {
				c.collectAssignedGenericValues(
					node.Lhs, node.Rhs, summaries, bindings, sources,
				)
			}
		case *ast.ValueSpec:
			left := make([]ast.Expr, len(node.Names))
			for index := range node.Names {
				left[index] = node.Names[index]
			}
			c.collectAssignedGenericValues(
				left, node.Values, summaries, bindings, sources,
			)
		}
		return true
	})
}

func (c *checker) markAmbiguousGenericValueBindings(
	file *ast.File,
	bindings map[types.Object]*genericValueBinding,
) {
	ast.Inspect(file, func(node ast.Node) bool {
		switch statement := node.(type) {
		case *ast.AssignStmt:
			c.markAmbiguousGenericTargets(statement.Lhs, statement.Tok, bindings)
		case *ast.RangeStmt:
			c.markAmbiguousGenericTargets(
				[]ast.Expr{statement.Key, statement.Value}, statement.Tok, bindings,
			)
		}
		return true
	})
}

func (c *checker) markAmbiguousGenericTargets(
	targets []ast.Expr,
	operator token.Token,
	bindings map[types.Object]*genericValueBinding,
) {
	for _, target := range targets {
		name, ok := target.(*ast.Ident)
		if !ok || name == nil {
			continue
		}
		if operator == token.DEFINE && c.pass.TypesInfo.Defs[name] != nil {
			continue
		}
		if binding := bindings[c.pass.TypesInfo.ObjectOf(name)]; binding != nil {
			binding.ambiguous = true
		}
	}
}

func (c *checker) collectAssignedGenericValues(
	left []ast.Expr,
	right []ast.Expr,
	summaries map[*types.Func]*genericEffectSummary,
	bindings map[types.Object]*genericValueBinding,
	sources map[ast.Expr]bool,
) {
	if len(left) != len(right) {
		return
	}
	for index, expression := range right {
		value, ok := c.genericValue(expression, summaries)
		name, named := left[index].(*ast.Ident)
		if !ok || !named || name.Name == "_" {
			continue
		}
		object := c.pass.TypesInfo.ObjectOf(name)
		if object == nil {
			continue
		}
		if current := bindings[object]; current != nil {
			current.ambiguous = true
			continue
		}
		bindings[object] = &genericValueBinding{
			value: value, source: expression, ambiguous: false,
		}
		sources[expression] = true
	}
}

func (c *checker) genericValue(
	expression ast.Expr,
	summaries map[*types.Func]*genericEffectSummary,
) (genericValue, bool) {
	if call, ok := unparenthesized(expression).(*ast.CallExpr); ok {
		function, receiverArguments, typeArguments := c.genericCall(call)
		if function == nil {
			return noGenericValue(), false
		}
		fact := c.genericZeroFact(function, summaries)
		if fact != nil &&
			(len(fact.ReturnedZeroEffects) != 0 || len(fact.ReturnedAccessEffects) != 0) {
			return genericValue{
				function: function, fact: fact,
				receiverArguments: receiverArguments,
				typeArguments:     typeArguments, conditionCall: call, returned: true,
			}, true
		}
		return noGenericValue(), false
	}
	identifier := genericCallIdentifier(expression)
	if identifier == nil {
		return noGenericValue(), false
	}
	function, ok := c.genericCallObject(expression).(*types.Func)
	if !ok {
		return noGenericValue(), false
	}
	fact := c.genericZeroFact(function.Origin(), summaries)
	if fact == nil {
		return noGenericValue(), false
	}
	var typeArguments []types.Type = nil
	if instance, ok := c.pass.TypesInfo.Instances[identifier]; ok {
		typeArguments = typeList(instance.TypeArgs)
	}
	return genericValue{
		function: function.Origin(), fact: fact,
		receiverArguments: c.receiverTypeArguments(expression),
		typeArguments:     typeArguments,
		conditionCall:     nil,
		returned:          false,
	}, true
}

func (c *checker) reportDirectGenericValueEscape(
	expression ast.Expr,
	summaries map[*types.Func]*genericEffectSummary,
	sources map[ast.Expr]bool,
) {
	if sources[expression] || c.calledDirectly(expression) || c.discardedValue(expression) ||
		c.genericInstantiationPart(expression) {
		return
	}
	value, ok := c.genericValue(expression, summaries)
	if ok && !value.returned {
		c.reportGenericValueEscape(expression, value)
	}
}

func (c *checker) genericInstantiationPart(expression ast.Expr) bool {
	switch parent := c.parents[expression].(type) {
	case *ast.IndexExpr:
		return parent.X == expression
	case *ast.IndexListExpr:
		return parent.X == expression
	}
	return false
}

func (c *checker) reportReturnedGenericCall(
	call *ast.CallExpr,
	summaries map[*types.Func]*genericEffectSummary,
	sources map[ast.Expr]bool,
) {
	value, ok := c.genericValue(call, summaries)
	if !ok || !value.returned || sources[call] {
		return
	}
	if invocation := c.directCallOf(call); invocation != nil {
		c.reportGenericValueCall(invocation, value)
		return
	}
	if c.discardedValue(call) || c.expressionStatement(call) {
		return
	}
	c.reportGenericValueEscape(call, value)
}

func (c *checker) directCallOf(expression ast.Expr) *ast.CallExpr {
	current := ast.Node(expression)
	for {
		parentheses, ok := c.parents[current].(*ast.ParenExpr)
		if !ok {
			break
		}
		current = parentheses
	}
	call, ok := c.parents[current].(*ast.CallExpr)
	if ok && call.Fun == current {
		return call
	}
	return nil
}

func (c *checker) discardedValue(expression ast.Expr) bool {
	current := ast.Node(expression)
	for {
		parentheses, ok := c.parents[current].(*ast.ParenExpr)
		if !ok {
			break
		}
		current = parentheses
	}
	assignment, ok := c.parents[current].(*ast.AssignStmt)
	if !ok || len(assignment.Lhs) != len(assignment.Rhs) {
		return false
	}
	for index, right := range assignment.Rhs {
		if right != current {
			continue
		}
		name, blank := assignment.Lhs[index].(*ast.Ident)
		return blank && name.Name == "_"
	}
	return false
}

func (c *checker) expressionStatement(expression ast.Expr) bool {
	current := ast.Node(expression)
	for {
		parentheses, ok := c.parents[current].(*ast.ParenExpr)
		if !ok {
			break
		}
		current = parentheses
	}
	statement, ok := c.parents[current].(*ast.ExprStmt)
	return ok && statement.X == current
}

func (c *checker) reportBoundGenericValueUse(
	name *ast.Ident,
	bindings map[types.Object]*genericValueBinding,
) {
	binding := bindings[c.pass.TypesInfo.Uses[name]]
	if binding == nil || c.discardedValue(name) {
		return
	}
	if call := c.directCallOf(name); call != nil && !binding.ambiguous {
		c.reportGenericValueCall(call, binding.value)
		return
	}
	c.reportGenericValueEscape(name, binding.value)
}

func (c *checker) reportGenericValueCall(call *ast.CallExpr, value genericValue) {
	conditionCall := call
	effectsZero := value.fact.ZeroEffects
	effectsAccess := value.fact.AccessEffects
	description := "call to " + value.function.Name()
	if value.returned {
		conditionCall = value.conditionCall
		effectsZero = value.fact.ReturnedZeroEffects
		effectsAccess = value.fact.ReturnedAccessEffects
		description = "call to function returned by " + value.function.Name()
	}
	c.reportGenericEffects(call, conditionCall, effectsZero,
		value.receiverArguments, value.typeArguments, true, description)
	c.reportGenericEffects(call, conditionCall, effectsAccess,
		value.receiverArguments, value.typeArguments, false, description)
}

func (c *checker) reportGenericValueEscape(position ast.Expr, value genericValue) {
	if !c.genericValueAffectsModel(value) {
		return
	}
	description := "generic tgo function value " + value.function.Name()
	if value.returned {
		description = "function returned by " + value.function.Name()
	}
	c.reportResult(
		position.Pos(),
		"%s escapes; its effects cannot be checked at a call site",
		description,
	)
}

func (c *checker) genericValueAffectsModel(value genericValue) bool {
	zeroEffects, accessEffects := value.fact.ZeroEffects, value.fact.AccessEffects
	if value.returned {
		zeroEffects = value.fact.ReturnedZeroEffects
		accessEffects = value.fact.ReturnedAccessEffects
	}
	for _, effect := range zeroEffects {
		if c.genericEffectModel(effect, value.receiverArguments, value.typeArguments, true) != nil {
			return true
		}
	}
	for _, effect := range accessEffects {
		if c.genericEffectModel(
			effect, value.receiverArguments, value.typeArguments, false,
		) != nil {
			return true
		}
	}
	return false
}

func (c *checker) calledDirectly(expression ast.Expr) bool {
	current := expression
	for {
		parent := c.parents[current]
		parentheses, ok := parent.(*ast.ParenExpr)
		if !ok {
			call, called := parent.(*ast.CallExpr)
			return called && call.Fun == current
		}
		current = parentheses
	}
}

func noGenericValue() genericValue {
	return genericValue{
		function: nil, fact: nil, receiverArguments: nil, typeArguments: nil,
		conditionCall: nil, returned: false,
	}
}
