// Code generated by tgo. DO NOT EDIT.

package tgolint

import (
	"go/token"
	"go/types"
	"sort"

	"tgo/pkg/syntax"
)

func containedTypeParameters(
	typ types.Type,
	parameters map[*types.TypeParam]zeroParameter,
	seen map[types.Type]bool,
) map[zeroParameter]bool {
	result := make(map[zeroParameter]bool)
	if typ == nil {
		return result
	}
	typ = types.Unalias(typ)
	if seen[typ] {
		return result
	}
	seen[typ] = true
	merge := func(nested types.Type) {
		mergeZeroParameters(result, containedTypeParameters(nested, parameters, seen))
	}
	classified := goTypeOf(typ)
	switch classified.Tag() {
	case goTypeTagTypeParameter:
		parameterType := classified.TypeParameterPayload().Value
		{
			parameter, ok := parameters[parameterType]
			if ok {
				result[parameter] = true
			}
		}
	case goTypeTagNamed:
		named := classified.NamedPayload().Value
		for index := 0; index < named.TypeArgs().Len(); index++ {
			merge(named.TypeArgs().At(index))
		}
	case goTypeTagPointer:
		merge(classified.PointerPayload().Value.Elem())
	case goTypeTagArray:
		merge(classified.ArrayPayload().Value.Elem())
	case goTypeTagSlice:
		merge(classified.SlicePayload().Value.Elem())
	case goTypeTagMap:
		mapping := classified.MapPayload().Value
		merge(mapping.Key())
		merge(mapping.Elem())
	case goTypeTagChannel:
		merge(classified.ChannelPayload().Value.Elem())
	case goTypeTagNil, goTypeTagBasic, goTypeTagStruct, goTypeTagTuple,
		goTypeTagSignature, goTypeTagInterface, goTypeTagUnion, goTypeTagOther:
	default:
		panic("invalid goType tag") // unreachable: tgolint requires a case per tag
	}
	return result
}

// propagateGenericZeroFacts reaches a fixed point across local generic calls.
func (c *checker) propagateGenericZeroFacts(
	summaries map[*types.Func]*genericEffectSummary,
) {
	changed := true
	for changed {
		changed = false
		for _, summary := range summaries {
			for _, call := range summary.calls {
				function, receiverArguments, typeArguments := c.genericCall(call)
				if function == nil {
					continue
				}
				fact := c.genericZeroFact(function, summaries)
				if fact == nil {
					continue
				}
				if c.propagateGenericEffects(
					summary,
					call,
					fact.ZeroEffects,
					receiverArguments,
					typeArguments,
					true,
				) {
					changed = true
				}
				if c.propagateGenericEffects(
					summary,
					call,
					fact.AccessEffects,
					receiverArguments,
					typeArguments,
					false,
				) {
					changed = true
				}
			}
		}
	}
}

func (c *checker) propagateGenericEffects(
	summary *genericEffectSummary,
	callExpression *syntax.Expression,
	effects []GenericEffect,
	receiverArguments []types.Type,
	typeArguments []types.Type,
	zero bool,
) bool {
	changed := false
	pathConditions, pathMaySkip, reachable := c.genericEffectPath(
		summary, syntaxNode(callExpression),
	)
	if !reachable {
		return false
	}
	for _, effect := range effects {
		mapped, parameters, possible := c.propagatedGenericEffect(
			summary, callExpression, effect, receiverArguments, typeArguments,
			pathConditions, pathMaySkip, zero,
		)
		if !possible {
			continue
		}
		for parameter := range parameters {
			operand := c.addGenericEffect(summary, zero, parameter, mapped)
			if !operand {
				operand = changed
			}
			changed = operand
		}
	}
	return changed
}

// propagatedGenericEffect maps one callee effect into its caller.
func (c *checker) propagatedGenericEffect(
	summary *genericEffectSummary,
	callExpression *syntax.Expression,
	effect GenericEffect,
	receiverArguments []types.Type,
	typeArguments []types.Type,
	pathConditions []GenericEffectCondition,
	pathMaySkip bool,
	zero bool,
) (GenericEffect, map[zeroParameter]bool, bool) {
	type operandType = bool
	arguments := typeArguments
	if effect.Receiver {
		arguments = receiverArguments
	}
	var operand operandType = effect.TypeParameter < 0
	if !operand {
		operand = effect.TypeParameter >= len(arguments)
	}
	if operand {
		return noGenericEffect(), nil, false
	}
	conditions := append([]GenericEffectCondition(nil), pathConditions...)
	operand_1 := pathMaySkip
	if !operand_1 {
		operand_1 = effect.MaySkip
	}
	maySkip := operand_1
	targetType := arguments[effect.TypeParameter]
	for _, condition := range effect.Conditions {
		mapped, outcome := c.mapEffectCondition(
			summary, callExpression, condition, targetType,
		)
		if outcome == neverEffectOutcome() {
			return noGenericEffect(), nil, false
		}
		if outcome == conditionalEffectOutcome() {
			conditions = append(conditions, *mapped)
		}
		if outcome == unknownEffectOutcome() {
			maySkip = true
		}
	}
	mapped := GenericEffect{
		Receiver: false, TypeParameter: 0, Conditions: conditions, MaySkip: maySkip,
	}
	if zero {
		return mapped, zeroTypeParameters(
			targetType, summary.parameters, make(map[types.Type]bool),
		), true
	}
	return mapped, containedTypeParameters(
		targetType, summary.parameters, make(map[types.Type]bool),
	), true
}

// mapEffectCondition evaluates or remaps one callee condition.
func (c *checker) mapEffectCondition(
	summary *genericEffectSummary,
	callExpression *syntax.Expression,
	condition GenericEffectCondition,
	targetType types.Type,
) (*GenericEffectCondition, effectOutcome) {
	type operandType = bool
	call := syntax.CallExpressionOf(callExpression)
	if call == nil {
		return nil, unknownEffectOutcome()
	}
	var operand operandType = condition.ValueParameter < 0
	if !operand {
		operand = condition.ValueParameter >= len(call.Args)
	}
	if operand {
		return nil, unknownEffectOutcome()
	}
	{
		matches, known := c.effectConditionValue(
			callExpression, condition, targetType,
		)
		if known {
			if matches {
				return nil, alwaysEffectOutcome()
			}
			return nil, neverEffectOutcome()
		}
	}
	expression := call.Args[condition.ValueParameter]
	{
		mapped := c.mappedScalarEffectCondition(
			callExpression, expression, condition,
		)
		if mapped != nil {
			return mapped, conditionalEffectOutcome()
		}
	}
	return c.mapParameterEffectCondition(
		summary, callExpression, expression, condition,
	)
}

func (c *checker) mapParameterEffectCondition(
	summary *genericEffectSummary,
	callExpression *syntax.Expression,
	expression *syntax.Expression,
	condition GenericEffectCondition,
) (*GenericEffectCondition, effectOutcome) {
	call := syntax.CallExpressionOf(callExpression)
	if call == nil {
		return nil, unknownEffectOutcome()
	}
	{
		parentheses := syntax.ParenthesizedExpressionOf(expression)
		if parentheses != nil {
			expression = parentheses.Expression
		}
	}
	expected := condition.Expected
	{
		type operandType = bool
		negation := syntax.UnaryExpressionOf(expression)
		var operand operandType = negation != nil
		if operand {
			operand = negation.Operator == token.NOT
		}
		var operand_1 operandType = operand
		if operand_1 {
			operand_1 = condition.Kind == booleanEffectCondition()
		}
		if operand_1 {
			expression = negation.Expression
			expected = !expected
		}
	}
	index, ok := c.expressionParameter(summary, expression)
	operand_2 := !ok
	if !operand_2 {
		operand_2 = !c.parameterStableBefore(summary, index, call.Start)
	}
	if operand_2 {
		return nil, unknownEffectOutcome()
	}
	otherIndex := -1
	if condition.OtherParameter >= 0 {
		if condition.OtherParameter >= len(call.Args) {
			return nil, unknownEffectOutcome()
		}
		otherIndex, ok = c.expressionParameter(
			summary,
			call.Args[condition.OtherParameter],
		)
		operand_3 := !ok
		if !operand_3 {
			operand_3 = !c.parameterStableBefore(summary, otherIndex, call.Start)
		}
		if operand_3 {
			return nil, unknownEffectOutcome()
		}
	}
	mapped := GenericEffectCondition{
		ValueParameter: index,
		OtherParameter: otherIndex,
		Kind:           condition.Kind,
		Expected:       expected,
	}
	return &mapped, conditionalEffectOutcome()
}

func (c *checker) mappedScalarEffectCondition(
	callExpression *syntax.Expression,
	expression *syntax.Expression,
	condition GenericEffectCondition,
) *GenericEffectCondition {
	if !isScalarEffectCondition(condition.Kind) {
		return nil
	}
	value, known := c.scalarValueAt(syntaxNode(callExpression), expression)
	if !known {
		return nil
	}
	index, negated, parameter := scalarParameter(value)
	if !parameter {
		return nil
	}
	expected := condition.Expected
	var operand bool = condition.Kind == booleanEffectCondition()
	if operand {
		operand = negated
	}
	if operand {
		expected = !expected
	}
	return &GenericEffectCondition{
		ValueParameter: index, OtherParameter: -1,
		Kind: condition.Kind, Expected: expected,
	}
}

func isScalarEffectCondition(kind EffectKind) bool {
	switch effectKind := kind; effectKind.Tag() {
	case EffectKindTagBoolean:
		return true
	case EffectKindTagNonzero:
		return true
	case EffectKindTagNonempty:
		return false
	case EffectKindTagMapMiss:
		return false
	case EffectKindTagChannelClosed:
		return false
	case EffectKindTagAssertionFails:
		return false
	case EffectKindTagResliceExtends:
		return false
	default:
		panic("invalid EffectKind tag") // unreachable: tgolint requires a case per tag
	}
}

func (c *checker) genericZeroFact(
	function *types.Func,
	summaries map[*types.Func]*genericEffectSummary,
) *GenericEffectFact {
	{
		summary := summaries[function]
		if summary != nil {
			return summary.effects()
		}
	}
	fact := new(GenericEffectFact)
	if c.pass.ImportObjectFact(function, fact) {
		return fact
	}
	return nil
}

func (summary *genericEffectSummary) effects() *GenericEffectFact {
	return &GenericEffectFact{
		ZeroEffects: append([]GenericEffect(nil), summary.zeroEffects...),
		AccessEffects: append(
			[]GenericEffect(nil), summary.accessEffects...,
		),
		ReturnedZeroEffects: append(
			[]GenericEffect(nil), summary.returnedZeroEffects...,
		),
		ReturnedAccessEffects: append(
			[]GenericEffect(nil), summary.returnedAccessEffects...,
		),
	}
}

// fact sorts a local summary for package export.
func (summary *genericEffectSummary) fact() *GenericEffectFact {
	effects := summary.effects()
	sortGenericEffects(effects.ZeroEffects)
	sortGenericEffects(effects.AccessEffects)
	sortGenericEffects(effects.ReturnedZeroEffects)
	sortGenericEffects(effects.ReturnedAccessEffects)
	return effects
}

func (fact *GenericEffectFact) hasEffects() bool {
	var operand bool = len(fact.ZeroEffects) != 0
	if !operand {
		operand = len(fact.AccessEffects) != 0
	}
	var operand_1 bool = operand
	if !operand_1 {
		operand_1 = len(fact.ReturnedZeroEffects) != 0
	}
	var operand_2 bool = operand_1
	if !operand_2 {
		operand_2 = len(fact.ReturnedAccessEffects) != 0
	}
	return operand_2

}

func sortGenericEffects(effects []GenericEffect) {
	sort.Slice(effects, func(left, right int) bool {
		if effects[left].Receiver != effects[right].Receiver {
			return !effects[left].Receiver
		}
		if effects[left].TypeParameter != effects[right].TypeParameter {
			return effects[left].TypeParameter < effects[right].TypeParameter
		}
		if effects[left].MaySkip != effects[right].MaySkip {
			return !effects[left].MaySkip
		}
		if len(effects[left].Conditions) != len(effects[right].Conditions) {
			return len(effects[left].Conditions) < len(effects[right].Conditions)
		}
		for index := range effects[left].Conditions {
			leftCondition := effects[left].Conditions[index]
			rightCondition := effects[right].Conditions[index]
			if leftCondition.ValueParameter != rightCondition.ValueParameter {
				return leftCondition.ValueParameter < rightCondition.ValueParameter
			}
			leftKind := leftCondition.Kind.Tag()
			rightKind := rightCondition.Kind.Tag()
			if leftKind != rightKind {
				return leftKind < rightKind
			}
			if leftCondition.OtherParameter != rightCondition.OtherParameter {
				return leftCondition.OtherParameter < rightCondition.OtherParameter
			}
			if leftCondition.Expected != rightCondition.Expected {
				return !leftCondition.Expected
			}
		}
		return false
	})
}
