// Code generated by tgo. DO NOT EDIT.

package tgolint

import "go/types"

func zeroTypeParameters(
	typ types.Type,
	parameters map[*types.TypeParam]zeroParameter,
	seen map[types.Type]bool,
) map[zeroParameter]bool {
	result := make(map[zeroParameter]bool)
	if typ == nil {
		return result
	}
	typ = types.Unalias(typ)
	if seen[typ] {
		return result
	}
	seen[typ] = true
	classified := goTypeOf(typ)
	switch classified.Tag() {
	case goTypeTagTypeParameter:
		parameterType := classified.TypeParameterPayload().Value
		if parameter, ok := parameters[parameterType]; ok {
			result[parameter] = true
		}
	case goTypeTagNamed:
		named := classified.NamedPayload().Value
		mergeZeroParameters(result, zeroTypeParameters(named.Underlying(), parameters, seen))
	case goTypeTagStruct:
		structure := classified.StructPayload().Value
		for index := 0; index < structure.NumFields(); index++ {
			mergeZeroParameters(
				result,
				zeroTypeParameters(structure.Field(index).Type(), parameters, seen),
			)
		}
	case goTypeTagArray:
		array := classified.ArrayPayload().Value
		if array.Len() > 0 {
			mergeZeroParameters(result, zeroTypeParameters(array.Elem(), parameters, seen))
		}
	case goTypeTagNil, goTypeTagBasic, goTypeTagSlice, goTypeTagPointer,
		goTypeTagTuple, goTypeTagSignature, goTypeTagMap, goTypeTagChannel,
		goTypeTagInterface, goTypeTagUnion, goTypeTagOther:
	default:
		panic("invalid goType tag") // unreachable: tgolint requires a case per tag
	}
	return result
}

func mergeZeroParameters(target, source map[zeroParameter]bool) {
	for parameter := range source {
		target[parameter] = true
	}
}
