// Code generated by tgo. DO NOT EDIT.

package tgolint

import "encoding/json"
import jsonv2 "encoding/json/v2"
import "encoding/json/jsontext"
import "fmt"

import (
	"go/token"
	"go/types"
	"strings"

	"tgo/pkg/syntax"
)

// GenericEffectFact carries generic effects between analysis packages.

type GenericEffectFact struct {
	ZeroEffects           []GenericEffect
	AccessEffects         []GenericEffect
	ReturnedZeroEffects   []GenericEffect
	ReturnedAccessEffects []GenericEffect
}

// AFact marks GenericEffectFact as a Go analysis fact.
func (*GenericEffectFact) AFact() {}

type zeroParameter struct {
	receiver bool
	index    int
}

// EffectKind identifies the condition that controls a generic effect.
func tgoEffectKindExternalJSONTo[T interface{}](out *jsontext.Encoder, name string, payload T) error {
	{
		err := out.WriteToken(jsontext.BeginObject)
		if err != nil {
			return err
		}
	}
	{
		err := out.WriteToken(jsontext.String(name))
		if err != nil {
			return err
		}
	}
	{
		err := jsonv2.MarshalEncode(out, payload)
		if err != nil {
			return err
		}
	}
	return out.WriteToken(jsontext.EndObject)
}

// EffectKind requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type EffectKindTag uint8

const (
	EffectKindTagBoolean EffectKindTag = iota + 1
	EffectKindTagNonzero
	EffectKindTagNonempty
	EffectKindTagMapMiss
	EffectKindTagChannelClosed
	EffectKindTagAssertionFails
	EffectKindTagResliceExtends
)

type EffectKind struct {
	tgoTag EffectKindTag
}

// Tag returns the active tag.
func (v EffectKind) Tag() EffectKindTag { return v.tgoTag }

// GobEncode returns the stable four-byte enum tag.
func (v EffectKind) GobEncode() ([]byte, error) {
	type operandType = bool
	var operand operandType = v.tgoTag < EffectKindTagBoolean
	if !operand {
		operand = v.tgoTag > EffectKindTagResliceExtends
	}
	if operand {
		return nil, fmt.Errorf("EffectKind: cannot gob encode invalid tag %d", v.tgoTag)
	}
	tag := uint32(v.tgoTag)
	return []byte{byte(tag >> 24), byte(tag >> 16), byte(tag >> 8), byte(tag)}, nil
}

// GobDecode replaces the value with a valid four-byte enum tag.
func (v *EffectKind) GobDecode(data []byte) error {
	type operandType = bool
	if len(data) != 4 {
		return fmt.Errorf("EffectKind: invalid gob data length %d", len(data))
	}
	number := uint32(data[0])<<24 | uint32(data[1])<<16 | uint32(data[2])<<8 | uint32(data[3])
	tag := EffectKindTag(number)
	var operand operandType = uint32(tag) != number
	if !operand {
		operand = tag < EffectKindTagBoolean
	}
	var operand_1 operandType = operand
	if !operand_1 {
		operand_1 = tag > EffectKindTagResliceExtends
	}
	if operand_1 {
		return fmt.Errorf("EffectKind: cannot gob decode unknown tag %d", number)
	}
	switch tag {
	case EffectKindTagBoolean:
		*v = NewEffectKindBoolean()
	case EffectKindTagNonzero:
		*v = NewEffectKindNonzero()
	case EffectKindTagNonempty:
		*v = NewEffectKindNonempty()
	case EffectKindTagMapMiss:
		*v = NewEffectKindMapMiss()
	case EffectKindTagChannelClosed:
		*v = NewEffectKindChannelClosed()
	case EffectKindTagAssertionFails:
		*v = NewEffectKindAssertionFails()
	case EffectKindTagResliceExtends:
		*v = NewEffectKindResliceExtends()
	}
	return nil
}

// EffectKindBoolean is the Boolean payload.
type EffectKindBoolean struct{}

// NewEffectKindBoolean constructs EffectKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewEffectKindBoolean() EffectKind {
	return EffectKind{tgoTag: EffectKindTagBoolean}
}

// BooleanPayload requires Boolean. No tag check.
func (EffectKind) BooleanPayload() EffectKindBoolean { return EffectKindBoolean{} }

// EffectKindNonzero is the Nonzero payload.
type EffectKindNonzero struct{}

// NewEffectKindNonzero constructs EffectKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewEffectKindNonzero() EffectKind {
	return EffectKind{tgoTag: EffectKindTagNonzero}
}

// NonzeroPayload requires Nonzero. No tag check.
func (EffectKind) NonzeroPayload() EffectKindNonzero { return EffectKindNonzero{} }

// EffectKindNonempty is the Nonempty payload.
type EffectKindNonempty struct{}

// NewEffectKindNonempty constructs EffectKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewEffectKindNonempty() EffectKind {
	return EffectKind{tgoTag: EffectKindTagNonempty}
}

// NonemptyPayload requires Nonempty. No tag check.
func (EffectKind) NonemptyPayload() EffectKindNonempty { return EffectKindNonempty{} }

// EffectKindMapMiss is the MapMiss payload.
type EffectKindMapMiss struct{}

// NewEffectKindMapMiss constructs EffectKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewEffectKindMapMiss() EffectKind {
	return EffectKind{tgoTag: EffectKindTagMapMiss}
}

// MapMissPayload requires MapMiss. No tag check.
func (EffectKind) MapMissPayload() EffectKindMapMiss { return EffectKindMapMiss{} }

// EffectKindChannelClosed is the ChannelClosed payload.
type EffectKindChannelClosed struct{}

// NewEffectKindChannelClosed constructs EffectKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewEffectKindChannelClosed() EffectKind {
	return EffectKind{tgoTag: EffectKindTagChannelClosed}
}

// ChannelClosedPayload requires ChannelClosed. No tag check.
func (EffectKind) ChannelClosedPayload() EffectKindChannelClosed { return EffectKindChannelClosed{} }

// EffectKindAssertionFails is the AssertionFails payload.
type EffectKindAssertionFails struct{}

// NewEffectKindAssertionFails constructs EffectKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewEffectKindAssertionFails() EffectKind {
	return EffectKind{tgoTag: EffectKindTagAssertionFails}
}

// AssertionFailsPayload requires AssertionFails. No tag check.
func (EffectKind) AssertionFailsPayload() EffectKindAssertionFails { return EffectKindAssertionFails{} }

// EffectKindResliceExtends is the ResliceExtends payload.
type EffectKindResliceExtends struct{}

// NewEffectKindResliceExtends constructs EffectKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewEffectKindResliceExtends() EffectKind {
	return EffectKind{tgoTag: EffectKindTagResliceExtends}
}

// ResliceExtendsPayload requires ResliceExtends. No tag check.
func (EffectKind) ResliceExtendsPayload() EffectKindResliceExtends { return EffectKindResliceExtends{} }

func (v EffectKind) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case EffectKindTagBoolean:
		payload := v.BooleanPayload()
		return json.Marshal(struct {
			Payload EffectKindBoolean `json:"Boolean"`
		}{Payload: payload})
	case EffectKindTagNonzero:
		payload := v.NonzeroPayload()
		return json.Marshal(struct {
			Payload EffectKindNonzero `json:"Nonzero"`
		}{Payload: payload})
	case EffectKindTagNonempty:
		payload := v.NonemptyPayload()
		return json.Marshal(struct {
			Payload EffectKindNonempty `json:"Nonempty"`
		}{Payload: payload})
	case EffectKindTagMapMiss:
		payload := v.MapMissPayload()
		return json.Marshal(struct {
			Payload EffectKindMapMiss `json:"MapMiss"`
		}{Payload: payload})
	case EffectKindTagChannelClosed:
		payload := v.ChannelClosedPayload()
		return json.Marshal(struct {
			Payload EffectKindChannelClosed `json:"ChannelClosed"`
		}{Payload: payload})
	case EffectKindTagAssertionFails:
		payload := v.AssertionFailsPayload()
		return json.Marshal(struct {
			Payload EffectKindAssertionFails `json:"AssertionFails"`
		}{Payload: payload})
	case EffectKindTagResliceExtends:
		payload := v.ResliceExtendsPayload()
		return json.Marshal(struct {
			Payload EffectKindResliceExtends `json:"ResliceExtends"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid EffectKind JSON tag")
	}
}

func (v EffectKind) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case EffectKindTagBoolean:
		payload := v.BooleanPayload()
		return tgoEffectKindExternalJSONTo(out, "Boolean", payload)
	case EffectKindTagNonzero:
		payload := v.NonzeroPayload()
		return tgoEffectKindExternalJSONTo(out, "Nonzero", payload)
	case EffectKindTagNonempty:
		payload := v.NonemptyPayload()
		return tgoEffectKindExternalJSONTo(out, "Nonempty", payload)
	case EffectKindTagMapMiss:
		payload := v.MapMissPayload()
		return tgoEffectKindExternalJSONTo(out, "MapMiss", payload)
	case EffectKindTagChannelClosed:
		payload := v.ChannelClosedPayload()
		return tgoEffectKindExternalJSONTo(out, "ChannelClosed", payload)
	case EffectKindTagAssertionFails:
		payload := v.AssertionFailsPayload()
		return tgoEffectKindExternalJSONTo(out, "AssertionFails", payload)
	case EffectKindTagResliceExtends:
		payload := v.ResliceExtendsPayload()
		return tgoEffectKindExternalJSONTo(out, "ResliceExtends", payload)
	default:
		return fmt.Errorf("invalid EffectKind JSON tag")
	}
}

func (v *EffectKind) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	{
		err := json.Unmarshal(data, &object)
		if err != nil {
			return err
		}
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one EffectKind JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Boolean":
		var payload EffectKindBoolean
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindBoolean()
		return nil
	case "Nonzero":
		var payload EffectKindNonzero
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindNonzero()
		return nil
	case "Nonempty":
		var payload EffectKindNonempty
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindNonempty()
		return nil
	case "MapMiss":
		var payload EffectKindMapMiss
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindMapMiss()
		return nil
	case "ChannelClosed":
		var payload EffectKindChannelClosed
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindChannelClosed()
		return nil
	case "AssertionFails":
		var payload EffectKindAssertionFails
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindAssertionFails()
		return nil
	case "ResliceExtends":
		var payload EffectKindResliceExtends
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindResliceExtends()
		return nil
	default:
		return fmt.Errorf("unknown EffectKind JSON variant %q", variant)
	}
}

func (v *EffectKind) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	type operandType_1 = bool
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one EffectKind JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		type operandType = bool
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Boolean":
			current = 1
		case "Nonzero":
			current = 2
		case "Nonempty":
			current = 3
		case "MapMiss":
			current = 4
		case "ChannelClosed":
			current = 5
		case "AssertionFails":
			current = 6
		case "ResliceExtends":
			current = 7
		}
		var operand operandType = haveName
		if operand {
			operand = current == selected
		}
		same := operand
		var operand_1 operandType = same
		if operand_1 {
			operand_1 = current == 0
		}
		if operand_1 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		var operand_2 operandType = !multiple
		if operand_2 {
			operand_2 = current > 0
		}
		var operand_3 operandType = operand_2
		if operand_3 {
			operand_3 = current == selected
		}
		if operand_3 {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else {
			err := in.SkipValue()
			if err != nil {
				return err
			}
		}
	}
	{
		_, err := in.ReadToken()
		if err != nil {
			return err
		}
	}
	var operand_4 operandType_1 = !haveName
	if !operand_4 {
		operand_4 = multiple
	}
	if operand_4 {
		return fmt.Errorf("expected one EffectKind JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown EffectKind JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload EffectKindBoolean
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindBoolean()
		return nil
	case 2:
		var payload EffectKindNonzero
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindNonzero()
		return nil
	case 3:
		var payload EffectKindNonempty
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindNonempty()
		return nil
	case 4:
		var payload EffectKindMapMiss
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindMapMiss()
		return nil
	case 5:
		var payload EffectKindChannelClosed
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindChannelClosed()
		return nil
	case 6:
		var payload EffectKindAssertionFails
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindAssertionFails()
		return nil
	case 7:
		var payload EffectKindResliceExtends
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewEffectKindResliceExtends()
		return nil
	default:
		return fmt.Errorf("invalid EffectKind JSON tag")
	}
}

func booleanEffectCondition() EffectKind {
	return NewEffectKindBoolean()
}
func nonzeroEffectConditionKind() EffectKind {
	return NewEffectKindNonzero()
}
func nonemptyEffectCondition() EffectKind {
	return NewEffectKindNonempty()
}
func mapMissEffectCondition() EffectKind {
	return NewEffectKindMapMiss()
}
func closedChannelEffectCondition() EffectKind {
	return NewEffectKindChannelClosed()
}
func failedAssertionEffectCondition() EffectKind {
	return NewEffectKindAssertionFails()
}
func extendingResliceEffectCondition() EffectKind {
	return NewEffectKindResliceExtends()
}

// GenericEffect is a serializable condition for one type argument effect.

type GenericEffect struct {
	Receiver      bool
	TypeParameter int
	Conditions    []GenericEffectCondition
	MaySkip       bool
}

// GenericEffectCondition describes one value condition for a generic effect.

type GenericEffectCondition struct {
	ValueParameter int
	OtherParameter int
	Kind           EffectKind
	Expected       bool
}

type genericEffectSummary struct {
	function              *types.Func
	file                  *syntax.File
	declaration           *syntax.FunctionDeclaration
	parameters            map[*types.TypeParam]zeroParameter
	zeroEffects           []GenericEffect
	accessEffects         []GenericEffect
	returnedZeroEffects   []GenericEffect
	returnedAccessEffects []GenericEffect
	calls                 []*syntax.Expression
	reachable             map[syntax.Node]bool
	root                  *syntax.Node
	body                  *syntax.BlockStatement
}

// checkGenericZeroSafety exports generic zero facts and checks each use.
// checkGenericZeroSafety builds effect facts and checks each concrete call.
func (c *checker) checkGenericZeroSafety() {
	summaries := c.collectGenericZeroSummaries()
	c.propagateGenericZeroFacts(summaries)

	for _, summary := range summaries {
		fact := summary.fact()
		if fact.hasEffects() {
			c.pass.ExportObjectFact(summary.function, fact)
		}
	}

	bindings, sources := c.collectGenericValueBindings(summaries)
	for _, file := range c.files {
		if c.generated[file] {
			continue
		}
		inspectGenericFile(file, func(node *syntax.Node) bool {
			type operandType = bool
			expression, ok := syntax.ExpressionOf(node)
			if !ok {
				return true
			}
			if syntax.IdentifierExpressionOf(expression) != nil {
				c.reportBoundGenericValueUse(expression, bindings)
			}
			{
				call := syntax.CallExpressionOf(expression)
				if call != nil {
					c.reportGenericZeroCall(expression, summaries)
					c.reportReturnedGenericCall(expression, summaries, sources)
				}
			}
			var operand operandType = syntax.IndexExpressionOf(expression) != nil
			if !operand {
				operand = syntax.IndexListExpressionOf(expression) != nil
			}
			var operand_1 operandType = operand
			if !operand_1 {
				operand_1 = syntax.SelectorExpressionOf(expression) != nil
			}
			if operand_1 {
				c.reportDirectGenericValueEscape(expression, summaries, sources)
			}
			return true
		})
	}
}

// collectGenericZeroSummaries creates one local effect summary per generic function.
func (c *checker) collectGenericZeroSummaries() map[*types.Func]*genericEffectSummary {
	summaries := make(map[*types.Func]*genericEffectSummary)
	for _, file := range c.files {
		if c.generated[file] {
			continue
		}
		inspectGenericFile(file, func(node *syntax.Node) bool {
			type operandType = bool
			function, ok := syntax.FunctionDeclarationOf(node)
			var operand operandType = !ok
			if !operand {
				operand = function.Body == nil
			}
			if operand {
				return true
			}
			object, ok := c.facts.DefinitionName(function.Name).(*types.Func)
			if !ok {
				return false
			}
			signature, ok := object.Type().(*types.Signature)
			if !ok {
				return false
			}
			parameters := genericParameters(signature)
			if len(parameters) == 0 {
				return false
			}
			root := *node
			summary := &genericEffectSummary{
				function: object, file: file, declaration: function, parameters: parameters,
				zeroEffects: nil, accessEffects: nil, returnedZeroEffects: nil,
				returnedAccessEffects: nil, calls: nil,
				reachable: c.reachableNodes(function.Body), root: &root,
				body: function.Body,
			}
			c.collectDirectGenericZeros(summary)
			c.collectReturnedGenericEffects(summary)
			summaries[object] = summary
			return false
		})
	}
	return summaries
}

func genericParameters(signature *types.Signature) map[*types.TypeParam]zeroParameter {
	parameters := make(map[*types.TypeParam]zeroParameter)
	for index := 0; index < signature.RecvTypeParams().Len(); index++ {
		parameters[signature.RecvTypeParams().At(index)] = zeroParameter{
			receiver: true,
			index:    index,
		}
	}
	if signature.Recv() != nil {
		{
			named, ok := dereference(signature.Recv().Type()).(*types.Named)
			if ok {
				for index := 0; index < named.TypeArgs().Len(); index++ {
					parameter, ok := named.TypeArgs().At(index).(*types.TypeParam)
					if ok {
						parameters[parameter] = zeroParameter{receiver: true, index: index}
					}
				}
			}
		}
	}
	for index := 0; index < signature.TypeParams().Len(); index++ {
		parameters[signature.TypeParams().At(index)] = zeroParameter{
			receiver: false,
			index:    index,
		}
	}
	return parameters
}

// collectDirectGenericZeros records zero creation in one generic body.
func (c *checker) collectDirectGenericZeros(summary *genericEffectSummary) {
	c.collectGenericPresenceZeros(summary)
	c.collectNamedResultZeros(summary)
	c.collectGenericNodes(summary)
}

func (c *checker) collectGenericNodes(summary *genericEffectSummary) {
	inspectGenericBlock(summary.body, func(node *syntax.Node) bool {
		{
			_, nested := syntax.FunctionLiteralOf(node)
			if nested {
				return false
			}
		}
		{
			specification, ok := syntax.SpecificationOf(node)
			if ok {
				{
					value := syntax.ValueSpecificationOf(specification)
					if value != nil {
						c.collectValueSpecZeros(summary, node, value)
					}
				}
			}
		}
		expression, ok := syntax.ExpressionOf(node)
		if !ok {
			return true
		}
		{
			literal := syntax.CompositeLiteralOf(expression)
			if literal != nil {
				c.collectLiteralZeros(summary, expression, literal)
			}
		}
		{
			call := syntax.CallExpressionOf(expression)
			if call != nil {
				c.collectCallZeros(summary, expression, call)
				summary.calls = append(summary.calls, expression)
			}
		}
		{
			index := syntax.IndexExpressionOf(expression)
			if index != nil {
				c.collectMapReadZero(summary, expression, index)
			}
		}
		{
			unary := syntax.UnaryExpressionOf(expression)
			if unary != nil {
				type operandType = bool
				var operand operandType = unary.Operator == token.ARROW
				if operand {
					operand = !c.commaOK(expression)
				}
				if operand {
					c.markConditionalGenericZero(
						summary, node, firstType(c.facts.Type(expression)),
						closedChannelEffectCondition(), unary.Expression, nil,
					)
				}
			}
		}
		{
			slice := syntax.SliceExpressionOf(expression)
			if slice != nil {
				c.collectResliceZero(summary, expression, slice)
			}
		}
		{
			selector := syntax.SelectorExpressionOf(expression)
			if selector != nil {
				c.collectGenericAccess(summary, node, expression, selector)
			}
		}
		return true
	})
}

// collectReturnedGenericEffects records effects in a directly returned closure.
func (c *checker) collectReturnedGenericEffects(summary *genericEffectSummary) {
	inspectGenericBlock(summary.body, func(node *syntax.Node) bool {
		type operandType = bool
		{
			_, nested := syntax.FunctionLiteralOf(node)
			if nested {
				return false
			}
		}
		statement, ok := syntax.StatementOf(node)
		var operand operandType = !ok
		if !operand {
			operand = syntax.ReturnStatementOf(statement) == nil
		}
		if operand {
			return true
		}
		for _, expression := range syntax.ReturnStatementOf(statement).Results {
			value := unparenthesized(expression)
			literal := syntax.FunctionLiteralExpressionOf(value)
			if literal == nil {
				continue
			}
			root := syntax.ExpressionNode(value)
			returned := &genericEffectSummary{
				function: summary.function, file: summary.file,
				declaration: summary.declaration,
				parameters:  summary.parameters, zeroEffects: nil,
				accessEffects: nil, returnedZeroEffects: nil,
				returnedAccessEffects: nil, calls: nil,
				reachable: c.reachableNodes(literal.Body), root: &root,
				body: literal.Body,
			}
			c.collectGenericNodes(returned)
			summary.returnedZeroEffects = append(
				summary.returnedZeroEffects, returned.zeroEffects...,
			)
			summary.returnedAccessEffects = append(
				summary.returnedAccessEffects, returned.accessEffects...,
			)
		}
		return false
	})
}

// collectGenericPresenceZeros runs the normal pair proof for each type parameter.
// It records only pairs that discard or use a value before the ok proof.
// collectGenericPresenceZeros records zero values from failed presence operations.
func (c *checker) collectGenericPresenceZeros(summary *genericEffectSummary) {
	previousZeroTypes := c.zeroTypes
	previousCaptureResult := c.captureResult
	previousCaptureSource := c.captureSource
	previousChecked := c.checked
	previousPresence := c.presence
	defer func() {
		c.zeroTypes = previousZeroTypes
		c.captureResult = previousCaptureResult
		c.captureSource = previousCaptureSource
		c.checked = previousChecked
		c.presence = previousPresence
	}()

	for parameter, reference := range summary.parameters {
		currentModel := parameterModel()
		var sources []*syntax.Expression = nil
		c.zeroTypes = map[*types.TypeParam]*model{parameter: currentModel}
		record := func(candidate *model, source *syntax.Expression) {
			if source == nil {
				if candidate == currentModel {
					sources = append(sources, nil)
				}
				return
			}
			if candidate == currentModel {
				sources = append(sources, source)
			}
		}
		c.captureResult = func(candidate *model) { record(candidate, nil) }
		c.captureSource = record
		c.checked = make(map[*syntax.Expression]bool)
		c.presence = make(map[*syntax.Expression]bool)
		c.checkConstructors(summary.root, summary.body)
		for _, source := range sources {
			if source == nil {
				c.addGenericEffect(summary, true, reference, GenericEffect{
					Receiver: false, TypeParameter: 0, Conditions: nil, MaySkip: true,
				})
				continue
			}
			c.markGenericPresenceEffect(summary, source)
		}
	}
}

func (c *checker) markGenericPresenceEffect(
	summary *genericEffectSummary,
	source *syntax.Expression,
) {
	typ := firstType(c.facts.Type(source))
	{
		index := syntax.IndexExpressionOf(source)
		if index != nil {
			c.markConditionalGenericZero(
				summary, syntaxNode(source), typ, mapMissEffectCondition(),
				index.Expression, index.Index,
			)
		} else {
			unary := syntax.UnaryExpressionOf(source)
			if unary != nil {
				c.markConditionalGenericZero(
					summary, syntaxNode(source), typ, closedChannelEffectCondition(),
					unary.Expression, nil,
				)
			} else {
				assertion := syntax.TypeAssertionExpressionOf(source)
				if assertion != nil {
					c.markConditionalGenericZero(
						summary, syntaxNode(source), typ, failedAssertionEffectCondition(),
						assertion.Expression, nil,
					)
				} else {
					c.markGenericZeroWith(summary, syntaxNode(source), typ, nil, true)
				}
			}
		}
	}

}

func (c *checker) collectNamedResultZeros(summary *genericEffectSummary) {
	results := summary.declaration.Type.Results
	if results == nil {
		return
	}
	for _, field := range results.List {
		for _, name := range field.Names {
			{
				variable, ok := c.facts.DefinitionName(name).(*types.Var)
				if ok {
					c.markGenericZeroUnconditional(summary, variable.Type())
				}
			}
		}
	}
}

func (c *checker) markGenericZeroUnconditional(
	summary *genericEffectSummary,
	typ types.Type,
) {
	for parameter := range zeroTypeParameters(typ, summary.parameters, make(map[types.Type]bool)) {
		c.addGenericEffect(summary, true, parameter, noGenericEffect())
	}
}

func (c *checker) collectValueSpecZeros(
	summary *genericEffectSummary,
	node *syntax.Node,
	specification *syntax.ValueSpecification,
) {
	if len(specification.Values) != 0 {
		return
	}
	for _, name := range specification.Names {
		{
			variable, ok := c.facts.DefinitionName(name).(*types.Var)
			if ok {
				c.markGenericZeroAt(summary, node, variable.Type())
			}
		}
	}
}

// collectCallZeros records zero-producing built-ins and conversions.
func (c *checker) collectCallZeros(
	summary *genericEffectSummary,
	expression *syntax.Expression,
	call *syntax.CallExpression,
) {
	name := syntax.IdentifierExpressionOf(call.Callee)
	if name == nil {
		return
	}
	{
		_, ok := c.facts.Object(name).(*types.Builtin)
		if !ok {
			return
		}
	}
	switch name.Name {
	case "new":
		if len(call.Args) == 1 {
			c.markGenericZeroAt(summary, syntaxNode(expression), c.facts.Type(call.Args[0]))
		}
	case "make":
		c.collectMakeZeros(summary, expression, call)
	case "clear":
		if len(call.Args) != 1 {
			return
		}
		{
			slice, ok := coreType(c.facts.Type(call.Args[0])).(*types.Slice)
			if ok {
				c.markConditionalGenericZero(
					summary, syntaxNode(expression), slice.Elem(),
					nonemptyEffectCondition(), call.Args[0], nil,
				)
			}
		}
	}
}

func (c *checker) collectMakeZeros(
	summary *genericEffectSummary,
	expression *syntax.Expression,
	call *syntax.CallExpression,
) {
	if len(call.Args) < 2 {
		return
	}
	typeArgument := call.Args[0]
	if typeArgument == nil {
		return
	}
	slice, ok := coreType(c.facts.Type(typeArgument)).(*types.Slice)
	if !ok {
		return
	}
	lengthArgument := call.Args[1]
	if lengthArgument == nil {
		return
	}
	condition, outcome := c.nonzeroEffectCondition(lengthArgument)
	if outcome == neverEffectOutcome() {
		return
	}
	if outcome == alwaysEffectOutcome() {
		c.markGenericZeroAt(summary, syntaxNode(expression), slice.Elem())
		return
	}
	if outcome == conditionalEffectOutcome() {
		if condition == nil {
			return
		}
		c.markGenericZeroWith(summary, syntaxNode(expression), slice.Elem(), condition, false)
		return
	}
	c.markGenericZeroWith(summary, syntaxNode(expression), slice.Elem(), nil, true)
}

func (c *checker) collectMapReadZero(
	summary *genericEffectSummary,
	expression *syntax.Expression,
	index *syntax.IndexExpression,
) {
	if c.assignmentTarget(expression) {
		return
	}
	if c.commaOK(expression) {
		return
	}
	mapping, ok := coreType(c.facts.Type(index.Expression)).(*types.Map)
	if ok {
		c.markConditionalGenericZero(
			summary, syntaxNode(expression), mapping.Elem(), mapMissEffectCondition(),
			index.Expression, index.Index,
		)
	}
}

func (c *checker) collectResliceZero(
	summary *genericEffectSummary,
	value *syntax.Expression,
	expression *syntax.SliceExpression,
) {
	type operandType = bool
	if expression.High == nil {
		return
	}
	var operand operandType = c.currentLength(expression.High, expression.Expression)
	if !operand {
		operand = constantZero(c.facts.Constant(expression.High))
	}
	if operand {
		return
	}
	slice, ok := coreType(c.facts.Type(expression.Expression)).(*types.Slice)
	if ok {
		c.markConditionalGenericZero(
			summary, syntaxNode(value), slice.Elem(), extendingResliceEffectCondition(),
			expression.Expression, expression.High,
		)
	}
}

func (c *checker) collectGenericAccess(
	summary *genericEffectSummary,
	node *syntax.Node,
	expression *syntax.Expression,
	selector *syntax.SelectorExpression,
) {
	type operandType = bool
	var operand operandType = !strings.HasPrefix(selector.Selector.Name, "Tgo")
	if !operand {
		operand = !c.receiverCanHideModel(c.facts.Type(selector.Expression))
	}
	if operand {
		return
	}
	{
		selection := c.facts.Selection(expression)
		if selection == nil {
			return
		} else {
			_, ok := selection.Obj().(*types.Func)
			if !ok {
				return
			}
		}
	}
	c.markGenericAccessAt(summary, node, c.facts.Type(selector.Expression))
}

func noGenericEffect() GenericEffect {
	return GenericEffect{
		Receiver: false, TypeParameter: 0, Conditions: nil, MaySkip: false,
	}
}
