// Code generated by tgo. DO NOT EDIT.

package tgolint

import (
	"bytes"
	"encoding/gob"
	"testing"
)

func TestGenericEffectFactGobRoundTrip(t *testing.T) {
	t.Parallel()
	want := &GenericEffectFact{
		Version: 1,
		Storage: StorageEffectGraph{Known: true, Entry: 0,
			Functions: []StorageEffectFunction{{
				ID: 0, Captures: nil, ZeroEffects: nil, AccessEffects: nil,
				Blocks: []StorageEffectBlock{{
					ID: 0,
					Operations: []StorageEffectOperation{{
						Kind: storageEffectCall, Position: 7,
						Target: StorageEffectRegion{}, Source: StorageEffectRegion{},
						Regions: nil, Inputs: nil, Results: nil, Function: -1,
						TypeArguments: []StorageEffectType{{
							Kind: storageTypeSlice, Element: []StorageEffectType{{
								Kind: storageTypeParameter, Parameter: 1,
							}},
						}},
						Field: "", Length: 0, Capacity: 0,
						KnownLength: false, KnownCapacity: false,
						ZeroEffects: nil, AccessEffects: nil,
					}},
					Successors: nil,
				}},
			}},
		},
		ZeroEffects: []GenericEffect{{
			Receiver:      false,
			TypeParameter: 1,
			Conditions: []GenericEffectCondition{{
				ValueParameter: 2,
				OtherParameter: -1,
				Kind:           NewEffectKindBoolean(),
				Expected:       true,
			}},
			MaySkip: false,
		}},
		AccessEffects:         nil,
		ReturnedZeroEffects:   nil,
		ReturnedAccessEffects: nil,
		ReturnedZeroEffectsAtDepth: []GenericEffectAtDepth{{
			CallDepth: 2,
			Effect: GenericEffect{
				Receiver: false, TypeParameter: 0,
				Conditions: nil, MaySkip: true,
			},
		}},
		ReturnedAccessEffectsAtDepth: nil,
	}
	data := *new(bytes.Buffer)
	if err := gob.NewEncoder(&data).Encode(want); err != nil {
		t.Fatal(err)
	}
	got := new(GenericEffectFact)
	if err := gob.NewDecoder(&data).Decode(got); err != nil {
		t.Fatal(err)
	}
	if len(got.ZeroEffects) != 1 || len(got.ZeroEffects[0].Conditions) != 1 {
		t.Fatalf("decoded fact = %#v", got)
	}
	if got.Version != 1 || !got.Storage.Known ||
		len(got.Storage.Functions) != 1 ||
		got.Storage.Functions[0].Blocks[0].Operations[0].Position != 7 {
		t.Fatalf("decoded storage fact = %#v", got.Storage)
	}
	if len(got.ReturnedZeroEffectsAtDepth) != 1 ||
		got.ReturnedZeroEffectsAtDepth[0].CallDepth != 2 ||
		!got.ReturnedZeroEffectsAtDepth[0].Effect.MaySkip {
		t.Fatalf("decoded returned fact = %#v", got.ReturnedZeroEffectsAtDepth)
	}
	condition := got.ZeroEffects[0].Conditions[0]
	if condition.Kind.Tag() != EffectKindTagBoolean || !condition.Expected ||
		condition.ValueParameter != 2 || condition.OtherParameter != -1 {
		t.Fatalf("decoded condition = %#v", condition)
	}
}

func TestRecursiveStorageGraphCompletesWithEffects(t *testing.T) {
	t.Parallel()
	fact := &GenericEffectFact{Version: 1}
	fact.Storage = StorageEffectGraph{
		Known: true, Entry: 0,
		Functions: []StorageEffectFunction{{
			ID:          0,
			ZeroEffects: []GenericEffect{{TypeParameter: 0}},
			Blocks: []StorageEffectBlock{
				{ID: 0, Successors: []StorageEffectEdge{{Block: 1}, {Block: 2}}},
				{ID: 1},
				{ID: 2, Operations: []StorageEffectOperation{{
					Kind: storageEffectCall, Function: 0,
				}}},
			},
		}},
	}
	effects := storageGraphEffects(storageGraphCall{
		fact: fact, function: 0,
	}, newStorageState())
	if !effects.completed || len(effects.zero) != 1 {
		t.Fatalf("recursive effects = %#v", effects)
	}
}

func TestAcyclicStorageTransferIsCached(t *testing.T) {
	t.Parallel()
	fact := &GenericEffectFact{Version: 1, Storage: StorageEffectGraph{
		Known: true, Entry: 0,
		Functions: []StorageEffectFunction{{ID: 0, Blocks: []StorageEffectBlock{{ID: 0}}}},
	}}
	context := newStorageExecutionContext()
	call := storageGraphCall{fact: fact, function: 0}
	_, _, first := executeStorageFunction(call, newStorageState(), context)
	_, _, second := executeStorageFunction(call, newStorageState(), context)
	if !first.completed || !second.completed || len(context.completed) != 1 {
		t.Fatalf("completed transfers = %#v", context.completed)
	}
}

func TestCompletedStorageKeyKeepsExactSliceBounds(t *testing.T) {
	t.Parallel()
	fact := &GenericEffectFact{Version: 1, Storage: StorageEffectGraph{
		Known: true, Entry: 0,
		Functions: []StorageEffectFunction{{ID: 0}},
	}}
	call := storageGraphCall{fact: fact, function: 0}
	left := storageValue{slices: []storageSlice{{
		length: 2, knownLength: true,
	}}}
	right := storageValue{slices: []storageSlice{{
		length: 3, knownLength: true,
	}}}
	call.arguments = []storageValue{left}
	leftExact := storageCallInputKey(call, newStorageState(), false)
	leftAbstract := storageCallInputKey(call, newStorageState(), true)
	call.arguments = []storageValue{right}
	rightExact := storageCallInputKey(call, newStorageState(), false)
	rightAbstract := storageCallInputKey(call, newStorageState(), true)
	if leftExact == rightExact || leftAbstract != rightAbstract {
		t.Fatalf("slice keys: exact %q %q; abstract %q %q",
			leftExact, rightExact, leftAbstract, rightAbstract)
	}
}

func TestRecursiveStorageExecutionNormalizesSliceBounds(t *testing.T) {
	t.Parallel()
	fact := &GenericEffectFact{Version: 1}
	fact.Storage = StorageEffectGraph{
		Known: true, Entry: 0,
		Functions: []StorageEffectFunction{{
			ID: 0,
			Blocks: []StorageEffectBlock{
				{ID: 0, Successors: []StorageEffectEdge{{Block: 1}, {Block: 2}}},
				{ID: 1},
				{ID: 2, Operations: []StorageEffectOperation{
					{Kind: storageEffectRead, Source: StorageEffectRegion{
						Root: storageRootParameter, ID: 0,
					}, Results: []int{1}},
					{Kind: storageEffectCall, Function: 0, Inputs: []int{1, 1}},
				}},
			},
		}},
	}
	context := newStorageExecutionContext()
	call := storageGraphCall{fact: fact, function: 0}
	for _, length := range []int64{0, 2, 3} {
		call.arguments = []storageValue{{slices: []storageSlice{{
			length: length, knownLength: true,
		}}}}
		_, _, effects := executeStorageFunction(call, newStorageState(), context)
		if !effects.completed {
			t.Fatalf("recursive length %d did not complete", length)
		}
	}
	if len(context.completed) != 2 {
		t.Fatalf("completed recursive inputs = %#v", context.completed)
	}
}

func TestStorageAllocationIdentityIncludesCallerSite(t *testing.T) {
	t.Parallel()
	fact := &GenericEffectFact{Version: 1, Storage: StorageEffectGraph{Known: true}}
	operation := StorageEffectOperation{
		Kind:    storageEffectAllocate,
		Target:  StorageEffectRegion{Root: storageRootAllocation, ID: 4},
		Results: []int{1},
	}
	left := &storageExecutionState{storage: newStorageState(), temps: make(map[int]storageValue)}
	right := &storageExecutionState{storage: newStorageState(), temps: make(map[int]storageValue)}
	applyStorageOperation(left, storageGraphCall{
		fact: fact, function: 0, caller: fact, callerGraph: 1, callSite: 10,
	}, operation, newStorageExecutionContext())
	applyStorageOperation(right, storageGraphCall{
		fact: fact, function: 0, caller: fact, callerGraph: 1, callSite: 20,
	}, operation, newStorageExecutionContext())
	leftLocation := left.temps[1].regions[0].location
	rightLocation := right.temps[1].regions[0].location
	if leftLocation == rightLocation {
		t.Fatalf("factory allocations share location %#v", leftLocation)
	}
}

func TestStorageBirthMovesRecentReferencesToSummary(t *testing.T) {
	t.Parallel()
	fact := &GenericEffectFact{Version: 1, Storage: StorageEffectGraph{Known: true}}
	call := storageGraphCall{
		fact: fact, function: 0, allocationRoute: "factory",
	}
	state := newStorageState()
	first := storageBirthLocation(&state, &call, storageRootAllocation, 4)
	value := storageValue{
		regions: []storagePath{{location: first}},
		slices:  []storageSlice{{backing: first}},
		functions: []storageFunction{{
			captures: []storagePath{{location: first}},
		}},
	}
	state.memory[storageMemoryKey(storagePath{location: first})] = value
	call.arguments = []storageValue{value}
	call.captures = []storagePath{{location: first}}
	second := storageBirthLocation(&state, &call, storageRootAllocation, 4)
	if second.generation != storageGenerationRecent {
		t.Fatalf("birth locations = %#v, %#v", first, second)
	}
	summary := first
	summary.generation = storageGenerationSummary
	summary.merged = true
	if _, ok := state.memory[storageMemoryKey(storagePath{location: summary})]; !ok {
		t.Fatalf("summary memory is absent: %#v", state.memory)
	}
	argument := call.arguments[0]
	if argument.regions[0].location != summary ||
		argument.slices[0].backing != summary ||
		argument.functions[0].captures[0].location != summary ||
		call.captures[0].location != summary {
		t.Fatalf("old recent references were not renamed: %#v %#v", argument, call.captures)
	}
}

func TestCachedStorageFactoryReplaysBirth(t *testing.T) {
	t.Parallel()
	fact := &GenericEffectFact{Version: 1}
	fact.Storage = StorageEffectGraph{
		Known: true, Entry: 0,
		Functions: []StorageEffectFunction{{
			ID: 0,
			Blocks: []StorageEffectBlock{{ID: 0, Operations: []StorageEffectOperation{
				{
					Kind: storageEffectAllocate,
					Target: StorageEffectRegion{
						Root: storageRootAllocation, ID: 1,
					},
					Results: []int{1},
				},
				{Kind: storageEffectReturn, Inputs: []int{1}},
			}}},
		}},
	}
	context := newStorageExecutionContext()
	call := storageGraphCall{
		fact: fact, function: 0, allocationRoute: "cached-factory",
	}
	state, first, _ := executeStorageFunction(call, newStorageState(), context)
	firstPath := storagePath{location: first[0].regions[0].location}
	state.memory[storageMemoryKey(firstPath)] = first[0]
	state, second, _ := executeStorageFunction(call, state, context)
	firstLocation := first[0].regions[0].location
	secondLocation := second[0].regions[0].location
	if firstLocation.generation != storageGenerationRecent ||
		secondLocation.generation != storageGenerationRecent {
		t.Fatalf("factory returns = %#v, %#v", first, second)
	}
	summary := firstLocation
	summary.generation = storageGenerationSummary
	summary.merged = true
	if _, ok := state.memory[storageMemoryKey(storagePath{location: summary})]; !ok {
		t.Fatalf("factory summary is absent: %#v", state.memory)
	}
}

func TestStorageEffectProjectionDoesNotMutateConditions(t *testing.T) {
	t.Parallel()
	effects := []GenericEffect{{
		TypeParameter: 0,
		Conditions: []GenericEffectCondition{{
			ValueParameter: 0, OtherParameter: 1,
		}},
	}}
	projected := projectStorageEffects(effects, nil, []StorageEffectType{{
		Kind: storageTypeParameter, Parameter: 1,
	}}, []int{2, 3})
	if effects[0].Conditions[0].ValueParameter != 0 ||
		effects[0].Conditions[0].OtherParameter != 1 {
		t.Fatalf("source conditions changed: %#v", effects)
	}
	if projected[0].Conditions[0].ValueParameter != 2 ||
		projected[0].Conditions[0].OtherParameter != 3 {
		t.Fatalf("projected conditions = %#v", projected)
	}
}

func TestStorageIndexWriteIsWeakForAlternativeTargets(t *testing.T) {
	t.Parallel()
	state := newStorageState()
	left := storageLocation{graph: 1, site: 1}
	right := storageLocation{graph: 1, site: 2}
	leftPath := storageMemoryKey(storagePath{location: left, steps: []StorageEffectPath{{
		Kind: storagePathIndex, Index: 0,
	}}})
	rightPath := storageMemoryKey(storagePath{location: right, steps: []StorageEffectPath{{
		Kind: storagePathIndex, Index: 0,
	}}})
	writeStorageMemory(state, leftPath, storageValue{integer: 1, integerKnown: true}, true)
	writeStorageMemory(state, rightPath, storageValue{integer: 2, integerKnown: true}, true)
	writeStorageIndex(state, storageValue{slices: []storageSlice{
		{backing: left, knownOffset: true},
		{backing: right, knownOffset: true},
	}}, StorageEffectOperation{KnownLength: true}, storageValue{
		integer: 3, integerKnown: true,
	})
	if state.memory[leftPath].integerKnown || state.memory[rightPath].integerKnown {
		t.Fatalf("alternative target write was strong: %#v", state.memory)
	}
}

func TestStorageIndexUsesRuntimeInteger(t *testing.T) {
	t.Parallel()
	operation := storageIndexOperation(map[int]storageValue{
		2: {integer: 4, integerKnown: true},
	}, StorageEffectOperation{Inputs: []int{1, 2}})
	if !operation.KnownLength || operation.Length != 4 {
		t.Fatalf("index operation = %#v", operation)
	}
}

func TestStorageIndexKeepsEncodedIntegerWithoutTemp(t *testing.T) {
	t.Parallel()
	operation := storageIndexOperation(map[int]storageValue{}, StorageEffectOperation{
		Inputs: []int{1, 0}, Length: 4, KnownLength: true,
	})
	if !operation.KnownLength || operation.Length != 4 {
		t.Fatalf("index operation = %#v", operation)
	}
}

func TestStorageZeroResliceKeepsUnknownOffset(t *testing.T) {
	t.Parallel()
	value := resliceStorageValue(storageValue{slices: []storageSlice{{
		offset: 3, knownOffset: false,
	}}}, StorageEffectOperation{KnownOffset: true})
	if value.slices[0].knownOffset {
		t.Fatalf("reslice restored unknown offset: %#v", value)
	}
}

func TestStorageUnknownSliceOffsetReadsWildcard(t *testing.T) {
	t.Parallel()
	state := newStorageState()
	backing := storageLocation{graph: 1, site: 1}
	path := storageMemoryKey(storagePath{location: backing, steps: []StorageEffectPath{{
		Kind: storagePathIndex, Index: 3,
	}}})
	want := storageValue{integer: 7, integerKnown: true}
	writeStorageMemory(state, path, want, true)
	got := readStorageIndex(state, storageValue{slices: []storageSlice{{
		backing: backing, knownOffset: false,
	}}}, StorageEffectOperation{Length: 0, KnownLength: true})
	if !got.integerKnown || got.integer != want.integer {
		t.Fatalf("wildcard read = %#v", got)
	}
}

func TestStorageIndexDeduplicatesOneDestination(t *testing.T) {
	t.Parallel()
	state := newStorageState()
	location := storageLocation{graph: 1, site: 1}
	path := storagePath{location: location}
	indexed := storageMemoryKey(storagePath{
		location: location,
		steps:    []StorageEffectPath{{Kind: storagePathIndex, Index: 0}},
	})
	writeStorageMemory(state, indexed, storageValue{integer: 1, integerKnown: true}, true)
	writeStorageIndex(state, storageValue{
		regions: []storagePath{path},
		slices:  []storageSlice{{backing: location, knownOffset: true}},
	}, StorageEffectOperation{KnownLength: true}, storageValue{
		integer: 3, integerKnown: true,
	})
	if got := state.memory[indexed]; !got.integerKnown || got.integer != 3 {
		t.Fatalf("deduplicated write = %#v", got)
	}
}

func TestStorageCopyJoinsAlternativeSourcesBeforeWrite(t *testing.T) {
	t.Parallel()
	state := newStorageState()
	destination := storageLocation{graph: 1, site: 1}
	left := storageLocation{graph: 1, site: 2}
	right := storageLocation{graph: 1, site: 3}
	indexPath := func(location storageLocation) storagePathKey {
		return storageMemoryKey(storagePath{
			location: location,
			steps:    []StorageEffectPath{{Kind: storagePathIndex, Index: 0}},
		})
	}
	writeStorageMemory(state, indexPath(left), storageValue{
		integer: 1, integerKnown: true,
	}, true)
	writeStorageMemory(state, indexPath(right), storageValue{
		integer: 2, integerKnown: true,
	}, true)
	copyStorageSlices(state,
		storageValue{slices: []storageSlice{{
			backing: destination, length: 1,
			knownOffset: true, knownLength: true,
		}}},
		storageValue{slices: []storageSlice{
			{backing: left, length: 1, knownOffset: true, knownLength: true},
			{backing: right, length: 1, knownOffset: true, knownLength: true},
		}},
	)
	if got := state.memory[indexPath(destination)]; got.integerKnown {
		t.Fatalf("alternative source copy = %#v", got)
	}
}
