// Code generated by tgo. DO NOT EDIT.
//tgo:v2 "models.tgo"

package tgolint

import __tgo_json "encoding/json"
import __tgo_jsonv2 "encoding/json/v2"
import __tgo_jsontext "encoding/json/jsontext"
import __tgo_fmt "fmt"

func __tgo_model_external_json_to[T interface{}](out *__tgo_jsontext.Encoder, name string, payload T) error {
	if err := out.WriteToken(__tgo_jsontext.BeginObject); err != nil {
		return err
	}
	if err := out.WriteToken(__tgo_jsontext.String(name)); err != nil {
		return err
	}
	if err := __tgo_jsonv2.MarshalEncode(out, payload); err != nil {
		return err
	}
	return out.WriteToken(__tgo_jsontext.EndObject)
}

// model requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type modelTag uint8

const (
	modelTagChecked modelTag = iota + 1
	modelTagEnum
	modelTagMixed
	modelTagParameter
)

type model struct {
	tgoTag     modelTag
	tgoChecked modelChecked
	tgoPayload interface{}
}

// Tag returns the active tag.
func (v model) Tag() modelTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v model) UnknownTag() string {
	return __tgo_fmt.Sprintf("model: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// modelChecked is the Checked payload.
type modelChecked struct {
	Package string
	Name    string
}

// model constructs model. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value modelChecked) model() model {
	return model{tgoTag: modelTagChecked, tgoChecked: value}
}

// CheckedPayload requires Checked. No tag check.
func (v model) CheckedPayload() modelChecked { return v.tgoChecked }

// modelEnum is the Enum payload.
type modelEnum struct {
	Package  string
	Name     string
	Variants []string
}

// model constructs model. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value modelEnum) model() model {
	return model{tgoTag: modelTagEnum, tgoPayload: value}
}

// EnumPayload requires Enum. No tag check.
func (v model) EnumPayload() modelEnum { return v.tgoPayload.(modelEnum) }

// modelMixed is the Mixed payload.
type modelMixed struct{}

// model constructs model. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value modelMixed) model() model {
	return model{tgoTag: modelTagMixed}
}

// MixedPayload requires Mixed. No tag check.
func (model) MixedPayload() modelMixed { return modelMixed{} }

// modelParameter is the Parameter payload.
type modelParameter struct{}

// model constructs model. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value modelParameter) model() model {
	return model{tgoTag: modelTagParameter}
}

// ParameterPayload requires Parameter. No tag check.
func (model) ParameterPayload() modelParameter { return modelParameter{} }

func (v model) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case modelTagChecked:
		payload := v.CheckedPayload()
		return __tgo_json.Marshal(struct {
			Payload modelChecked `json:"Checked"`
		}{Payload: payload})
	case modelTagEnum:
		payload := v.EnumPayload()
		return __tgo_json.Marshal(struct {
			Payload modelEnum `json:"Enum"`
		}{Payload: payload})
	case modelTagMixed:
		payload := v.MixedPayload()
		return __tgo_json.Marshal(struct {
			Payload modelMixed `json:"Mixed"`
		}{Payload: payload})
	case modelTagParameter:
		payload := v.ParameterPayload()
		return __tgo_json.Marshal(struct {
			Payload modelParameter `json:"Parameter"`
		}{Payload: payload})
	default:
		return nil, __tgo_fmt.Errorf("invalid model JSON tag")
	}
}

func (v model) MarshalJSONTo(out *__tgo_jsontext.Encoder) error {
	switch v.tgoTag {
	case modelTagChecked:
		payload := v.CheckedPayload()
		return __tgo_model_external_json_to(out, "Checked", payload)
	case modelTagEnum:
		payload := v.EnumPayload()
		return __tgo_model_external_json_to(out, "Enum", payload)
	case modelTagMixed:
		payload := v.MixedPayload()
		return __tgo_model_external_json_to(out, "Mixed", payload)
	case modelTagParameter:
		payload := v.ParameterPayload()
		return __tgo_model_external_json_to(out, "Parameter", payload)
	default:
		return __tgo_fmt.Errorf("invalid model JSON tag")
	}
}

func (v *model) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]__tgo_json.RawMessage
	if err := __tgo_json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return __tgo_fmt.Errorf("expected one model JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Checked":
		var payload modelChecked
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.model()
		return nil
	case "Enum":
		var payload modelEnum
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.model()
		return nil
	case "Mixed":
		var payload modelMixed
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.model()
		return nil
	case "Parameter":
		var payload modelParameter
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.model()
		return nil
	default:
		return __tgo_fmt.Errorf("unknown model JSON variant %q", variant)
	}
}

func (v *model) UnmarshalJSONFrom(in *__tgo_jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return __tgo_fmt.Errorf("expected one model JSON variant")
	}
	var payloadData __tgo_jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Checked":
			current = 1
		case "Enum":
			current = 2
		case "Mixed":
			current = 3
		case "Parameter":
			current = 4
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return __tgo_fmt.Errorf("expected one model JSON variant")
	}
	if selected == 0 {
		return __tgo_fmt.Errorf("unknown model JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload modelChecked
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.model()
		return nil
	case 2:
		var payload modelEnum
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.model()
		return nil
	case 3:
		var payload modelMixed
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.model()
		return nil
	case 4:
		var payload modelParameter
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.model()
		return nil
	default:
		return __tgo_fmt.Errorf("invalid model JSON tag")
	}
}

// modelWireFact is the stable fact format used by go/analysis.
// The checker decodes it before it uses the model.

type modelWireFact struct {
	Kind     uint8
	Package  string
	Name     string
	Variants []string
}

// AFact marks modelWireFact as a Go analysis fact.
func (*modelWireFact) AFact() {}

const (
	checkedModelWire uint8 = 1
	enumModelWire    uint8 = 2
)

func checkedModel(packagePath string, name string) *model {
	value := modelChecked{Package: packagePath, Name: name}.model()
	return &value
}

func enumModel(packagePath string, name string, variants []string) *model {
	value := modelEnum{
		Package: packagePath, Name: name, Variants: variants,
	}.model()
	return &value
}

func mixedModel() *model {
	value := modelMixed{}.model()
	return &value
}

func parameterModel() *model {
	value := modelParameter{}.model()
	return &value
}

func modelDescription(value *model) (string, string) {
	if value == nil {
		return "", ""
	}
	switch enumValue13 := *value; enumValue13.Tag() {
	case modelTagChecked:
		checked := enumValue13.CheckedPayload()
		return "checked", checked.Name
	case modelTagEnum:
		enum := enumValue13.EnumPayload()
		return "enum", enum.Name
	case modelTagMixed:
		return "", ""
	case modelTagParameter:
		return "generic", "type argument"
	default:
		panic(enumValue13.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func modelKind(value *model) string {
	kind, _ := modelDescription(value)
	return kind
}

func modelName(value *model) string {
	_, name := modelDescription(value)
	return name
}

func modelPackage(value *model) string {
	if value == nil {
		return ""
	}
	switch enumValue14 := *value; enumValue14.Tag() {
	case modelTagChecked:
		checked := enumValue14.CheckedPayload()
		return checked.Package
	case modelTagEnum:
		enum := enumValue14.EnumPayload()
		return enum.Package
	case modelTagMixed:
		return ""
	case modelTagParameter:
		return ""
	default:
		panic(enumValue14.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func modelVariants(value *model) []string {
	if value == nil {
		return nil
	}
	switch enumValue15 := *value; enumValue15.Tag() {
	case modelTagChecked:
		return nil
	case modelTagEnum:
		enum := enumValue15.EnumPayload()
		return enum.Variants
	case modelTagMixed:
		return nil
	case modelTagParameter:
		return nil
	default:
		panic(enumValue15.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func modelIsChecked(value *model) bool {
	if value == nil {
		return false
	}
	switch enumValue16 := *value; enumValue16.Tag() {
	case modelTagChecked:
		return true
	case modelTagEnum:
		return false
	case modelTagMixed:
		return false
	case modelTagParameter:
		return false
	default:
		panic(enumValue16.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func modelIsEnum(value *model) bool {
	if value == nil {
		return false
	}
	switch enumValue17 := *value; enumValue17.Tag() {
	case modelTagChecked:
		return false
	case modelTagEnum:
		return true
	case modelTagMixed:
		return false
	case modelTagParameter:
		return false
	default:
		panic(enumValue17.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func modelIsMixed(value *model) bool {
	if value == nil {
		return false
	}
	switch enumValue18 := *value; enumValue18.Tag() {
	case modelTagChecked:
		return false
	case modelTagEnum:
		return false
	case modelTagMixed:
		return true
	case modelTagParameter:
		return false
	default:
		panic(enumValue18.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func sameModel(left *model, right *model) bool {
	if left == nil || right == nil {
		return left == right
	}
	if modelIsChecked(left) {
		return modelIsChecked(right) && modelPackage(left) == modelPackage(right) &&
			modelName(left) == modelName(right)
	}
	if modelIsEnum(left) {
		return modelIsEnum(right) && modelPackage(left) == modelPackage(right) &&
			modelName(left) == modelName(right)
	}
	if modelIsMixed(left) {
		return modelIsMixed(right)
	}
	return modelIsParameter(right)
}

func modelIsParameter(value *model) bool {
	if value == nil {
		return false
	}
	switch enumValue19 := *value; enumValue19.Tag() {
	case modelTagChecked:
		return false
	case modelTagEnum:
		return false
	case modelTagMixed:
		return false
	case modelTagParameter:
		return true
	default:
		panic(enumValue19.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

// encodeModelFact converts the internal ADT to its package fact form.
func encodeModelFact(value *model) *modelWireFact {
	if value == nil {
		return nil
	}
	switch enumValue20 := *value; enumValue20.Tag() {
	case modelTagChecked:
		checked := enumValue20.CheckedPayload()
		return &modelWireFact{
			Kind: checkedModelWire, Package: checked.Package,
			Name: checked.Name, Variants: nil,
		}
	case modelTagEnum:
		enum := enumValue20.EnumPayload()
		return &modelWireFact{
			Kind: enumModelWire, Package: enum.Package, Name: enum.Name,
			Variants: append([]string(nil), enum.Variants...),
		}
	case modelTagMixed:
		return nil
	case modelTagParameter:
		return nil
	default:
		panic(enumValue20.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

// decodeModelFact validates a wire fact before it enters the checker.
func decodeModelFact(fact *modelWireFact, expectedPackage string) *model {
	if fact == nil || fact.Package != expectedPackage || fact.Name == "" {
		return nil
	}
	switch fact.Kind {
	case checkedModelWire:
		if len(fact.Variants) == 0 {
			return checkedModel(fact.Package, fact.Name)
		}
	case enumModelWire:
		if len(fact.Variants) != 0 {
			return enumModel(
				fact.Package, fact.Name, append([]string(nil), fact.Variants...),
			)
		}
	}
	return nil
}
