// Code generated by tgo. DO NOT EDIT.

package tgolint

import __tgo_json "encoding/json"
import __tgo_jsonv2 "encoding/json/v2"
import __tgo_jsontext "encoding/json/jsontext"
import __tgo_fmt "fmt"

import "go/types"

// Go types stores T. nilType stores the current union of T and nil.
// Optional is T | nil. Never is an impossible value.
func __tgo_nilType_external_json_to[T interface{}](out *__tgo_jsontext.Encoder, name string, payload T) error {
	if err := out.WriteToken(__tgo_jsontext.BeginObject); err != nil {
		return err
	}
	if err := out.WriteToken(__tgo_jsontext.String(name)); err != nil {
		return err
	}
	if err := __tgo_jsonv2.MarshalEncode(out, payload); err != nil {
		return err
	}
	return out.WriteToken(__tgo_jsontext.EndObject)
}

// nilType requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type nilTypeTag uint8

const (
	nilTypeTagNever nilTypeTag = iota + 1
	nilTypeTagNonNil
	nilTypeTagNil
	nilTypeTagOptional
)

type nilType struct {
	tgoTag nilTypeTag
}

// Tag returns the active tag.
func (v nilType) Tag() nilTypeTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v nilType) UnknownTag() string {
	return __tgo_fmt.Sprintf("nilType: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// GobEncode returns the stable four-byte enum tag.
func (v nilType) GobEncode() ([]byte, error) {
	if v.tgoTag < nilTypeTagNever || v.tgoTag > nilTypeTagOptional {
		return nil, __tgo_fmt.Errorf("nilType: cannot gob encode invalid tag %d", v.tgoTag)
	}
	tag := uint32(v.tgoTag)
	return []byte{byte(tag >> 24), byte(tag >> 16), byte(tag >> 8), byte(tag)}, nil
}

// GobDecode replaces the value with a valid four-byte enum tag.
func (v *nilType) GobDecode(data []byte) error {
	if len(data) != 4 {
		return __tgo_fmt.Errorf("nilType: invalid gob data length %d", len(data))
	}
	number := uint32(data[0])<<24 | uint32(data[1])<<16 | uint32(data[2])<<8 | uint32(data[3])
	tag := nilTypeTag(number)
	if uint32(tag) != number || tag < nilTypeTagNever || tag > nilTypeTagOptional {
		return __tgo_fmt.Errorf("nilType: cannot gob decode unknown tag %d", number)
	}
	*v = nilType{tgoTag: tag}
	return nil
}

// nilTypeNever is the Never payload.
type nilTypeNever struct{}

// nilType constructs nilType. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value nilTypeNever) nilType() nilType {
	return nilType{tgoTag: nilTypeTagNever}
}

// NeverPayload requires Never. No tag check.
func (nilType) NeverPayload() nilTypeNever { return nilTypeNever{} }

// nilTypeNonNil is the NonNil payload.
type nilTypeNonNil struct{}

// nilType constructs nilType. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value nilTypeNonNil) nilType() nilType {
	return nilType{tgoTag: nilTypeTagNonNil}
}

// NonNilPayload requires NonNil. No tag check.
func (nilType) NonNilPayload() nilTypeNonNil { return nilTypeNonNil{} }

// nilTypeNil is the Nil payload.
type nilTypeNil struct{}

// nilType constructs nilType. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value nilTypeNil) nilType() nilType {
	return nilType{tgoTag: nilTypeTagNil}
}

// NilPayload requires Nil. No tag check.
func (nilType) NilPayload() nilTypeNil { return nilTypeNil{} }

// nilTypeOptional is the Optional payload.
type nilTypeOptional struct{}

// nilType constructs nilType. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value nilTypeOptional) nilType() nilType {
	return nilType{tgoTag: nilTypeTagOptional}
}

// OptionalPayload requires Optional. No tag check.
func (nilType) OptionalPayload() nilTypeOptional { return nilTypeOptional{} }

func (v nilType) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case nilTypeTagNever:
		payload := v.NeverPayload()
		return __tgo_json.Marshal(struct {
			Payload nilTypeNever `json:"Never"`
		}{Payload: payload})
	case nilTypeTagNonNil:
		payload := v.NonNilPayload()
		return __tgo_json.Marshal(struct {
			Payload nilTypeNonNil `json:"NonNil"`
		}{Payload: payload})
	case nilTypeTagNil:
		payload := v.NilPayload()
		return __tgo_json.Marshal(struct {
			Payload nilTypeNil `json:"Nil"`
		}{Payload: payload})
	case nilTypeTagOptional:
		payload := v.OptionalPayload()
		return __tgo_json.Marshal(struct {
			Payload nilTypeOptional `json:"Optional"`
		}{Payload: payload})
	default:
		return nil, __tgo_fmt.Errorf("invalid nilType JSON tag")
	}
}

func (v nilType) MarshalJSONTo(out *__tgo_jsontext.Encoder) error {
	switch v.tgoTag {
	case nilTypeTagNever:
		payload := v.NeverPayload()
		return __tgo_nilType_external_json_to(out, "Never", payload)
	case nilTypeTagNonNil:
		payload := v.NonNilPayload()
		return __tgo_nilType_external_json_to(out, "NonNil", payload)
	case nilTypeTagNil:
		payload := v.NilPayload()
		return __tgo_nilType_external_json_to(out, "Nil", payload)
	case nilTypeTagOptional:
		payload := v.OptionalPayload()
		return __tgo_nilType_external_json_to(out, "Optional", payload)
	default:
		return __tgo_fmt.Errorf("invalid nilType JSON tag")
	}
}

func (v *nilType) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]__tgo_json.RawMessage
	if err := __tgo_json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return __tgo_fmt.Errorf("expected one nilType JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Never":
		var payload nilTypeNever
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.nilType()
		return nil
	case "NonNil":
		var payload nilTypeNonNil
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.nilType()
		return nil
	case "Nil":
		var payload nilTypeNil
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.nilType()
		return nil
	case "Optional":
		var payload nilTypeOptional
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.nilType()
		return nil
	default:
		return __tgo_fmt.Errorf("unknown nilType JSON variant %q", variant)
	}
}

func (v *nilType) UnmarshalJSONFrom(in *__tgo_jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return __tgo_fmt.Errorf("expected one nilType JSON variant")
	}
	var payloadData __tgo_jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Never":
			current = 1
		case "NonNil":
			current = 2
		case "Nil":
			current = 3
		case "Optional":
			current = 4
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return __tgo_fmt.Errorf("expected one nilType JSON variant")
	}
	if selected == 0 {
		return __tgo_fmt.Errorf("unknown nilType JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload nilTypeNever
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.nilType()
		return nil
	case 2:
		var payload nilTypeNonNil
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.nilType()
		return nil
	case 3:
		var payload nilTypeNil
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.nilType()
		return nil
	case 4:
		var payload nilTypeOptional
		if err := __tgo_jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.nilType()
		return nil
	default:
		return __tgo_fmt.Errorf("invalid nilType JSON tag")
	}
}

func neverNilType() nilType    { return nilTypeNever{}.nilType() }
func nonNilType() nilType      { return nilTypeNonNil{}.nilType() }
func nilOnlyType() nilType     { return nilTypeNil{}.nilType() }
func optionalNilType() nilType { return nilTypeOptional{}.nilType() }

func nilTypeMembers(value nilType) uint8 {
	switch value.Tag() {
	case nilTypeTagNever:
		return 0
	case nilTypeTagNonNil:
		return 1
	case nilTypeTagNil:
		return 2
	case nilTypeTagOptional:
		return 3
	default:
		panic(value.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func nilTypeFromMembers(members uint8) nilType {
	switch members & 3 {
	case 0:
		return neverNilType()
	case 1:
		return nonNilType()
	case 2:
		return nilOnlyType()
	default:
		return optionalNilType()
	}
}

func unionNilTypes(left nilType, right nilType) nilType {
	return nilTypeFromMembers(nilTypeMembers(left) | nilTypeMembers(right))
}

func intersectNilTypes(left nilType, right nilType) nilType {
	return nilTypeFromMembers(nilTypeMembers(left) & nilTypeMembers(right))
}

func equalNilType(left nilType, right nilType) bool {
	return nilTypeMembers(left) == nilTypeMembers(right)
}

func isNeverNilType(value nilType) bool    { return nilTypeMembers(value) == 0 }
func isNonNilType(value nilType) bool      { return nilTypeMembers(value) == 1 }
func isNilOnlyType(value nilType) bool     { return nilTypeMembers(value) == 2 }
func isOptionalNilType(value nilType) bool { return nilTypeMembers(value) == 3 }

// declaredNilType maps a Go type to T or T | nil.
func declaredNilType(typ types.Type) nilType {
	if typeCanBeNil(typ) {
		return optionalNilType()
	}
	return nonNilType()
}

func typeCanBeNil(typ types.Type) bool {
	if typ == nil {
		return true
	}
	if _, parameter := types.Unalias(typ).(*types.TypeParam); parameter {
		return true
	}
	switch coreType(typ).(type) {
	case *types.Pointer, *types.Slice, *types.Map, *types.Chan,
		*types.Signature, *types.Interface:
		return true
	case *types.Basic:
		basic, _ := coreType(typ).(*types.Basic)
		return basic != nil && basic.Kind() == types.UnsafePointer
	}
	return false
}
