// Code generated by tgo. DO NOT EDIT.

package tgolint

import "encoding/json"
import jsonv2 "encoding/json/v2"
import "encoding/json/jsontext"
import "fmt"

import (
	"bytes"
	"go/token"
	"go/types"
	"path/filepath"
	"strconv"

	"tgo/pkg/syntax"

	"golang.org/x/tools/go/analysis"
)

type verifiedSource struct {
	generated *syntax.File
	file      *syntax.File
	tokenFile *token.File
	data      []byte
}

// verifySourceModels checks generated declarations against their canonical source.
func (c *checker) verifySourceModels(generated *syntax.File) *verifiedSource {
	generatedPath := c.pass.Fset.Position(generated.Package).Filename
	generatedData, readErr := c.pass.ReadFile(generatedPath)
	sourceName := c.generatedSource[generated]
	operand := readErr != nil
	if !operand {
		operand = sourceName == ""
	}
	if operand {
		c.failVerification(generated.Package, "generated tgo source mapping is invalid")
		return nil
	}
	sourcePath := filepath.Join(filepath.Dir(generatedPath), sourceName)
	data, err := readTGoSource(c.pass, sourcePath)
	if err != nil {
		c.failVerification(
			generated.Package,
			"cannot read tgo source %s: %v",
			sourceName,
			err,
		)
		return nil
	}
	if !bytes.Equal(generatedData, c.outputs[sourceName]) {
		c.failVerification(generated.Package, "generated tgo output integrity check failed")
		return nil
	}
	sourceFiles := token.NewFileSet()
	file, err := syntax.ParseFile(
		sourceFiles,
		sourcePath,
		data,
		syntax.ParseComments|syntax.AllErrors,
	)
	if err != nil {
		c.failVerification(
			generated.Package,
			"cannot parse tgo source %s: %v",
			sourceName,
			err,
		)
		return nil
	}
	sourceNames := make(map[string]bool)
	sourceToken := sourceFiles.File(file.Package)
	for _, declaration := range file.Declarations {
		{
			source := sourceDeclaration(
				declaration,
				c.packagePath(),
				file,
				sourceToken,
				data,
			)
			if source != nil {
				sourceNames[sourceModelName(source)] = true
			}
		}
		c.checkSourceDeclaration(
			generated,
			sourceName,
			file,
			declaration,
			sourceToken,
			data,
		)
	}
	c.reportExtraGeneratedModels(generated, sourceName, sourceNames)
	if c.invalid {
		return nil
	}
	return &verifiedSource{
		generated: generated,
		file:      file,
		tokenFile: sourceToken,
		data:      data,
	}
}

// exportSourceModels publishes facts only after every generated file verifies.
func (c *checker) exportSourceModels(source *verifiedSource) {
	for _, declaration := range source.file.Declarations {
		c.exportSourceDeclaration(
			source.generated,
			source.file,
			declaration,
			source.tokenFile,
			source.data,
		)
	}
}

func (c *checker) hasModelAPIs(object *types.TypeName) bool {
	{
		_, ok := object.Type().Underlying().(*types.Interface)
		if ok {
			return false
		}
	}
	var operand bool = method(object.Type(), "Tag") != nil
	if !operand {
		operand = method(object.Type(), "check") != nil
	}
	return operand

}

// reportExtraGeneratedModels rejects model APIs with no matching TGo declaration.
func (c *checker) reportExtraGeneratedModels(
	file *syntax.File,
	sourceName string,
	sourceNames map[string]bool,
) {
	for _, declarationValue := range file.Declarations {
		general := syntax.GeneralDeclarationOf(declarationValue)
		if general == nil {
			continue
		}
		for _, item := range general.Specs {
			specification := syntax.TypeSpecificationOf(item)
			var operand bool = specification == nil
			if !operand {
				operand = sourceNames[specification.Name.Name]
			}
			if operand {
				continue
			}
			object, objectOK := c.facts.DefinitionName(specification.Name).(*types.TypeName)
			operand_1 := !objectOK
			if !operand_1 {
				operand_1 = object.IsAlias()
			}
			if operand_1 {
				continue
			}
			if c.hasModelAPIs(object) {
				c.failVerification(
					specification.Start,
					"generated tgo output for %s does not match %s",
					specification.Name.Name,
					sourceName,
				)
			}
		}
	}
}

// checkSourceDeclaration compares one TGo model with its generated Go API.
func (c *checker) checkSourceDeclaration(
	generated *syntax.File,
	sourceName string,
	file *syntax.File,
	declaration *syntax.Declaration,
	sourceFile *token.File,
	data []byte,
) {
	source := sourceDeclaration(
		declaration,
		c.packagePath(),
		file,
		sourceFile,
		data,
	)
	if source == nil {
		return
	}
	name := sourceModelName(source)
	specification := generatedTypeSpec(generated, name)
	if specification == nil {
		c.failVerification(
			generated.Package,
			"generated tgo output for %s does not match %s",
			name,
			sourceName,
		)
		return
	}
	object, objectOK := c.facts.DefinitionName(specification.Name).(*types.TypeName)
	operand := !objectOK
	if !operand {
		operand = !sourceShapeMatches(
			generated,
			specification.Type,
			object.Type(),
			source,
		)
	}
	if operand {
		c.failVerification(
			specification.Start,
			"generated tgo output for %s does not match %s",
			name,
			sourceName,
		)
		return
	}
}

// exportSourceDeclaration records one verified model and its constructors.
func (c *checker) exportSourceDeclaration(
	generated *syntax.File,
	file *syntax.File,
	declaration *syntax.Declaration,
	sourceFile *token.File,
	data []byte,
) {
	source := sourceDeclaration(
		declaration,
		c.packagePath(),
		file,
		sourceFile,
		data,
	)
	if source == nil {
		return
	}
	name := sourceModelName(source)
	specification := generatedTypeSpec(generated, name)
	if specification == nil {
		return
	}
	object, ok := c.facts.DefinitionName(specification.Name).(*types.TypeName)
	if !ok {
		return
	}
	fact := sourceModelFact(source)
	if fact != nil {
		key := objectKey{pkg: object.Pkg(), name: object.Name()}
		c.models[key] = fact
		c.pass.ExportObjectFact(object, encodeModelFact(fact))
		c.exportValidationFacts(object, fact)
	}
}

func (c *checker) packagePath() string {
	if c.pass.Pkg == nil {
		return ""
	}
	return c.pass.Pkg.Path()
}

func tgosourceModelExternalJSONTo[T interface{}](out *jsontext.Encoder, name string, payload T) error {
	{
		err := out.WriteToken(jsontext.BeginObject)
		if err != nil {
			return err
		}
	}
	{
		err := out.WriteToken(jsontext.String(name))
		if err != nil {
			return err
		}
	}
	{
		err := jsonv2.MarshalEncode(out, payload)
		if err != nil {
			return err
		}
	}
	return out.WriteToken(jsontext.EndObject)
}

// sourceModel requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type sourceModelTag uint8

const (
	sourceModelTagEnum sourceModelTag = iota + 1
	sourceModelTagStruct
)

type sourceModel struct {
	tgoTag     sourceModelTag
	tgoStruct  sourceModelStruct
	tgoPayload interface{}
}

// Tag returns the active tag.
func (v sourceModel) Tag() sourceModelTag { return v.tgoTag }

// sourceModelEnum is the Enum payload.
type sourceModelEnum struct {
	Name     string
	Fact     *model
	Variants []sourceVariant
}
type TgosourceModelEnumInput struct {
	FieldName     string
	FieldFact     *model
	FieldVariants []sourceVariant
}

// NewsourceModelEnum constructs sourceModel. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewsourceModelEnum(Name string, Fact *model, Variants []sourceVariant) sourceModel {
	tgoValue := sourceModelEnum{Name, Fact, Variants}
	return sourceModel{tgoTag: sourceModelTagEnum, tgoPayload: tgoValue}
}

// EnumPayload requires Enum. No tag check.
func (v sourceModel) EnumPayload() sourceModelEnum { return v.tgoPayload.(sourceModelEnum) }

// sourceModelStruct is the Struct payload.
type sourceModelStruct struct {
	Name   string
	Fact   *model
	Fields []sourceField
}
type TgosourceModelStructInput struct {
	FieldName   string
	FieldFact   *model
	FieldFields []sourceField
}

// NewsourceModelStruct constructs sourceModel. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewsourceModelStruct(Name string, Fact *model, Fields []sourceField) sourceModel {
	tgoValue := sourceModelStruct{Name, Fact, Fields}
	return sourceModel{tgoTag: sourceModelTagStruct, tgoStruct: tgoValue}
}

// StructPayload requires Struct. No tag check.
func (v sourceModel) StructPayload() sourceModelStruct { return v.tgoStruct }

func (v sourceModel) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case sourceModelTagEnum:
		payload := v.EnumPayload()
		return json.Marshal(struct {
			Payload sourceModelEnum `json:"Enum"`
		}{Payload: payload})
	case sourceModelTagStruct:
		payload := v.StructPayload()
		return json.Marshal(struct {
			Payload sourceModelStruct `json:"Struct"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid sourceModel JSON tag")
	}
}

func (v sourceModel) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case sourceModelTagEnum:
		payload := v.EnumPayload()
		return tgosourceModelExternalJSONTo(out, "Enum", payload)
	case sourceModelTagStruct:
		payload := v.StructPayload()
		return tgosourceModelExternalJSONTo(out, "Struct", payload)
	default:
		return fmt.Errorf("invalid sourceModel JSON tag")
	}
}

func (v *sourceModel) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	{
		err := json.Unmarshal(data, &object)
		if err != nil {
			return err
		}
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one sourceModel JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Enum":
		var payload sourceModelEnum
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		if payload.Fact == nil {
			return fmt.Errorf("invalid sourceModel.Enum JSON payload: Fact must not be nil")
		}

		*v = NewsourceModelEnum(payload.Name, payload.Fact, payload.Variants)
		return nil
	case "Struct":
		var payload sourceModelStruct
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewsourceModelStruct(payload.Name, payload.Fact, payload.Fields)
		return nil
	default:
		return fmt.Errorf("unknown sourceModel JSON variant %q", variant)
	}
}

func (v *sourceModel) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one sourceModel JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Enum":
			current = 1
		case "Struct":
			current = 2
		}
		operand := haveName
		if operand {
			operand = current == selected
		}
		same := operand
		operand_1 := same
		if operand_1 {
			operand_1 = current == 0
		}
		if operand_1 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		operand_2 := !multiple
		if operand_2 {
			operand_2 = current > 0
		}
		var operand_3 bool = operand_2
		if operand_3 {
			operand_3 = current == selected
		}
		if operand_3 {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else {
			err := in.SkipValue()
			if err != nil {
				return err
			}
		}
	}
	{
		_, err := in.ReadToken()
		if err != nil {
			return err
		}
	}
	operand_4 := !haveName
	if !operand_4 {
		operand_4 = multiple
	}
	if operand_4 {
		return fmt.Errorf("expected one sourceModel JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown sourceModel JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload sourceModelEnum
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		if payload.Fact == nil {
			return fmt.Errorf("invalid sourceModel.Enum JSON payload: Fact must not be nil")
		}

		*v = NewsourceModelEnum(payload.Name, payload.Fact, payload.Variants)
		return nil
	case 2:
		var payload sourceModelStruct
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewsourceModelStruct(payload.Name, payload.Fact, payload.Fields)
		return nil
	default:
		return fmt.Errorf("invalid sourceModel JSON tag")
	}
}

// sourceDeclaration converts one syntax declaration to verified model metadata.
func sourceDeclaration(
	declaration *syntax.Declaration,
	packagePath string,
	file *syntax.File,
	sourceFile *token.File,
	data []byte,
) *sourceModel {
	if file == nil {
		return nil
	}
	if sourceFile == nil {
		return nil
	}
	{
		node, ok := syntax.EnumDeclarationOf(declaration)
		if ok {
			if node == nil {
				return nil
			}
			variants := make([]string, 0, len(node.Variants))
			sourceVariants := make([]sourceVariant, 0, len(node.Variants))
			for _, variant := range node.Variants {
				if variant == nil {
					continue
				}
				variants = append(variants, variant.Name.Name)
				fields := []sourceField(nil)
				for _, field := range variant.Fields {
					if field != nil {
						fields = append(fields, sourceFields(file, sourceFile, data, field)...)
					}
				}
				sourceVariants = append(
					sourceVariants,
					sourceVariant{
						name:   variant.Name.Name,
						fields: fields,
					},
				)
			}
			result := func(input TgosourceModelEnumInput) sourceModel {
				return NewsourceModelEnum(input.FieldName, input.FieldFact, input.FieldVariants)
			}(TgosourceModelEnumInput{FieldName: node.Name.Name, FieldFact: enumModel(packagePath, node.Name.Name, variants), FieldVariants: sourceVariants})

			return &result
		}
	}
	{
		node, ok := syntax.StructDeclarationOf(declaration)
		if ok {
			if node == nil {
				return nil
			}
			fields := []sourceField(nil)
			for _, field := range node.Fields {
				if field != nil {
					fields = append(fields, sourceFields(file, sourceFile, data, field)...)
				}
			}
			var fact *model = nil
			if node.Checked != token.NoPos {
				fact = checkedModel(packagePath, node.Name.Name)
			}
			result := func(input TgosourceModelStructInput) sourceModel {
				return NewsourceModelStruct(input.FieldName, input.FieldFact, input.FieldFields)
			}(TgosourceModelStructInput{FieldName: node.Name.Name, FieldFact: fact, FieldFields: fields})

			return &result
		}
	}
	return nil
}

func sourceModelName(value *sourceModel) string {
	if value == nil {
		return ""
	}
	switch item := *value; item.Tag() {
	case sourceModelTagEnum:
		return item.EnumPayload().Name
	case sourceModelTagStruct:
		return item.StructPayload().Name
	default:
		panic("invalid sourceModel tag") // unreachable: tgolint requires a case per tag
	}
}

func sourceModelFact(value *sourceModel) *model {
	if value == nil {
		return nil
	}
	switch item := *value; item.Tag() {
	case sourceModelTagEnum:
		return item.EnumPayload().Fact
	case sourceModelTagStruct:
		return item.StructPayload().Fact
	default:
		panic("invalid sourceModel tag") // unreachable: tgolint requires a case per tag
	}
}

func readTGoSource(pass *analysis.Pass, path string) ([]byte, error) {
	found := false
	for _, other := range pass.OtherFiles {
		if filepath.Clean(other) == filepath.Clean(path) {
			found = true
			break
		}
	}
	if !found {
		pass.OtherFiles = append(pass.OtherFiles, path)
	}
	result, err := pass.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("pass.ReadFile: %w", err)
	}

	data := result
	return data, nil
}

func generatedTypeSpec(file *syntax.File, name string) *syntax.TypeSpecification {
	for _, declarationValue := range file.Declarations {
		general := syntax.GeneralDeclarationOf(declarationValue)
		if general == nil {
			continue
		}
		for _, item := range general.Specs {
			specification := syntax.TypeSpecificationOf(item)
			operand := specification != nil
			if operand {
				operand = specification.Name.Name == name
			}
			if operand {
				return specification
			}
		}
	}
	return nil
}

// sourceShapeMatches checks source fields and the public generated model API.
func sourceShapeMatches(
	generated *syntax.File,
	representation *syntax.Expression,
	typ types.Type,
	source *sourceModel,
) bool {
	if source == nil {
		return false
	}
	switch item := *source; item.Tag() {
	case sourceModelTagStruct:
		sourceStruct := item.StructPayload()
		structure := syntax.StructTypeExpressionOf(representation)
		if structure == nil {
			return false
		}
		if !sameFields(sourceStruct.Fields, structure.Fields.List, generated) {
			return false
		}
		var operand bool = sourceStruct.Fact == nil
		if !operand {
			operand_1 := validCheckedStructAPI(typ)
			if operand_1 {
				operand_1 = validCheckedCarrier(typ, sourceStruct.Fields)
			}
			operand = operand_1
		}
		return operand

	case sourceModelTagEnum:
		enum := item.EnumPayload()
		if !generatedEnumShape(typ, enum.Name, enum.Variants) {
			return false
		}
		for _, variant := range enum.Variants {
			payloadSpec := generatedTypeSpec(generated, enum.Name+variant.name)
			if payloadSpec == nil {
				return false
			}
			payload := syntax.StructTypeExpressionOf(payloadSpec.Type)
			var operand_2 bool = payload == nil
			if !operand_2 {
				operand_2 = !sameFields(variant.fields, payload.Fields.List, generated)
			}
			if operand_2 {
				return false
			}
		}
		return true
	default:
		panic("invalid sourceModel tag") // unreachable: tgolint requires a case per tag
	}
}

func validCheckedStructAPI(typ types.Type) bool {
	signature := method(typ, "check")
	var operand bool = signature == nil
	if !operand {
		operand = signature.Recv() == nil
	}
	var operand_1 bool = operand
	if !operand_1 {
		operand_1 = signature.Params().Len() != 0
	}
	var operand_2 bool = operand_1
	if !operand_2 {
		operand_2 = signature.Results().Len() != 2
	}
	var operand_3 bool = operand_2
	if !operand_3 {
		operand_3 = signature.Variadic()
	}
	if operand_3 {
		return false
	}
	errorObject := types.Universe.Lookup("error")
	var operand_4 bool = errorObject == nil
	if !operand_4 {
		operand_4 = !types.Identical(signature.Recv().Type(), typ)
	}
	var operand_5 bool = operand_4
	if !operand_5 {
		operand_5 = !types.Identical(signature.Results().At(0).Type(), typ)
	}
	var operand_6 bool = operand_5
	if !operand_6 {
		operand_6 = !types.Identical(signature.Results().At(1).Type(), errorObject.Type())
	}
	if operand_6 {
		return false
	}
	named, ok := types.Unalias(typ).(*types.Named)
	operand_7 := !ok
	if !operand_7 {
		operand_7 = named.Obj().Pkg() == nil
	}
	if operand_7 {
		return false
	}
	constructor, ok := named.Obj().Pkg().Scope().Lookup(
		"New" + named.Obj().Name(),
	).(*types.Func)
	if !ok {
		return false
	}
	created, ok := constructor.Type().(*types.Signature)
	structure, structureOK := named.Underlying().(*types.Struct)
	operand_8 := !ok
	if !operand_8 {
		operand_8 = !structureOK
	}
	var operand_9 bool = operand_8
	if !operand_9 {
		operand_9 = created.Recv() != nil
	}
	var operand_10 bool = operand_9
	if !operand_10 {
		operand_10 = created.Variadic()
	}
	var operand_11 bool = operand_10
	if !operand_11 {
		operand_11 = created.Params().Len() != structure.NumFields()
	}
	var operand_12 bool = operand_11
	if !operand_12 {
		operand_12 = created.Results().Len() != 2
	}
	if operand_12 {
		return false
	}
	for index := 0; index < structure.NumFields(); index++ {
		if !types.Identical(created.Params().At(index).Type(), structure.Field(index).Type()) {
			return false
		}
	}
	operand_13 := types.Identical(created.Results().At(0).Type(), typ)
	if operand_13 {
		operand_13 = types.Identical(created.Results().At(1).Type(), errorObject.Type())
	}
	return operand_13

}

// generatedEnumShape checks enum operations without reading private storage.
func generatedEnumShape(
	typ types.Type,
	name string,
	variants []sourceVariant,
) bool {
	tag, ok := typeInPackage(typ, name+"Tag")
	operand := !ok
	if !operand {
		operand = !validGeneratedTagAPI(typ, tag, name, variants)
	}
	if operand {
		return false
	}
	for _, variant := range variants {
		payloadName := name + variant.name
		payload, ok := typeInPackage(typ, payloadName)
		operand_1 := !ok
		if !operand_1 {
			operand_1 = !validEnumAPI(
				typ, payload, variant.name+"Payload", "New"+payloadName,
			)
		}
		if operand_1 {
			return false
		}
		if len(variant.fields) > 0 {
			carrier, ok := typeInPackage(typ, "Tgo"+payloadName+"Input")
			operand_2 := !ok
			if !operand_2 {
				operand_2 = !validEnumCarrier(payload, carrier)
			}
			if operand_2 {
				return false
			}
		}
	}
	return true
}

func validGeneratedTagAPI(
	typ types.Type,
	tagType types.Type,
	name string,
	variants []sourceVariant,
) bool {
	tag := method(typ, "Tag")
	var operand bool = tag == nil
	if !operand {
		operand = tag.Params().Len() != 0
	}
	var operand_1 bool = operand
	if !operand_1 {
		operand_1 = tag.Results().Len() != 1
	}
	var operand_2 bool = operand_1
	if !operand_2 {
		operand_2 = !types.Identical(tag.Results().At(0).Type(), tagType)
	}
	if operand_2 {
		return false
	}
	basic, ok := coreType(tagType).(*types.Basic)
	operand_3 := !ok
	if !operand_3 {
		operand_3 = basic.Info()&types.IsUnsigned == 0
	}
	if operand_3 {
		return false
	}
	named, ok := types.Unalias(typ).(*types.Named)
	operand_4 := !ok
	if !operand_4 {
		operand_4 = named.Obj().Pkg() == nil
	}
	if operand_4 {
		return false
	}
	names := []string(nil)
	for _, variant := range variants {
		names = append(names, name+"Tag"+variant.name)
	}
	for index, constantName := range names {
		constant, ok := named.Obj().Pkg().Scope().Lookup(constantName).(*types.Const)
		operand_5 := !ok
		if !operand_5 {
			operand_5 = !types.Identical(constant.Type(), tagType)
		}
		var operand_6 bool = operand_5
		if !operand_6 {
			operand_6 = constant.Val().ExactString() != strconv.Itoa(index+1)
		}
		if operand_6 {
			return false
		}
	}
	return true
}

func typeInPackage(typ types.Type, name string) (types.Type, bool) {
	named, ok := types.Unalias(typ).(*types.Named)
	operand := !ok
	if !operand {
		operand = named.Obj().Pkg() == nil
	}
	if operand {
		return nil, false
	}
	object, ok := named.Obj().Pkg().Scope().Lookup(name).(*types.TypeName)
	if !ok {
		return nil, false
	}
	return object.Type(), true
}

// sameModelFact compares model identity and the ordered enum variants.
func sameModelFact(left *model, right *model) bool {
	var operand bool = left == nil
	if !operand {
		operand = right == nil
	}
	var operand_1 bool = operand
	if !operand_1 {
		operand_1 = !sameModel(left, right)
	}
	if operand_1 {
		return false
	}
	leftVariants := modelVariants(left)
	rightVariants := modelVariants(right)
	if len(leftVariants) != len(rightVariants) {
		return false
	}
	for index := range leftVariants {
		if leftVariants[index] != rightVariants[index] {
			return false
		}
	}
	return true
}

type sourceField struct {
	name           string
	typeExpression string
	tag            string
}

type sourceVariant struct {
	name   string
	fields []sourceField
}

func sourceFields(
	file *syntax.File,
	sourceFile *token.File,
	data []byte,
	declaration *syntax.TGoField,
) []sourceField {
	result := []sourceField(nil)
	typeText := sourceExpression(file, sourceFile, data, declaration.Field.Type)
	tagText := ""
	if declaration.Field.Tag != nil {
		tagText = sourceRange(
			sourceFile,
			data,
			declaration.Field.Tag.Start,
			declaration.Field.Tag.Stop,
		)
	}
	if len(declaration.Field.Names) == 0 {
		return []sourceField{{name: "", typeExpression: typeText, tag: tagText}}
	}
	for _, name := range declaration.Field.Names {
		result = append(
			result,
			sourceField{
				name:           name.Name,
				typeExpression: typeText,
				tag:            tagText,
			},
		)
	}
	return result
}

func sourceExpression(
	file *syntax.File,
	sourceFile *token.File,
	data []byte,
	expression *syntax.Expression,
) string {
	if expression == nil {
		return ""
	}
	start := syntax.ExpressionPosition(expression)
	end := syntax.ExpressionEnd(expression)
	result := []byte(
		sourceRange(
			sourceFile,
			data,
			syntax.ExpressionPosition(expression),
			syntax.ExpressionEnd(expression),
		),
	)
	for _, extension := range syntax.Extensions(file) {
		node, ok := syntax.NonNilPointerTypeOf(extension)
		operand := !ok
		if !operand {
			operand = node.Percent < start
		}
		var operand_1 bool = operand
		if !operand_1 {
			operand_1 = node.Percent >= end
		}
		if operand_1 {
			continue
		}
		result[sourceFile.Offset(node.Percent)-sourceFile.Offset(start)] = '*'
	}
	return string(result)
}

func sourceRange(
	sourceFile *token.File,
	data []byte,
	start token.Pos,
	end token.Pos,
) string {
	return string(data[sourceFile.Offset(start):sourceFile.Offset(end)])
}
