// Code generated by tgo. DO NOT EDIT.

package tgolint

import (
	"go/token"
	"go/types"

	"tgo/pkg/syntax"
)

// checkRepresentationAccess blocks private fields and unchecked payload methods.
func (c *checker) checkRepresentationAccess(expression *syntax.Expression) {
	if c.syntaxSafe[expression] || c.syntaxHandled[expression] {
		return
	}
	selector := syntax.SelectorExpressionOf(expression)
	if selector == nil {
		return
	}
	model := c.modelForSourceSelector(expression, selector)
	if model == nil {
		return
	}
	if tag := variantTag(model, selector.Selector.Name); tag != 0 {
		c.checkPayloadAccessor(expression, selector, model, tag)
		return
	}
	if modelIsChecked(model) && c.checkedFieldChange(expression) &&
		!c.checkedReceiverMutation(expression, model) {
		c.pass.Reportf(
			selector.Start,
			"checked field %s cannot be changed after construction",
			selector.Selector.Name,
		)
		return
	}
	if privateRepresentation(model, selector.Selector.Name) {
		c.pass.Reportf(
			selector.Start,
			"%s.%s is private tgo representation",
			modelName(model),
			selector.Selector.Name,
		)
		return
	}
}

// checkedReceiverMutation permits normalization in the model check method.
func (c *checker) checkedReceiverMutation(
	expression *syntax.Expression,
	model *model,
) bool {
	selector := syntax.SelectorExpressionOf(expression)
	if selector == nil {
		return false
	}
	receiver := sourceUnparenthesized(selector.Expression)
	receiverName := syntax.IdentifierExpressionOf(receiver)
	if receiverName == nil {
		return false
	}
	receiverObject := c.facts.Object(receiverName)
	target := syntax.ExpressionNode(expression)
	current := syntax.Parent(c.file, &target)
	for current != nil {
		declaration, ok := syntax.FunctionDeclarationOf(current)
		if ok {
			return declaration != nil && declaration.Name.Name == "check" &&
				c.matchesCheckedReceiver(
					declaration, model, receiverName, receiverObject,
				)
		}
		current = syntax.Parent(c.file, current)
	}
	return false
}

func (c *checker) matchesCheckedReceiver(
	declaration *syntax.FunctionDeclaration,
	model *model,
	name *syntax.Identifier,
	object types.Object,
) bool {
	declared := c.checkedReceiverObject(declaration, model)
	if sameSourceObject(declared, object) {
		return true
	}
	if variable, ok := object.(*types.Var); ok && !variable.IsField() {
		return false
	}
	if declared == nil || declaration.Receiver == nil ||
		len(declaration.Receiver.List) != 1 {
		return false
	}
	field := declaration.Receiver.List[0]
	return len(field.Names) == 1 && field.Names[0].Name == name.Name
}

func sameSourceObject(left types.Object, right types.Object) bool {
	return left != nil && right != nil &&
		(left == right || left.Name() == right.Name() && left.Pos() == right.Pos())
}

func (c *checker) checkedReceiverObject(
	declaration *syntax.FunctionDeclaration,
	model *model,
) types.Object {
	if declaration.Receiver == nil || len(declaration.Receiver.List) != 1 {
		return nil
	}
	field := declaration.Receiver.List[0]
	if len(field.Names) != 1 {
		return nil
	}
	object := c.facts.Object(field.Names[0])
	if object == nil || !sameModelForType(object.Type(), model) {
		return nil
	}
	return object
}

func sameModelForType(
	typ types.Type,
	model *model,
) bool {
	if model == nil || typ == nil {
		return false
	}
	named, ok := dereference(typ).(*types.Named)
	return ok && named.Obj().Pkg() != nil &&
		named.Obj().Pkg().Path() == modelPackage(model) &&
		named.Obj().Name() == modelName(model)
}

func (c *checker) checkedFieldChange(expression *syntax.Expression) bool {
	selection := c.facts.Selection(expression)
	if !selectionUsesOwnedStorage(selection) {
		return false
	}
	current := expression
	ownedSlice := false
	target := syntax.ExpressionNode(current)
	parent := c.parents[target]
	for parent != nil {
		if wrapped, ok := syntax.ExpressionOf(parent); ok {
			if wrapped == nil {
				return false
			}
			parentheses := syntax.ParenthesizedExpressionOf(wrapped)
			if parentheses != nil &&
				sameExpressionRange(parentheses.Expression, current) {
				current = wrapped
				parent = c.parents[*parent]
				continue
			}
			selector := syntax.SelectorExpressionOf(wrapped)
			if selector != nil && sameExpressionRange(selector.Expression, current) {
				if modelIsChecked(c.modelForReceiver(c.facts.Type(current))) ||
					!structOwnsSelectedStorage(c.facts.Type(current)) ||
					!selectionUsesOwnedStorage(c.facts.Selection(wrapped)) {
					return false
				}
				current = wrapped
				parent = c.parents[*parent]
				continue
			}
			index := syntax.IndexExpressionOf(wrapped)
			if index != nil && sameExpressionRange(index.Expression, current) {
				if !ownedSlice && !arrayOwnsIndexedStorage(c.facts.Type(current)) {
					return false
				}
				current = wrapped
				ownedSlice = false
				parent = c.parents[*parent]
				continue
			}
			slice := syntax.SliceExpressionOf(wrapped)
			if slice != nil && sameExpressionRange(slice.Expression, current) {
				if !ownedSlice && !arrayOwnsIndexedStorage(c.facts.Type(current)) {
					return false
				}
				current = wrapped
				ownedSlice = true
				parent = c.parents[*parent]
				continue
			}
			unary := syntax.UnaryExpressionOf(wrapped)
			return unary != nil && unary.Operator == token.AND &&
				sameExpressionRange(unary.Expression, current)
		}
		statement, ok := syntax.StatementOf(parent)
		if !ok {
			return false
		}
		if increment := syntax.IncrementStatementOf(statement); increment != nil {
			return sameExpressionRange(increment.Expression, current)
		}
		if assignment := syntax.AssignmentStatementOf(statement); assignment != nil {
			for _, left := range assignment.Left {
				if sameExpressionRange(left, current) {
					return true
				}
			}
		}
		if ranged := syntax.RangeStatementOf(statement); ranged != nil &&
			ranged.Operator == token.ASSIGN {
			if ranged.Key != nil && sameExpressionRange(ranged.Key, current) {
				return true
			}
			if ranged.Value != nil && sameExpressionRange(ranged.Value, current) {
				return true
			}
		}
		return false
	}
	return false
}

func selectionUsesOwnedStorage(selection *types.Selection) bool {
	if selection == nil || selection.Kind() != types.FieldVal {
		return false
	}
	current := selection.Recv()
	for offset, index := range selection.Index() {
		current = dereference(current)
		structure, ok := current.Underlying().(*types.Struct)
		if !ok || index >= structure.NumFields() {
			return false
		}
		current = structure.Field(index).Type()
		if offset < len(selection.Index())-1 &&
			!structOwnsSelectedStorage(current) {
			return false
		}
	}
	return true
}

func structOwnsSelectedStorage(typ types.Type) bool {
	if typ == nil {
		return false
	}
	_, ok := types.Unalias(typ).Underlying().(*types.Struct)
	return ok
}

func arrayOwnsIndexedStorage(typ types.Type) bool {
	if typ == nil {
		return false
	}
	_, ok := types.Unalias(typ).Underlying().(*types.Array)
	return ok
}

func sameExpressionRange(left *syntax.Expression, right *syntax.Expression) bool {
	return syntax.ExpressionPosition(left) == syntax.ExpressionPosition(right) &&
		syntax.ExpressionEnd(left) == syntax.ExpressionEnd(right)
}

func privateRepresentation(model *model, name string) bool {
	if modelIsChecked(model) {
		return false
	}
	if name == "tgoTag" {
		return true
	}
	for _, variant := range modelVariants(model) {
		if name == "tgo"+variant {
			return true
		}
	}
	return false
}
