// Code generated by tgo. DO NOT EDIT.

package tgolint

import (
	"go/token"
	"go/types"

	"tgo/pkg/syntax"
)

// checkRepresentationAccess blocks private fields and unchecked payload methods.
func (c *checker) checkRepresentationAccess(expression *syntax.Expression) {
	operand := c.syntaxSafe[expression]
	if !operand {
		operand = c.syntaxHandled[expression]
	}
	if operand {
		return
	}
	selector := syntax.SelectorExpressionOf(expression)
	if selector == nil {
		return
	}
	model := c.modelForSourceSelector(expression, selector)
	if model == nil {
		return
	}
	{
		tag := variantTag(model, selector.Selector.Name)
		if tag != 0 {
			c.checkPayloadAccessor(expression, selector, model, tag)
			return
		}
	}
	operand_1 := modelIsChecked(model)
	if operand_1 {
		operand_1 = c.checkedFieldChange(expression)
	}
	var operand_2 bool = operand_1
	if operand_2 {
		operand_2 = !c.checkedReceiverMutation(expression, model)
	}
	if operand_2 {
		name := selector.Selector.Name
		{
			field := c.promotedPointerMethodField(expression)
			if field != nil {
				name = field.Name()
			}
		}
		c.pass.Reportf(
			selector.Start,
			"checked field %s cannot be changed after construction",
			name,
		)
		return
	}
	if privateRepresentation(model, selector.Selector.Name) {
		c.pass.Reportf(
			selector.Start,
			"%s.%s is private tgo representation",
			modelName(model),
			selector.Selector.Name,
		)
		return
	}
}

// checkedReceiverMutation permits normalization in the model check method.
func (c *checker) checkedReceiverMutation(
	expression *syntax.Expression,
	model *model,
) bool {
	selector := syntax.SelectorExpressionOf(expression)
	if selector == nil {
		return false
	}
	selection := c.facts.Selection(expression)
	if selection == nil {
		return false
	}
	var directField bool = selection.Kind() == types.FieldVal
	if directField {
		directField = len(selection.Index()) == 1
	}
	promotedField := c.promotedPointerMethodField(expression)
	var operand bool = selection.Kind() == types.MethodVal
	if operand {
		operand = len(selection.Index()) == 2
	}
	var operand_1 bool = operand
	if operand_1 {
		operand_1 = promotedField != nil
	}
	var directPrimitiveMethod bool = operand_1
	if directPrimitiveMethod {
		directPrimitiveMethod = checkedPrimitiveType(promotedField.Type())
	}
	operand_2 := !directField
	if operand_2 {
		operand_2 = !directPrimitiveMethod
	}
	if operand_2 {
		return false
	}
	receiver := sourceUnparenthesized(selector.Expression)
	receiverName := syntax.IdentifierExpressionOf(receiver)
	if receiverName == nil {
		return false
	}
	receiverObject := c.facts.Object(receiverName)
	target := syntax.ExpressionNode(expression)
	current := syntax.Parent(c.file, &target)
	for current != nil {
		declaration, ok := syntax.FunctionDeclarationOf(current)
		if ok {
			var operand_3 bool = declaration == nil
			if !operand_3 {
				operand_3 = declaration.Name.Name != "check"
			}
			var operand_4 bool = operand_3
			if !operand_4 {
				operand_4 = !c.matchesCheckedReceiver(
					declaration, model, receiverName, receiverObject,
				)
			}
			if operand_4 {
				return false
			}
			operand_5 := directPrimitiveMethod
			if !operand_5 {
				operand_5 = checkedPrimitiveField(selection)
			}
			if operand_5 {
				return true
			}
			return c.checkedFieldReplacement(expression)
		}
		current = syntax.Parent(c.file, current)
	}
	return false
}

func checkedPrimitiveField(selection *types.Selection) bool {
	field, ok := selection.Obj().(*types.Var)
	if !ok {
		return false
	}
	return checkedPrimitiveType(field.Type())
}

func checkedPrimitiveType(typ types.Type) bool {
	basic, ok := types.Unalias(typ).Underlying().(*types.Basic)
	if !ok {
		return false
	}
	const allowed = types.IsBoolean | types.IsInteger | types.IsFloat |
		types.IsComplex | types.IsString
	return basic.Info()&allowed != 0
}

func (c *checker) checkedFieldReplacement(expression *syntax.Expression) bool {
	current := expression
	parent := c.parents[syntax.ExpressionNode(current)]
	for parent != nil {
		{
			wrapped, ok := syntax.ExpressionOf(parent)
			if ok {
				if wrapped == nil {
					return false
				}
				parentheses := syntax.ParenthesizedExpressionOf(wrapped)
				var operand bool = parentheses == nil
				if !operand {
					operand = !sameExpressionRange(parentheses.Expression, current)
				}
				if operand {
					return false
				}
				current = wrapped
				parent = c.parents[*parent]
				continue
			}
		}
		statement, ok := syntax.StatementOf(parent)
		if !ok {
			return false
		}
		{
			assignment := syntax.AssignmentStatementOf(statement)
			if assignment != nil {
				for _, left := range assignment.Left {
					if sameExpressionRange(left, current) {
						return true
					}
				}
			}
		}
		{
			ranged := syntax.RangeStatementOf(statement)
			operand_1 := ranged != nil
			if operand_1 {
				operand_1 = ranged.Operator == token.ASSIGN
			}
			if operand_1 {
				if optionalSameExpressionRange(ranged.Key, current) {
					return true
				}
				if optionalSameExpressionRange(ranged.Value, current) {
					return true
				}
			}
		}
		return false
	}
	return false
}

func (c *checker) matchesCheckedReceiver(
	declaration *syntax.FunctionDeclaration,
	model *model,
	name *syntax.Identifier,
	object types.Object,
) bool {
	declared := c.checkedReceiverObject(declaration, model)
	if sameSourceObject(declared, object) {
		return true
	}
	{
		variable, ok := object.(*types.Var)
		operand := ok
		if operand {
			operand = !variable.IsField()
		}
		if operand {
			return false
		}
	}
	operand_1 := declared == nil
	if !operand_1 {
		operand_1 = declaration.Receiver == nil
	}
	operand_2 := operand_1
	if !operand_2 {
		operand_2 = len(declaration.Receiver.List) != 1
	}
	if operand_2 {
		return false
	}
	field := declaration.Receiver.List[0]
	var operand_3 bool = len(field.Names) == 1
	if operand_3 {
		operand_3 = field.Names[0].Name == name.Name
	}
	return operand_3
}

func sameSourceObject(left types.Object, right types.Object) bool {
	var operand bool = left != nil
	if operand {
		operand = right != nil
	}
	var operand_1 bool = operand
	if operand_1 {
		var operand_2 bool = left == right
		if !operand_2 {
			var operand_3 bool = left.Name() == right.Name()
			if operand_3 {
				operand_3 = left.Pos() == right.Pos()
			}
			operand_2 = operand_3
		}
		operand_1 = (operand_2)
	}
	return operand_1

}

func (c *checker) checkedReceiverObject(
	declaration *syntax.FunctionDeclaration,
	model *model,
) types.Object {
	operand := declaration.Receiver == nil
	if !operand {
		operand = len(declaration.Receiver.List) != 1
	}
	if operand {
		return nil
	}
	field := declaration.Receiver.List[0]
	if len(field.Names) != 1 {
		return nil
	}
	object := c.facts.Object(field.Names[0])
	var operand_1 bool = object == nil
	if !operand_1 {
		operand_1 = !sameModelForType(object.Type(), model)
	}
	if operand_1 {
		return nil
	}
	return object
}

func sameModelForType(
	typ types.Type,
	model *model,
) bool {
	operand := model == nil
	if !operand {
		operand = typ == nil
	}
	if operand {
		return false
	}
	named, ok := dereference(typ).(*types.Named)
	operand_1 := ok
	if operand_1 {
		operand_1 = named.Obj().Pkg() != nil
	}
	var operand_2 bool = operand_1
	if operand_2 {
		operand_2 = named.Obj().Pkg().Path() == modelPackage(model)
	}
	var operand_3 bool = operand_2
	if operand_3 {
		operand_3 = named.Obj().Name() == modelName(model)
	}
	return operand_3

}

func (c *checker) checkedFieldChange(expression *syntax.Expression) bool {
	selection := c.facts.Selection(expression)
	if selection == nil {
		return false
	}
	if selection.Kind() != types.FieldVal {
		return c.promotedPointerMethodField(expression) != nil
	}
	current := expression
	target := syntax.ExpressionNode(current)
	parent := c.parents[target]
	for parent != nil {
		{
			wrapped, ok := syntax.ExpressionOf(parent)
			if ok {
				if wrapped == nil {
					return false
				}
				parentheses := syntax.ParenthesizedExpressionOf(wrapped)
				var operand bool = parentheses != nil
				if operand {
					operand = sameExpressionRange(parentheses.Expression, current)
				}
				if operand {
					current = wrapped
					parent = c.parents[*parent]
					continue
				}
				selector := syntax.SelectorExpressionOf(wrapped)
				var operand_1 bool = selector != nil
				if operand_1 {
					operand_1 = sameExpressionRange(selector.Expression, current)
				}
				if operand_1 {
					return c.pointerMethodSelection(wrapped)
				}
				unary := syntax.UnaryExpressionOf(wrapped)
				var operand_2 bool = unary != nil
				if operand_2 {
					operand_2 = unary.Operator == token.AND
				}
				var operand_3 bool = operand_2
				if operand_3 {
					operand_3 = sameExpressionRange(unary.Expression, current)
				}
				return operand_3

			}
		}
		statement, ok := syntax.StatementOf(parent)
		if !ok {
			return false
		}
		{
			increment := syntax.IncrementStatementOf(statement)
			if increment != nil {
				return sameExpressionRange(increment.Expression, current)
			}
		}
		{
			assignment := syntax.AssignmentStatementOf(statement)
			if assignment != nil {
				for _, left := range assignment.Left {
					if sameExpressionRange(left, current) {
						return true
					}
				}
			}
		}
		{
			ranged := syntax.RangeStatementOf(statement)
			operand_4 := ranged != nil
			if operand_4 {
				operand_4 = ranged.Operator == token.ASSIGN
			}
			if operand_4 {
				if optionalSameExpressionRange(ranged.Key, current) {
					return true
				}
				if optionalSameExpressionRange(ranged.Value, current) {
					return true
				}
			}
		}
		return false
	}
	return false
}

func (c *checker) promotedPointerMethodField(
	expression *syntax.Expression,
) *types.Var {
	selection := c.facts.Selection(expression)
	var operand bool = selection == nil
	if !operand {
		operand = len(selection.Index()) < 2
	}
	var operand_1 bool = operand
	if !operand_1 {
		var operand_2 bool = selection.Kind() != types.MethodVal
		if operand_2 {
			operand_2 = selection.Kind() != types.MethodExpr
		}
		operand_1 = (operand_2)
	}
	var operand_3 bool = operand_1
	if !operand_3 {
		operand_3 = !c.pointerMethodSelection(expression)
	}
	if operand_3 {
		return nil
	}
	current := selection.Recv()
	for _, index := range selection.Index()[:len(selection.Index())-1] {
		current = dereference(current)
		structure, ok := current.Underlying().(*types.Struct)
		operand_4 := !ok
		if !operand_4 {
			operand_4 = index >= structure.NumFields()
		}
		if operand_4 {
			return nil
		}
		field := structure.Field(index)
		if modelIsChecked(c.modelForReceiver(current)) {
			return field
		}
		current = field.Type()
	}
	return nil
}

func optionalSameExpressionRange(
	left *syntax.Expression,
	right *syntax.Expression,
) bool {
	if left == nil {
		return false
	}
	return sameExpressionRange(left, right)
}

func sameExpressionRange(left *syntax.Expression, right *syntax.Expression) bool {
	var operand bool = syntax.ExpressionPosition(left) == syntax.ExpressionPosition(right)
	if operand {
		operand = syntax.ExpressionEnd(left) == syntax.ExpressionEnd(right)
	}
	return operand

}

func privateRepresentation(model *model, name string) bool {
	if modelIsChecked(model) {
		return false
	}
	if name == "tgoTag" {
		return true
	}
	for _, variant := range modelVariants(model) {
		if name == "tgo"+variant {
			return true
		}
	}
	return false
}
