// Code generated by tgo. DO NOT EDIT.

package tgolint

import "go/types"

// coreType returns the shared underlying type of a concrete or constrained type.
// It returns nil if no type fact or common underlying type is available.
func coreType(typ types.Type) types.Type {
	if typ == nil {
		return nil
	}
	typ = types.Unalias(typ)
	{
		parameter, ok := typ.(*types.TypeParam)
		if ok {
			terms, supported := simpleTerms(parameter.Constraint())
			operand := !supported
			if !operand {
				operand = len(terms) == 0
			}
			if operand {
				return nil
			}
			core := terms[0].Type().Underlying()
			for _, term := range terms[1:] {
				candidate := term.Type().Underlying()
				if !types.Identical(core, candidate) {
					core = commonChannel(core, candidate)
					if core == nil {
						return nil
					}
				}
			}
			return core
		}
	}
	return typ.Underlying()
}

// commonChannel combines channel directions when their element types match.
func commonChannel(left, right types.Type) types.Type {
	type operandType = bool
	leftChannel, leftOK := left.(*types.Chan)
	rightChannel, rightOK := right.(*types.Chan)
	operand := !leftOK
	if !operand {
		operand = !rightOK
	}
	var operand_1 bool = operand
	if !operand_1 {
		operand_1 = !types.Identical(leftChannel.Elem(), rightChannel.Elem())
	}
	if operand_1 {
		return nil
	}
	if leftChannel.Dir() == types.SendRecv {
		return rightChannel
	}
	var operand_2 operandType = rightChannel.Dir() == types.SendRecv
	if !operand_2 {
		operand_2 = leftChannel.Dir() == rightChannel.Dir()
	}
	if operand_2 {
		return leftChannel
	}
	return nil
}

// simpleTerms gets the normalized structural terms of a constraint.
// simpleTerms expands a constraint into a finite set of type terms.
func simpleTerms(typ types.Type) ([]*types.Term, bool) {
	typ = types.Unalias(typ)
	classified := goTypeOf(typ)
	switch classified.Tag() {
	case goTypeTagTypeParameter:
		return simpleTerms(classified.TypeParameterPayload().Value.Constraint())
	case goTypeTagNamed:
		named := classified.NamedPayload().Value
		if goTypeOf(named.Underlying()).Tag() == goTypeTagInterface {
			return simpleTerms(named.Underlying())
		}
		return []*types.Term{types.NewTerm(false, named)}, true
	case goTypeTagUnion:
		union := classified.UnionPayload().Value
		terms := make([]*types.Term, union.Len())
		for index := range terms {
			terms[index] = union.Term(index)
		}
		return terms, true
	case goTypeTagInterface:
		value := classified.InterfacePayload().Value
		var restriction []*types.Term = nil
		for index := 0; index < value.NumEmbeddeds(); index++ {
			terms, supported := simpleTerms(value.EmbeddedType(index))
			if !supported {
				return nil, false
			}
			if terms == nil {
				continue
			}
			if restriction == nil {
				restriction = terms
				continue
			}
			restriction = intersectTerms(restriction, terms)
		}
		return restriction, true
	case goTypeTagNil, goTypeTagBasic, goTypeTagArray, goTypeTagSlice,
		goTypeTagStruct, goTypeTagPointer, goTypeTagTuple, goTypeTagSignature,
		goTypeTagMap, goTypeTagChannel, goTypeTagOther:
		return []*types.Term{types.NewTerm(false, typ)}, true
	default:
		panic("invalid goType tag") // unreachable: tgolint requires a case per tag
	}
}

// intersectTerms returns the terms that are present in both unions.
// intersectTerms computes the shared terms from two constraint sets.
func intersectTerms(left, right []*types.Term) []*types.Term {
	intersection := make([]*types.Term, 0)
	for _, leftTerm := range left {
		for _, rightTerm := range right {
			term := intersectTerm(leftTerm, rightTerm)
			var operand bool = term != nil
			if operand {
				operand = !containsTerm(intersection, term)
			}
			if operand {
				intersection = append(intersection, term)
			}
		}
	}
	return intersection
}

// intersectTerm returns the overlap of two exact or approximate terms.
// intersectTerm returns the narrower compatible term.
func intersectTerm(left, right *types.Term) *types.Term {
	leftType := types.Unalias(left.Type())
	rightType := types.Unalias(right.Type())
	operand := !left.Tilde()
	if operand {
		operand = !right.Tilde()
	}
	if operand {
		if types.Identical(leftType, rightType) {
			return types.NewTerm(false, leftType)
		}
		return nil
	}
	if !types.Identical(leftType.Underlying(), rightType.Underlying()) {
		return nil
	}
	if !left.Tilde() {
		return types.NewTerm(false, leftType)
	}
	if !right.Tilde() {
		return types.NewTerm(false, rightType)
	}
	return types.NewTerm(true, leftType)
}

// containsTerm reports whether terms already contains the same term.
func containsTerm(terms []*types.Term, target *types.Term) bool {
	for _, term := range terms {
		var operand bool = term.Tilde() == target.Tilde()
		if operand {
			operand = types.Identical(term.Type(), target.Type())
		}
		if operand {
			return true
		}
	}
	return false
}
