// Code generated by tgo. DO NOT EDIT.
//tgo:v1 "local.tgo" fc57ac90fd55796766808f17a8c564c9057c9d362cd16159ec93cc39cfcbf708

package nilbad

import "example.com/tgolint/nilmodel"

func badReturn(value *nilmodel.Item) *nilmodel.Item {
	return value
}

func badZero() {
	var value *nilmodel.Item = nil
	_ = value
}

func badNamedResult() (value *nilmodel.Item) {
	value = nil
	return
}
