package compiler

import (
	"bytes"
	cryptorand "crypto/rand"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/build"
	"go/parser"
	"go/token"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"tgo/internal/outputname"

	"github.com/gofrs/flock"
)

const generatedHeader = "// Code generated by tgo. DO NOT EDIT."

// Build checks tgo packages and writes Go source beside each input file.
// If a check fails, it restores all output files changed by this build.
func Build(directory string, patterns []string) (err error) {
	root, module, err := moduleRoot(directory)
	if err != nil {
		return err
	}
	context, err := effectiveBuildContext(directory)
	if err != nil {
		return err
	}
	lock, err := acquireModuleLock(root)
	if err != nil {
		return err
	}
	defer func() {
		err = errors.Join(err, lock.Unlock())
	}()
	packages, err := discover(root, module, &context)
	if err != nil {
		return err
	}
	selected, err := selectPackages(directory, patterns, packages)
	if err != nil {
		return err
	}
	builder := packageBuilder{
		packages: packages,
		root:     root,
		module:   module,
		context:  &context,
		states:   make(map[string]buildState),
		previous: make(map[string]previousFile),
		current:  make(map[string]previousFile),
	}
	defer func() {
		if err != nil {
			err = errors.Join(err, builder.restore())
		}
	}()
	for _, path := range selected {
		if err = builder.build(path); err != nil {
			return err
		}
	}
	return nil
}

type goEnvironment struct {
	GOOS       string
	GOARCH     string
	CGOEnabled string `json:"CGO_ENABLED"`
	GOFlags    string `json:"GOFLAGS"`
	GO386      string
	GOAMD64    string
	GOARM      string
	GOARM64    string
	GOMIPS     string
	GOMIPS64   string
	GOPPC64    string
	GORISCV64  string
	GOWASM     string
}

// effectiveBuildContext gets target values and user tags used by the Go command.
func effectiveBuildContext(directory string) (build.Context, error) {
	command := exec.Command(
		"go", "env", "-json",
		"GOOS", "GOARCH", "CGO_ENABLED", "GOFLAGS",
		"GO386", "GOAMD64", "GOARM", "GOARM64", "GOMIPS", "GOMIPS64",
		"GOPPC64", "GORISCV64", "GOWASM",
	)
	command.Dir = directory
	output, err := command.CombinedOutput()
	if err != nil {
		return build.Context{}, fmt.Errorf("find Go build context: %s", output)
	}
	var environment goEnvironment
	if err := json.Unmarshal(output, &environment); err != nil {
		return build.Context{}, fmt.Errorf("read Go build context: %w", err)
	}
	context := build.Default
	context.GOOS = environment.GOOS
	context.GOARCH = environment.GOARCH
	context.CgoEnabled = environment.CGOEnabled == "1"
	toolTags, err := effectiveToolTags(build.Default.ToolTags, environment)
	if err != nil {
		return build.Context{}, err
	}
	context.ToolTags = toolTags
	tags, err := buildTagsFromGoFlags(environment.GOFlags)
	if err != nil {
		return build.Context{}, fmt.Errorf("read GOFLAGS: %w", err)
	}
	context.BuildTags = append(append([]string(nil), build.Default.BuildTags...), tags...)
	return context, nil
}

// effectiveToolTags replaces host architecture tags with target tags.
func effectiveToolTags(current []string, environment goEnvironment) ([]string, error) {
	tags := make([]string, 0, len(current))
	for _, tag := range current {
		if !architectureFeatureTag(tag) {
			tags = append(tags, tag)
		}
	}
	architecture, err := architectureFeatureTags(environment)
	if err != nil {
		return nil, err
	}
	return append(tags, architecture...), nil
}

// architectureFeatureTag reports whether a tool tag belongs to an architecture.
func architectureFeatureTag(tag string) bool {
	for _, architecture := range []string{
		"386", "amd64", "arm", "arm64", "mips", "mipsle", "mips64", "mips64le",
		"ppc64", "ppc64le", "riscv64", "wasm",
	} {
		if strings.HasPrefix(tag, architecture+".") {
			return true
		}
	}
	return false
}

// architectureFeatureTags gets cumulative feature tags for the target architecture.
func architectureFeatureTags(environment goEnvironment) ([]string, error) {
	switch environment.GOARCH {
	case "386":
		return singleFeatureTag("386", environment.GO386, "387", "sse2")
	case "amd64":
		return numberedFeatureTags("GOAMD64", "amd64.v", environment.GOAMD64, "v", 1, 4)
	case "arm":
		version, _, _ := strings.Cut(environment.GOARM, ",")
		return numberedFeatureTags("GOARM", "arm.", version, "", 5, 7)
	case "arm64":
		return arm64FeatureTags(environment.GOARM64)
	case "mips", "mipsle":
		return singleFeatureTag(environment.GOARCH, environment.GOMIPS, "hardfloat", "softfloat")
	case "mips64", "mips64le":
		return singleFeatureTag(environment.GOARCH, environment.GOMIPS64, "hardfloat", "softfloat")
	case "ppc64", "ppc64le":
		return numberedFeatureTags(
			"GOPPC64", environment.GOARCH+".power", environment.GOPPC64, "power", 8, 10,
		)
	case "riscv64":
		return riscv64FeatureTags(environment.GORISCV64)
	case "wasm":
		return wasmFeatureTags(environment.GOWASM)
	default:
		return nil, nil
	}
}

// numberedFeatureTags parses one level and returns all tags through it.
func numberedFeatureTags(
	name string,
	tagPrefix string,
	value string,
	valuePrefix string,
	first int,
	last int,
) ([]string, error) {
	level, err := featureLevel(value, valuePrefix, first, last)
	if err != nil {
		return nil, fmt.Errorf("invalid %s %q", name, value)
	}
	return cumulativeFeatureTags(tagPrefix, first, level), nil
}

// arm64FeatureTags gets cumulative tags for one ARM64 version.
func arm64FeatureTags(value string) ([]string, error) {
	version, _, _ := strings.Cut(value, ",")
	if len(version) != 4 || version[0] != 'v' || version[2] != '.' {
		return nil, fmt.Errorf("invalid GOARM64 %q", value)
	}
	major := int(version[1] - '0')
	minor := int(version[3] - '0')
	if major != 8 && major != 9 || minor < 0 || minor > 9 || major == 9 && minor > 5 {
		return nil, fmt.Errorf("invalid GOARM64 %q", value)
	}
	tags := cumulativeFeatureTags(fmt.Sprintf("arm64.v%d.", major), 0, minor)
	if major == 9 {
		tags = append(tags, cumulativeFeatureTags("arm64.v8.", 0, min(minor+5, 9))...)
	}
	return tags, nil
}

// riscv64FeatureTags gets cumulative RISC-V feature tags.
func riscv64FeatureTags(value string) ([]string, error) {
	levels := map[string]int{"rva20u64": 20, "rva22u64": 22, "rva23u64": 23}
	level, ok := levels[value]
	if !ok {
		return nil, fmt.Errorf("invalid GORISCV64 %q", value)
	}
	tags := []string{"riscv64.rva20u64"}
	if level >= 22 {
		tags = append(tags, "riscv64.rva22u64")
	}
	if level >= 23 {
		tags = append(tags, "riscv64.rva23u64")
	}
	return tags, nil
}

// wasmFeatureTags gets the configured WebAssembly feature tags.
func wasmFeatureTags(value string) ([]string, error) {
	for option := range strings.SplitSeq(value, ",") {
		switch option {
		case "satconv", "signext":
		case "":
		default:
			return nil, fmt.Errorf("invalid GOWASM feature %q", option)
		}
	}
	return []string{"wasm.satconv", "wasm.signext"}, nil
}

// featureLevel parses one numbered feature setting.
func featureLevel(value string, prefix string, first int, last int) (int, error) {
	number, found := strings.CutPrefix(value, prefix)
	if !found {
		return 0, errors.New("missing feature prefix")
	}
	level, err := strconv.Atoi(number)
	if err != nil || level < first || level > last {
		return 0, errors.New("invalid feature level")
	}
	return level, nil
}

// cumulativeFeatureTags returns all feature tags through one level.
func cumulativeFeatureTags(prefix string, first int, last int) []string {
	tags := make([]string, 0, last-first+1)
	for level := first; level <= last; level++ {
		tags = append(tags, prefix+strconv.Itoa(level))
	}
	return tags
}

// singleFeatureTag checks and returns one non-cumulative feature tag.
func singleFeatureTag(architecture string, value string, valid ...string) ([]string, error) {
	for _, candidate := range valid {
		if value == candidate {
			return []string{architecture + "." + value}, nil
		}
	}
	return nil, fmt.Errorf("invalid %s feature %q", architecture, value)
}

// buildTagsFromGoFlags gets tags from each Go -tags flag.
func buildTagsFromGoFlags(flags string) ([]string, error) {
	fields, err := splitGoFlags(flags)
	if err != nil {
		return nil, err
	}
	var tags []string
	for index := 0; index < len(fields); index++ {
		field := fields[index]
		value, found := strings.CutPrefix(field, "-tags=")
		if !found && field == "-tags" {
			if index+1 >= len(fields) {
				return nil, errors.New("-tags needs a value")
			}
			index++
			value = fields[index]
			found = true
		}
		if !found {
			continue
		}
		tags = strings.FieldsFunc(value, func(character rune) bool {
			return character == ',' || character == ' '
		})
	}
	return tags, nil
}

// splitGoFlags separates flags and removes matching outer quotes.
func splitGoFlags(value string) ([]string, error) {
	var fields []string
	for len(value) > 0 {
		value = strings.TrimLeft(value, " \t\n\r")
		if value == "" {
			break
		}
		if value[0] == '\'' || value[0] == '"' {
			quote := value[0]
			end := strings.IndexByte(value[1:], quote)
			if end < 0 {
				return nil, fmt.Errorf("unterminated %c string", quote)
			}
			fields = append(fields, value[1:end+1])
			value = value[end+2:]
			continue
		}
		end := strings.IndexAny(value, " \t\n\r")
		if end < 0 {
			fields = append(fields, value)
			break
		}
		fields = append(fields, value[:end])
		value = value[end:]
	}
	return fields, nil
}

// acquireModuleLock serializes builds and rollback for one module.
func acquireModuleLock(root string) (acquired *flock.Flock, err error) {
	canonicalRoot, err := filepath.EvalSymlinks(root)
	if err != nil {
		return nil, err
	}
	path := filepath.Join(canonicalRoot, ".tgo.lock")
	if err := ensureLockFile(path); err != nil {
		return nil, err
	}
	lock := flock.New(path)
	if err := lock.Lock(); err != nil {
		return nil, err
	}
	defer func() {
		if err != nil {
			err = errors.Join(err, lock.Unlock())
		}
	}()
	pathInfo, err := os.Lstat(path)
	if err != nil {
		return nil, err
	}
	lockedInfo, err := lock.Stat()
	if err != nil {
		return nil, err
	}
	if !pathInfo.Mode().IsRegular() || !os.SameFile(pathInfo, lockedInfo) {
		return nil, fmt.Errorf("refusing non-regular lock file %s", path)
	}
	return lock, nil
}

// ensureLockFile creates or checks the persistent module lock file.
func ensureLockFile(path string) error {
	for {
		info, err := os.Lstat(path)
		if err == nil {
			if !info.Mode().IsRegular() {
				return fmt.Errorf("refusing non-regular lock file %s", path)
			}
			return nil
		}
		if !errors.Is(err, os.ErrNotExist) {
			return err
		}
		file, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
		if errors.Is(err, os.ErrExist) {
			continue
		}
		if err != nil {
			return err
		}
		return file.Close()
	}
}

// moduleRoot finds the active module root and module path.
func moduleRoot(directory string) (string, string, error) {
	command := exec.Command("go", "env", "GOMOD")
	command.Dir = directory
	output, err := command.Output()
	if err != nil {
		return "", "", fmt.Errorf("find go.mod: %w", err)
	}
	path := strings.TrimSpace(string(output))
	if path == "" || path == os.DevNull {
		return "", "", errors.New("tgo needs a Go module; run go mod init first")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", "", err
	}
	for line := range strings.SplitSeq(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) >= 2 && fields[0] == "module" {
			return filepath.Dir(path), strings.Trim(fields[1], "\""), nil
		}
	}
	return "", "", errors.New("go.mod has no module path")
}

// discover indexes tgo packages without parsing their source.
func discover(
	root string,
	module string,
	context *build.Context,
) (map[string]*packageUnit, error) {
	discovery := packageDiscovery{
		root: root, module: module, context: context,
		packages: make(map[string]*packageUnit),
	}
	err := filepath.WalkDir(root, discovery.visit)
	if err != nil {
		return nil, err
	}
	for _, unit := range discovery.packages {
		unit.Imports = discovery.packages
	}
	return discovery.packages, nil
}

type packageDiscovery struct {
	root     string
	module   string
	context  *build.Context
	packages map[string]*packageUnit
}

// visit adds tgo files and skips directories outside the active module.
func (d *packageDiscovery) visit(path string, entry fs.DirEntry, walkErr error) error {
	if walkErr != nil {
		return walkErr
	}
	if entry.IsDir() {
		return d.visitDirectory(path, entry.Name())
	}
	switch {
	case strings.HasSuffix(entry.Name(), ".tgo"):
		if strings.HasSuffix(entry.Name(), "_test.tgo") {
			return nil
		}
		return d.addSource(path)
	case outputname.Reserved(entry.Name()):
		return d.addGeneratedCandidate(path)
	default:
		return nil
	}
}

// visitDirectory skips hidden, vendor, and nested module directories.
func (d *packageDiscovery) visitDirectory(path, name string) error {
	if path == d.root {
		return nil
	}
	if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") ||
		name == "testdata" || name == "vendor" {
		return filepath.SkipDir
	}
	if _, err := os.Stat(filepath.Join(path, "go.mod")); err == nil {
		return filepath.SkipDir
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

// addSource records one possible tgo source file.
func (d *packageDiscovery) addSource(path string) error {
	unit, err := d.packageFor(filepath.Dir(path))
	if err != nil {
		return err
	}
	unit.sourcePaths = append(unit.sourcePaths, path)
	return nil
}

// addGeneratedCandidate records an output that can keep an orphan package visible.
func (d *packageDiscovery) addGeneratedCandidate(path string) error {
	unit, err := d.packageFor(filepath.Dir(path))
	if err != nil {
		return err
	}
	unit.generatedPaths = append(unit.generatedPaths, path)
	return nil
}

// packageFor returns the indexed package for one directory.
func (d *packageDiscovery) packageFor(directory string) (*packageUnit, error) {
	importPath, err := d.importPath(directory)
	if err != nil {
		return nil, err
	}
	unit := d.packages[importPath]
	if unit == nil {
		unit = &packageUnit{
			Dir:     directory,
			Path:    importPath,
			Module:  d.module,
			context: d.context,
			Models:  make(map[string]*model),
			fs:      token.NewFileSet(),
		}
		d.packages[importPath] = unit
	}
	return unit, nil
}

// importPath maps a package directory to its module import path.
func (d *packageDiscovery) importPath(directory string) (string, error) {
	relative, err := filepath.Rel(d.root, directory)
	if err != nil {
		return "", err
	}
	if relative == "." {
		return d.module, nil
	}
	return d.module + "/" + filepath.ToSlash(relative), nil
}

// readSource parses a tgo file and registers its model types.
func (p *packageUnit) readSource(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	source, err := parseSource(p.fs, path, data)
	if err != nil {
		return err
	}
	for _, model := range source.Models {
		if p.Models[model.Name] != nil {
			return fmt.Errorf(
				"%s:%d:%d: duplicate type %s",
				path,
				model.Line,
				model.Column,
				model.Name,
			)
		}
		p.Models[model.Name] = model
	}
	p.Sources = append(p.Sources, source)
	p.Files = append(p.Files, source.File)
	return nil
}

// matchingSources returns source files enabled for the current Go target.
func (p *packageUnit) matchingSources() ([]string, error) {
	if p.sourcesMatched {
		return p.matchingPaths, p.matchError
	}
	p.sourcesMatched = true
	for _, path := range p.sourcePaths {
		match, err := matchTgoFile(p.context, path)
		if err != nil {
			p.matchError = err
			return nil, err
		}
		if !match {
			continue
		}
		cgo, err := fileImportsC(path)
		if err != nil {
			p.matchError = err
			return nil, err
		}
		if cgo && !p.context.CgoEnabled {
			continue
		}
		p.usesC = p.usesC || cgo
		p.matchingPaths = append(p.matchingPaths, path)
	}
	return p.matchingPaths, nil
}

// matchTgoFile applies Go build constraints to one tgo file.
func matchTgoFile(context *build.Context, path string) (bool, error) {
	directory := filepath.Dir(path)
	name := filepath.Base(path)
	fakeName := strings.TrimSuffix(name, ".tgo") + ".s"
	fakePath := filepath.Clean(filepath.Join(directory, fakeName))
	realPath := filepath.Clean(path)
	fileContext := *context
	fileContext.OpenFile = func(requested string) (io.ReadCloser, error) {
		if filepath.Clean(requested) == fakePath {
			return os.Open(realPath)
		}
		return os.Open(requested)
	}
	match, err := fileContext.MatchFile(directory, fakeName)
	if err == nil {
		return match, nil
	}
	message := err.Error()
	if detail, ok := strings.CutPrefix(message, fakeName); ok {
		message = path + detail
	}
	return false, errors.New(message)
}

// available reports whether this package has active source or orphan output.
func (p *packageUnit) available() (bool, error) {
	paths, err := p.matchingSources()
	if err != nil {
		return false, err
	}
	if len(paths) > 0 {
		return true, nil
	}
	for _, path := range p.generatedPaths {
		owned, err := generatedFile(path)
		if err != nil {
			return false, err
		}
		if owned && !p.sourceOwnsOutput(path) {
			return true, nil
		}
	}
	return false, nil
}

// sourceOwnsOutput reports whether a current source owns one generated path.
func (p *packageUnit) sourceOwnsOutput(path string) bool {
	for _, sourcePath := range p.sourcePaths {
		if p.outputPath(sourcePath) == path {
			return true
		}
	}
	return false
}

// load parses one selected package and its active Go files.
func (p *packageUnit) load() error {
	if p.loaded {
		return p.loadError
	}
	p.loaded = true
	paths, err := p.matchingSources()
	if err != nil {
		p.loadError = err
		return err
	}
	for _, path := range paths {
		if err := p.readSource(path); err != nil {
			p.loadError = err
			return err
		}
	}
	if len(paths) > 0 {
		p.loadError = p.readGoFiles()
	}
	return p.loadError
}

// readGoFiles loads user Go files that take part in package type checks.
func (p *packageUnit) readGoFiles() error {
	entries, err := os.ReadDir(p.Dir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		mode := parser.ParseComments | parser.SkipObjectResolution
		file, cgo, err := activeGoFile(p.context, p.fs, p.Dir, entry, mode)
		if err != nil {
			return err
		}
		if file == nil {
			continue
		}
		p.usesC = p.usesC || cgo
		p.Files = append(p.Files, file)
	}
	return nil
}

// generatedFile reports whether a reserved output is a regular file.
func generatedFile(path string) (bool, error) {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if !info.Mode().IsRegular() {
		return false, fmt.Errorf("refusing non-regular output %s", path)
	}
	return true, nil
}

// selectPackages expands command patterns to tgo package paths.
func selectPackages(
	directory string,
	patterns []string,
	packages map[string]*packageUnit,
) ([]string, error) {
	if len(patterns) == 0 {
		patterns = []string{"."}
	}
	selected := make(map[string]bool)
	for _, pattern := range patterns {
		target, recursive := packagePattern(directory, pattern)
		matched := false
		for _, path := range sortedPackagePaths(packages) {
			unit := packages[path]
			if !packageMatches(unit, path, pattern, target, recursive) {
				continue
			}
			available, err := unit.available()
			if err != nil {
				return nil, err
			}
			if !available {
				continue
			}
			selected[path] = true
			matched = true
		}
		if !matched {
			return nil, fmt.Errorf("%s: no tgo packages", pattern)
		}
	}
	paths := make([]string, 0, len(selected))
	for path := range selected {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths, nil
}

// sortedPackagePaths returns stable package map keys.
func sortedPackagePaths(packages map[string]*packageUnit) []string {
	paths := make([]string, 0, len(packages))
	for path := range packages {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths
}

// packagePattern returns the directory and recursion rule for a pattern.
func packagePattern(directory, pattern string) (string, bool) {
	recursive := strings.HasSuffix(pattern, "/...") || pattern == "..."
	target := strings.TrimSuffix(pattern, "/...")
	if target == "..." {
		target = "."
	}
	if !filepath.IsAbs(target) {
		target = filepath.Join(directory, target)
	}
	return filepath.Clean(target), recursive
}

// packageMatches reports whether a package matches one command pattern.
func packageMatches(
	unit *packageUnit,
	path string,
	pattern string,
	target string,
	recursive bool,
) bool {
	if path == pattern || unit.Dir == target {
		return true
	}
	childPrefix := target + string(filepath.Separator)
	return recursive && strings.HasPrefix(unit.Dir, childPrefix)
}

type buildState uint8

const (
	buildNew buildState = iota
	buildActive
	buildDone
)

type previousFile struct {
	data   []byte
	mode   fs.FileMode
	exists bool
}

type packageBuilder struct {
	packages map[string]*packageUnit
	root     string
	module   string
	context  *build.Context
	states   map[string]buildState
	previous map[string]previousFile
	current  map[string]previousFile
	order    []string
}

// build compiles dependencies before one package and writes its outputs.
func (b *packageBuilder) build(path string) error {
	switch b.states[path] {
	case buildDone:
		return nil
	case buildActive:
		return fmt.Errorf("import cycle at %s", path)
	}
	b.states[path] = buildActive
	unit := b.packages[path]
	if err := unit.load(); err != nil {
		return err
	}
	if len(unit.Sources) == 0 {
		imports, err := b.localGoImports(path)
		if err != nil {
			return err
		}
		for _, dependency := range imports {
			if err := b.buildImport(dependency); err != nil {
				return err
			}
		}
		if err := b.removeStaleOutputs(unit, expectedOutputs(unit, nil)); err != nil {
			return err
		}
		b.states[path] = buildDone
		return nil
	}
	for _, dependency := range importsOf(unit.Files) {
		if err := b.buildImport(dependency); err != nil {
			return err
		}
	}
	outputs, err := unit.compile()
	if err != nil {
		return err
	}
	for _, name := range sortedOutputPaths(outputs) {
		data := outputs[name]
		if err := b.write(name, data); err != nil {
			return err
		}
	}
	if err := b.removeStaleOutputs(unit, expectedOutputs(unit, outputs)); err != nil {
		return err
	}
	b.states[path] = buildDone
	return nil
}

// buildImport follows local Go packages until it reaches each tgo package.
func (b *packageBuilder) buildImport(path string) error {
	if dependency := b.packages[path]; dependency != nil {
		available, err := dependency.available()
		if err != nil {
			return err
		}
		if available {
			return b.build(path)
		}
	}
	if path != b.module && !strings.HasPrefix(path, b.module+"/") {
		return nil
	}
	switch b.states[path] {
	case buildDone:
		return nil
	case buildActive:
		return fmt.Errorf("import cycle at %s", path)
	}
	b.states[path] = buildActive
	imports, err := b.localGoImports(path)
	if err != nil {
		return err
	}
	for _, dependency := range imports {
		if err := b.buildImport(dependency); err != nil {
			return err
		}
	}
	b.states[path] = buildDone
	return nil
}

// localGoImports reads active Go imports from one package in the main module.
func (b *packageBuilder) localGoImports(path string) ([]string, error) {
	relative := strings.TrimPrefix(path, b.module)
	relative = strings.TrimPrefix(relative, "/")
	directory := filepath.Clean(filepath.Join(b.root, filepath.FromSlash(relative)))
	inside, err := filepath.Rel(b.root, directory)
	if err != nil {
		return nil, err
	}
	if inside == ".." || strings.HasPrefix(inside, ".."+string(filepath.Separator)) {
		return nil, nil
	}
	nested, err := nestedModule(directory, b.root)
	if err != nil {
		return nil, err
	}
	if nested {
		return nil, nil
	}
	entries, err := os.ReadDir(directory)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	files := make([]*ast.File, 0)
	set := token.NewFileSet()
	for _, entry := range entries {
		file, _, err := activeGoFile(
			b.context,
			set,
			directory,
			entry,
			parser.ImportsOnly,
		)
		if err != nil {
			return nil, err
		}
		if file != nil {
			files = append(files, file)
		}
	}
	return importsOf(files), nil
}

// activeGoFile parses one active user Go file.
func activeGoFile(
	context *build.Context,
	set *token.FileSet,
	directory string,
	entry os.DirEntry,
	mode parser.Mode,
) (*ast.File, bool, error) {
	name := entry.Name()
	if entry.IsDir() || !strings.HasSuffix(name, ".go") ||
		strings.HasSuffix(name, "_test.go") {
		return nil, false, nil
	}
	path := filepath.Join(directory, name)
	if outputname.Reserved(name) {
		owned, err := generatedFile(path)
		if err != nil || owned {
			return nil, false, err
		}
	}
	matches, err := context.MatchFile(directory, name)
	if err != nil || !matches {
		return nil, false, err
	}
	file, err := parser.ParseFile(set, path, nil, mode)
	if err != nil {
		return nil, false, err
	}
	cgo := importsC(file)
	if cgo && !context.CgoEnabled {
		return nil, false, nil
	}
	return file, cgo, nil
}

// nestedModule reports whether a directory belongs to another module.
func nestedModule(directory string, root string) (bool, error) {
	for current := directory; current != root; current = filepath.Dir(current) {
		if _, err := os.Stat(filepath.Join(current, "go.mod")); err == nil {
			return true, nil
		} else if !errors.Is(err, os.ErrNotExist) {
			return false, err
		}
		parent := filepath.Dir(current)
		if parent == current {
			return true, nil
		}
	}
	return false, nil
}

// expectedOutputs includes active output and output owned by inactive source.
func expectedOutputs(unit *packageUnit, outputs map[string][]byte) map[string]bool {
	expected := make(map[string]bool, len(outputs)+len(unit.sourcePaths))
	for path := range outputs {
		expected[path] = true
	}
	for _, sourcePath := range unit.sourcePaths {
		expected[unit.outputPath(sourcePath)] = true
	}
	return expected
}

// sortedOutputPaths returns stable generated output map keys.
func sortedOutputPaths(outputs map[string][]byte) []string {
	paths := make([]string, 0, len(outputs))
	for path := range outputs {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths
}

// importsOf returns the sorted import paths from a set of files.
func importsOf(files []*ast.File) []string {
	imports := make(map[string]bool)
	for _, file := range files {
		for _, spec := range file.Imports {
			path, err := strconv.Unquote(spec.Path.Value)
			if err == nil && path != "C" {
				imports[path] = true
			}
		}
	}
	paths := make([]string, 0, len(imports))
	for path := range imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths
}

// fileImportsC reports whether one source file imports C.
func fileImportsC(path string) (bool, error) {
	file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ImportsOnly)
	if err != nil {
		return false, err
	}
	return importsC(file), nil
}

// importsC reports whether one parsed file imports C.
func importsC(file *ast.File) bool {
	for _, spec := range file.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err == nil && path == "C" {
			return true
		}
	}
	return false
}

// write replaces one generated file and saves its prior state.
func (b *packageBuilder) write(path string, data []byte) error {
	if b.changed(path) {
		return fmt.Errorf("output changed twice in one build: %s", path)
	}
	previous, err := readFileSnapshot(path)
	if err != nil {
		return err
	}
	mode := fs.FileMode(0o644)
	if previous.exists {
		mode = previous.mode
	}
	changed, writtenMode, err := atomicWriteFile(path, data, mode, previous.exists)
	if changed {
		b.previous[path] = previous
		b.current[path] = previousFile{data: data, mode: writtenMode, exists: true}
		b.order = append(b.order, path)
	}
	return err
}

// removeStaleOutputs removes generated files with no current tgo source.
func (b *packageBuilder) removeStaleOutputs(
	unit *packageUnit,
	outputs map[string]bool,
) error {
	entries, err := os.ReadDir(unit.Dir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		path := filepath.Join(unit.Dir, entry.Name())
		if !staleOutput(entry, path, outputs) {
			continue
		}
		if err := b.removeGenerated(path); err != nil {
			return err
		}
	}
	return nil
}

// staleOutput reports whether a generated file is absent from new outputs.
func staleOutput(entry os.DirEntry, path string, outputs map[string]bool) bool {
	if !outputname.Reserved(entry.Name()) {
		return false
	}
	return !outputs[path]
}

// removeGenerated removes a tgo-owned file and saves it for rollback.
func (b *packageBuilder) removeGenerated(path string) error {
	if b.changed(path) {
		return fmt.Errorf("output changed twice in one build: %s", path)
	}
	owned, err := generatedFile(path)
	if err != nil {
		return err
	}
	if !owned {
		return nil
	}
	previous, err := readFileSnapshot(path)
	if err != nil {
		return err
	}
	if !previous.exists {
		return fmt.Errorf("output changed during build: %s", path)
	}
	changed, err := atomicRemoveFile(path)
	if changed {
		b.previous[path] = previous
		b.current[path] = previousFile{}
		b.order = append(b.order, path)
	}
	return err
}

// restore puts every changed output back after a failed build.
func (b *packageBuilder) restore() error {
	var failures []error
	for index := len(b.order) - 1; index >= 0; index-- {
		path := b.order[index]
		previous := b.previous[path]
		if err := fileUnchanged(path, b.current[path]); err != nil {
			failures = append(failures, err)
			continue
		}
		var err error
		if previous.exists {
			_, _, err = atomicWriteFile(path, previous.data, previous.mode, true)
		} else {
			_, err = atomicRemoveFile(path)
		}
		if err != nil {
			failures = append(failures, err)
		}
	}
	return errors.Join(failures...)
}

// changed reports whether this transaction already mutated one path.
func (b *packageBuilder) changed(path string) bool {
	_, changed := b.previous[path]
	return changed
}

// readFileSnapshot reads one regular file without following a known symlink.
func readFileSnapshot(path string) (previousFile, error) {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return previousFile{}, nil
	}
	if err != nil {
		return previousFile{}, err
	}
	if !info.Mode().IsRegular() {
		return previousFile{}, fmt.Errorf("refusing non-regular output %s", path)
	}
	file, err := os.Open(path)
	if err != nil {
		return previousFile{}, err
	}
	opened, err := file.Stat()
	if err != nil {
		return previousFile{}, errors.Join(err, file.Close())
	}
	if !os.SameFile(info, opened) {
		changeErr := fmt.Errorf("output changed while opening: %s", path)
		return previousFile{}, errors.Join(changeErr, file.Close())
	}
	data, err := io.ReadAll(file)
	if err != nil {
		return previousFile{}, errors.Join(err, file.Close())
	}
	if err := file.Close(); err != nil {
		return previousFile{}, err
	}
	mode := chmodMode(info.Mode())
	return previousFile{data: data, mode: mode, exists: true}, nil
}

// atomicWriteFile writes, syncs, and replaces one file in its directory.
func atomicWriteFile(
	path string,
	data []byte,
	mode fs.FileMode,
	preserveMode bool,
) (changed bool, writtenMode fs.FileMode, err error) {
	temporaryPath := filepath.Join(
		filepath.Dir(path),
		"."+filepath.Base(path)+".tmp-"+cryptorand.Text(),
	)
	temporary, err := os.OpenFile(
		temporaryPath,
		os.O_CREATE|os.O_EXCL|os.O_WRONLY,
		mode,
	)
	if err != nil {
		return false, 0, err
	}
	closed := false
	published := false
	defer func() {
		if !closed {
			err = errors.Join(err, temporary.Close())
		}
		if !published {
			removeErr := os.Remove(temporaryPath)
			if removeErr != nil && !errors.Is(removeErr, os.ErrNotExist) {
				err = errors.Join(err, removeErr)
			}
		}
	}()
	if _, err := temporary.Write(data); err != nil {
		return false, 0, err
	}
	if preserveMode {
		if err := temporary.Chmod(mode); err != nil {
			return false, 0, err
		}
	}
	if err := temporary.Sync(); err != nil {
		return false, 0, err
	}
	temporaryInfo, err := temporary.Stat()
	if err != nil {
		return false, 0, err
	}
	writtenMode = chmodMode(temporaryInfo.Mode())
	closeErr := temporary.Close()
	closed = true
	if closeErr != nil {
		return false, 0, closeErr
	}
	if err := replaceFile(temporaryPath, path); err != nil {
		return false, 0, err
	}
	published = true
	if err := syncDirectory(filepath.Dir(path)); err != nil {
		return true, writtenMode, err
	}
	return true, writtenMode, nil
}

// chmodMode returns file bits that chmod can preserve.
func chmodMode(mode fs.FileMode) fs.FileMode {
	return mode & (fs.ModePerm | fs.ModeSetuid | fs.ModeSetgid | fs.ModeSticky)
}

// atomicRemoveFile removes one file and syncs its directory.
func atomicRemoveFile(path string) (bool, error) {
	if err := os.Remove(path); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return false, nil
		}
		return false, err
	}
	if err := syncDirectory(filepath.Dir(path)); err != nil {
		return true, err
	}
	return true, nil
}

// fileUnchanged checks that no other process changed one output state.
func fileUnchanged(path string, expected previousFile) error {
	actual, err := readFileSnapshot(path)
	if err != nil {
		return err
	}
	if actual.exists != expected.exists {
		return fmt.Errorf("output changed during build: %s", path)
	}
	if !actual.exists {
		return nil
	}
	if actual.mode != expected.mode || !bytes.Equal(actual.data, expected.data) {
		return fmt.Errorf("output changed during build: %s", path)
	}
	return nil
}
