package compiler

import (
	"fmt"
	"go/parser"
	"go/token"
	"go/types"

	"tgo/pkg/syntax"
)

const generatedHeader = "// Code generated by tgo. DO NOT EDIT."

// File is one prepared source file.
type File struct {
	Name string
	Data []byte
}

// PackageInput contains one package with all file-system work complete.
type PackageInput struct {
	Directory string
	Path      string
	Sources   []File
	GoFiles   []File
	Imports   map[string]*CompiledPackage
	FileSet   *token.FileSet
	Importer  types.Importer
	UsesC     bool
}

// CompiledSource contains one source syntax tree and its projection metadata.
type CompiledSource struct {
	Name   string
	Syntax *syntax.File
	NonNil map[token.Pos]bool
}

// CompiledPackage contains one generated and typed Go projection.
type CompiledPackage struct {
	Path       string
	Outputs    map[string][]byte
	Sources    []CompiledSource
	Files      *token.FileSet
	Package    *types.Package
	Facts      *ProjectionFacts
	References map[token.Pos]types.Object
	unit       *packageUnit
}

// Compile checks and emits one prepared package in memory.
func Compile(input PackageInput) (*CompiledPackage, []error) {
	files := input.FileSet
	if files == nil {
		files = token.NewFileSet()
	}
	unit := &packageUnit{
		Dir: input.Directory, Path: input.Path,
		Models: make(map[string]*model), Imports: make(map[string]*packageUnit),
		usesC: input.UsesC, fs: files, importer: input.Importer,
	}
	for path, imported := range input.Imports {
		if imported != nil {
			unit.Imports[path] = imported.unit
		}
	}
	for _, file := range input.Sources {
		source, err := parseSource(files, file.Name, file.Data)
		if err != nil {
			return nil, []error{err}
		}
		for _, declaration := range source.Models {
			if unit.Models[declaration.Name] != nil {
				return nil, []error{fmt.Errorf(
					"%s:%d:%d: duplicate type %s",
					file.Name, declaration.Line, declaration.Column, declaration.Name,
				)}
			}
			unit.Models[declaration.Name] = declaration
		}
		unit.Sources = append(unit.Sources, source)
		unit.Files = append(unit.Files, source.File)
	}
	for _, file := range input.GoFiles {
		parsed, err := parser.ParseFile(
			files, file.Name, file.Data,
			parser.ParseComments|parser.SkipObjectResolution,
		)
		if err != nil {
			return nil, []error{err}
		}
		unit.Files = append(unit.Files, parsed)
	}
	outputs, err := unit.compile()
	if err != nil {
		return nil, []error{err}
	}
	sources := make([]CompiledSource, 0, len(unit.Sources))
	for _, source := range unit.Sources {
		sources = append(sources, CompiledSource{
			Name: source.Name, Syntax: source.Tree, NonNil: source.NonNil,
		})
	}
	return &CompiledPackage{
		Path: input.Path, Outputs: outputs, Sources: sources,
		Files: files, Package: unit.typed, Facts: newProjectionFacts(unit),
		References: projectionReferences(unit), unit: unit,
	}, nil
}
