// Code generated by tgo. DO NOT EDIT.

// Package format formats TGo source.
package format

import (
	goformat "go/format"
	"go/token"

	"tgo/pkg/syntax"
)

// Source formats one complete TGo source file.
func Source(filename string, source []byte) ([]byte, error) {
	if formatted, err := goformat.Source(source); err == nil {
		return formatted, nil
	}
	files := token.NewFileSet()
	file, tgoErr := syntax.ParseFile(
		files,
		filename,
		source,
		syntax.ParseComments|syntax.AllErrors|syntax.AllowInvalidModels,
	)
	if tgoErr != nil {
		return nil, tgoErr
	}
	return newPrinter(files, file, source).printFile(), nil
}
