version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - gocritic
    - ineffassign
    - lll
    - revive
  settings:
    lll:
      line-length: 100
      tab-width: 4
  exclusions:
    presets: []

formatters:
  enable:
    - gofmt
    - goimports
