// Code generated by tgo. DO NOT EDIT.

package model

import (
	"encoding/json"
	"encoding/json/jsontext"
	jsonv2 "encoding/json/v2"
	"fmt"
	"reflect"
	"strings"
)

func tgoJSONExternalExternalJSONTo[T interface{}](out *jsontext.Encoder, name string, payload T) error {
	if err := out.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := out.WriteToken(jsontext.String(name)); err != nil {
		return err
	}
	if err := jsonv2.MarshalEncode(out, payload); err != nil {
		return err
	}
	return out.WriteToken(jsontext.EndObject)
}
func tgoJSONExternalAdjacentJSONTo[T interface{}](
	out *jsontext.Encoder, tag string, name string, content string, payload T,
) error {
	if err := out.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := out.WriteToken(jsontext.String(tag)); err != nil {
		return err
	}
	if err := out.WriteToken(jsontext.String(name)); err != nil {
		return err
	}
	if err := out.WriteToken(jsontext.String(content)); err != nil {
		return err
	}
	if err := jsonv2.MarshalEncode(out, payload); err != nil {
		return err
	}
	return out.WriteToken(jsontext.EndObject)
}

// JSONExternal requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONExternalTag uint8

const (
	JSONExternalTagCreated JSONExternalTag = iota + 1
	JSONExternalTagEmpty
	JSONExternalTagLarge
)

type JSONExternal struct {
	tgoTag     JSONExternalTag
	tgoCreated JSONExternalCreated
	tgoPayload interface{}
}

// Tag returns the active tag.
func (v JSONExternal) Tag() JSONExternalTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONExternal) UnknownTag() string {
	return fmt.Sprintf("JSONExternal: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONExternalCreated is the Created payload.
type JSONExternalCreated struct {
	ID     string    `json:"account_id"`
	Reason string    `json:"reason,omitempty"`
	Custom JSONField `json:"custom,omitempty"`
}

// JSONExternal constructs JSONExternal. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONExternalCreated) JSONExternal() JSONExternal {
	return JSONExternal{tgoTag: JSONExternalTagCreated, tgoCreated: value}
}

// CreatedPayload requires Created. No tag check.
func (v JSONExternal) CreatedPayload() JSONExternalCreated { return v.tgoCreated }

// JSONExternalEmpty is the Empty payload.
type JSONExternalEmpty struct{}

// JSONExternal constructs JSONExternal. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONExternalEmpty) JSONExternal() JSONExternal {
	return JSONExternal{tgoTag: JSONExternalTagEmpty}
}

// EmptyPayload requires Empty. No tag check.
func (JSONExternal) EmptyPayload() JSONExternalEmpty { return JSONExternalEmpty{} }

// JSONExternalLarge is the Large payload.
type JSONExternalLarge struct {
	Data [100]byte
}

// JSONExternal constructs JSONExternal. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONExternalLarge) JSONExternal() JSONExternal {
	return JSONExternal{tgoTag: JSONExternalTagLarge, tgoPayload: value}
}

// LargePayload requires Large. No tag check.
func (v JSONExternal) LargePayload() JSONExternalLarge { return v.tgoPayload.(JSONExternalLarge) }

func (v JSONExternal) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONExternalTagCreated:
		payload := v.CreatedPayload()
		return json.Marshal(struct {
			Payload JSONExternalCreated `json:"created"`
		}{Payload: payload})
	case JSONExternalTagEmpty:
		payload := v.EmptyPayload()
		return json.Marshal(struct {
			Payload JSONExternalEmpty `json:"Empty"`
		}{Payload: payload})
	case JSONExternalTagLarge:
		payload := v.LargePayload()
		return json.Marshal(struct {
			Payload JSONExternalLarge `json:"Large"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid JSONExternal JSON tag")
	}
}

func (v JSONExternal) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONExternalTagCreated:
		payload := v.CreatedPayload()
		return tgoJSONExternalExternalJSONTo(out, "created", payload)
	case JSONExternalTagEmpty:
		payload := v.EmptyPayload()
		return tgoJSONExternalExternalJSONTo(out, "Empty", payload)
	case JSONExternalTagLarge:
		payload := v.LargePayload()
		return tgoJSONExternalExternalJSONTo(out, "Large", payload)
	default:
		return fmt.Errorf("invalid JSONExternal JSON tag")
	}
}

func (v *JSONExternal) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one JSONExternal JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "created":
		var payload JSONExternalCreated
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.JSONExternal()
		return nil
	case "Empty":
		var payload JSONExternalEmpty
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.JSONExternal()
		return nil
	case "Large":
		var payload JSONExternalLarge
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.JSONExternal()
		return nil
	default:
		return fmt.Errorf("unknown JSONExternal JSON variant %q", variant)
	}
}

func (v *JSONExternal) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one JSONExternal JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "created":
			current = 1
		case "Empty":
			current = 2
		case "Large":
			current = 3
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return fmt.Errorf("expected one JSONExternal JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown JSONExternal JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload JSONExternalCreated
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.JSONExternal()
		return nil
	case 2:
		var payload JSONExternalEmpty
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.JSONExternal()
		return nil
	case 3:
		var payload JSONExternalLarge
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.JSONExternal()
		return nil
	default:
		return fmt.Errorf("invalid JSONExternal JSON tag")
	}
}

// JSONInternal requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONInternalTag uint8

const (
	JSONInternalTagCreated JSONInternalTag = iota + 1
	JSONInternalTagEmpty
)

type JSONInternal struct {
	tgoTag     JSONInternalTag
	tgoCreated JSONInternalCreated
}

// Tag returns the active tag.
func (v JSONInternal) Tag() JSONInternalTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONInternal) UnknownTag() string {
	return fmt.Sprintf("JSONInternal: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONInternalCreated is the Created payload.
type JSONInternalCreated struct {
	ID     string    `json:"account_id"`
	Reason string    `json:"reason,omitempty"`
	Custom JSONField `json:"custom,omitempty"`
}

// JSONInternal constructs JSONInternal. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONInternalCreated) JSONInternal() JSONInternal {
	return JSONInternal{tgoTag: JSONInternalTagCreated, tgoCreated: value}
}

// CreatedPayload requires Created. No tag check.
func (v JSONInternal) CreatedPayload() JSONInternalCreated { return v.tgoCreated }

// JSONInternalEmpty is the Empty payload.
type JSONInternalEmpty struct{}

// JSONInternal constructs JSONInternal. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONInternalEmpty) JSONInternal() JSONInternal {
	return JSONInternal{tgoTag: JSONInternalTagEmpty}
}

// EmptyPayload requires Empty. No tag check.
func (JSONInternal) EmptyPayload() JSONInternalEmpty { return JSONInternalEmpty{} }

func (v JSONInternal) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONInternalTagCreated:
		payload := v.CreatedPayload()
		payloadData, err := json.Marshal(payload)
		if err != nil {
			return nil, err
		}
		if len(payloadData) < 2 || payloadData[0] != '{' || payloadData[len(payloadData)-1] != '}' {
			return nil, fmt.Errorf("expected JSONInternal JSON payload object")
		}
		if len(payloadData) == 2 {
			return []byte("{\"type\":\"created\"}"), nil
		}
		result := make([]byte, 0, len(payloadData)+17)
		result = append(result, "{\"type\":\"created\""...)
		result = append(result, ',')
		result = append(result, payloadData[1:]...)
		return result, nil
	case JSONInternalTagEmpty:
		payload := v.EmptyPayload()
		payloadData, err := json.Marshal(payload)
		if err != nil {
			return nil, err
		}
		if len(payloadData) < 2 || payloadData[0] != '{' || payloadData[len(payloadData)-1] != '}' {
			return nil, fmt.Errorf("expected JSONInternal JSON payload object")
		}
		if len(payloadData) == 2 {
			return []byte("{\"type\":\"Empty\"}"), nil
		}
		result := make([]byte, 0, len(payloadData)+15)
		result = append(result, "{\"type\":\"Empty\""...)
		result = append(result, ',')
		result = append(result, payloadData[1:]...)
		return result, nil
	default:
		return nil, fmt.Errorf("invalid JSONInternal JSON tag")
	}
}

func (v JSONInternal) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONInternalTagCreated:
		payload := v.CreatedPayload()
		_, marshalsJSON := interface{}(payload).(interface{ MarshalJSON() ([]byte, error) })
		_, marshalsText := interface{}(payload).(interface{ MarshalText() ([]byte, error) })
		_, marshalsJSONTo := interface{}(payload).(interface{ MarshalJSONTo(*jsontext.Encoder) error })
		if marshalsJSON || marshalsText || marshalsJSONTo {
			data, err := v.MarshalJSON()
			if err != nil {
				return err
			}
			return out.WriteValue(data)
		}
		return jsonv2.MarshalEncode(out, struct {
			Variant string `json:"type"`
			JSONInternalCreated
		}{Variant: "created", JSONInternalCreated: payload})
	case JSONInternalTagEmpty:
		payload := v.EmptyPayload()
		_, marshalsJSON := interface{}(payload).(interface{ MarshalJSON() ([]byte, error) })
		_, marshalsText := interface{}(payload).(interface{ MarshalText() ([]byte, error) })
		_, marshalsJSONTo := interface{}(payload).(interface{ MarshalJSONTo(*jsontext.Encoder) error })
		if marshalsJSON || marshalsText || marshalsJSONTo {
			data, err := v.MarshalJSON()
			if err != nil {
				return err
			}
			return out.WriteValue(data)
		}
		return jsonv2.MarshalEncode(out, struct {
			Variant string `json:"type"`
			JSONInternalEmpty
		}{Variant: "Empty", JSONInternalEmpty: payload})
	default:
		return fmt.Errorf("invalid JSONInternal JSON tag")
	}
}

func (v *JSONInternal) UnmarshalJSON(data []byte) error {
	var variant string
	var object struct {
		Tag string `json:"type"`
	}
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if object.Tag == "" {
		return fmt.Errorf("missing JSONInternal JSON tag")
	}
	variant = object.Tag
	switch variant {
	case "created":
		var payload JSONInternalCreated
		if err := json.Unmarshal(data, &payload); err != nil {
			return err
		}
		*v = payload.JSONInternal()
		return nil
	case "Empty":
		var payload JSONInternalEmpty
		if err := json.Unmarshal(data, &payload); err != nil {
			return err
		}
		*v = payload.JSONInternal()
		return nil
	default:
		return fmt.Errorf("unknown JSONInternal JSON variant %q", variant)
	}
}

func (v *JSONInternal) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	data, err := in.ReadValue()
	if err != nil {
		return err
	}
	return v.UnmarshalJSON(data)
}

// JSONAdjacent requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONAdjacentTag uint8

const (
	JSONAdjacentTagCreated JSONAdjacentTag = iota + 1
	JSONAdjacentTagEmpty
)

type JSONAdjacent struct {
	tgoTag     JSONAdjacentTag
	tgoCreated JSONAdjacentCreated
}

// Tag returns the active tag.
func (v JSONAdjacent) Tag() JSONAdjacentTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONAdjacent) UnknownTag() string {
	return fmt.Sprintf("JSONAdjacent: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONAdjacentCreated is the Created payload.
type JSONAdjacentCreated struct {
	ID     string    `json:"account_id"`
	Reason string    `json:"reason,omitempty"`
	Custom JSONField `json:"custom,omitempty"`
}

// JSONAdjacent constructs JSONAdjacent. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONAdjacentCreated) JSONAdjacent() JSONAdjacent {
	return JSONAdjacent{tgoTag: JSONAdjacentTagCreated, tgoCreated: value}
}

// CreatedPayload requires Created. No tag check.
func (v JSONAdjacent) CreatedPayload() JSONAdjacentCreated { return v.tgoCreated }

// JSONAdjacentEmpty is the Empty payload.
type JSONAdjacentEmpty struct{}

// JSONAdjacent constructs JSONAdjacent. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONAdjacentEmpty) JSONAdjacent() JSONAdjacent {
	return JSONAdjacent{tgoTag: JSONAdjacentTagEmpty}
}

// EmptyPayload requires Empty. No tag check.
func (JSONAdjacent) EmptyPayload() JSONAdjacentEmpty { return JSONAdjacentEmpty{} }

func (v JSONAdjacent) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONAdjacentTagCreated:
		payload := v.CreatedPayload()
		return json.Marshal(struct {
			Variant string              `json:"type"`
			Payload JSONAdjacentCreated `json:"data"`
		}{Variant: "created", Payload: payload})
	case JSONAdjacentTagEmpty:
		payload := v.EmptyPayload()
		return json.Marshal(struct {
			Variant string            `json:"type"`
			Payload JSONAdjacentEmpty `json:"data"`
		}{Variant: "Empty", Payload: payload})
	default:
		return nil, fmt.Errorf("invalid JSONAdjacent JSON tag")
	}
}

func (v JSONAdjacent) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONAdjacentTagCreated:
		payload := v.CreatedPayload()
		return tgoJSONExternalAdjacentJSONTo(out, "type", "created", "data", payload)
	case JSONAdjacentTagEmpty:
		payload := v.EmptyPayload()
		return tgoJSONExternalAdjacentJSONTo(out, "type", "Empty", "data", payload)
	default:
		return fmt.Errorf("invalid JSONAdjacent JSON tag")
	}
}

func (v *JSONAdjacent) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object struct {
		Tag     string          `json:"type"`
		Content json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if object.Tag == "" {
		return fmt.Errorf("missing JSONAdjacent JSON tag")
	}
	variant = object.Tag
	payloadData = object.Content
	if payloadData == nil {
		return fmt.Errorf("missing JSONAdjacent JSON content")
	}
	switch variant {
	case "created":
		var payload JSONAdjacentCreated
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.JSONAdjacent()
		return nil
	case "Empty":
		var payload JSONAdjacentEmpty
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.JSONAdjacent()
		return nil
	default:
		return fmt.Errorf("unknown JSONAdjacent JSON variant %q", variant)
	}
}

func (v *JSONAdjacent) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("missing JSONAdjacent JSON tag")
	}
	var contentData jsontext.Value
	selected := 0
	var unknown string
	contentPresent := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		field := 0
		switch {
		case wireName == "type":
			field = 1
		case wireName == "data":
			field = 2
		case strings.EqualFold(wireName, "type"):
			field = 1
		case strings.EqualFold(wireName, "data"):
			field = 2
		}
		switch field {
		case 1:
			if in.PeekKind() == 'n' {
				if _, err := in.ReadToken(); err != nil {
					return err
				}
				break
			}
			if in.PeekKind() != '"' {
				var invalid string
				return jsonv2.UnmarshalDecode(in, &invalid)
			}
			tagToken, err := in.ReadToken()
			if err != nil {
				return err
			}
			variantName := tagToken.String()
			selected = 0
			unknown = ""
			switch variantName {
			case "created":
				selected = 1
			case "Empty":
				selected = 2
			default:
				unknown = string(append([]byte(nil), variantName...))
			}
		case 2:
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			contentData = append(contentData[:0], raw...)
			contentPresent = true
		default:
			if err := in.SkipValue(); err != nil {
				return err
			}
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if selected == 0 && unknown == "" {
		return fmt.Errorf("missing JSONAdjacent JSON tag")
	}
	if !contentPresent {
		return fmt.Errorf("missing JSONAdjacent JSON content")
	}
	if selected == 0 {
		return fmt.Errorf("unknown JSONAdjacent JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload JSONAdjacentCreated
		if err := jsonv2.Unmarshal(contentData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.JSONAdjacent()
		return nil
	case 2:
		var payload JSONAdjacentEmpty
		if err := jsonv2.Unmarshal(contentData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.JSONAdjacent()
		return nil
	default:
		return fmt.Errorf("invalid JSONAdjacent JSON tag")
	}
}

// JSONUntagged requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONUntaggedTag uint8

const (
	JSONUntaggedTagNumber JSONUntaggedTag = iota + 1
	JSONUntaggedTagText
	JSONUntaggedTagOther
)

type JSONUntagged struct {
	tgoTag    JSONUntaggedTag
	tgoNumber JSONUntaggedNumber
	tgoText   JSONUntaggedText
	tgoOther  JSONUntaggedOther
}

// Tag returns the active tag.
func (v JSONUntagged) Tag() JSONUntaggedTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONUntagged) UnknownTag() string {
	return fmt.Sprintf("JSONUntagged: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONUntaggedNumber is the Number payload.
type JSONUntaggedNumber struct {
	Value int `json:"value"`
}

// JSONUntagged constructs JSONUntagged. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONUntaggedNumber) JSONUntagged() JSONUntagged {
	return JSONUntagged{tgoTag: JSONUntaggedTagNumber, tgoNumber: value}
}

// NumberPayload requires Number. No tag check.
func (v JSONUntagged) NumberPayload() JSONUntaggedNumber { return v.tgoNumber }

// JSONUntaggedText is the Text payload.
type JSONUntaggedText struct {
	Value string `json:"value"`
}

// JSONUntagged constructs JSONUntagged. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONUntaggedText) JSONUntagged() JSONUntagged {
	return JSONUntagged{tgoTag: JSONUntaggedTagText, tgoText: value}
}

// TextPayload requires Text. No tag check.
func (v JSONUntagged) TextPayload() JSONUntaggedText { return v.tgoText }

// JSONUntaggedOther is the Other payload.
type JSONUntaggedOther struct {
	Value string `json:"value"`
}

// JSONUntagged constructs JSONUntagged. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONUntaggedOther) JSONUntagged() JSONUntagged {
	return JSONUntagged{tgoTag: JSONUntaggedTagOther, tgoOther: value}
}

// OtherPayload requires Other. No tag check.
func (v JSONUntagged) OtherPayload() JSONUntaggedOther { return v.tgoOther }

func (v JSONUntagged) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONUntaggedTagNumber:
		payload := v.NumberPayload()
		return json.Marshal(payload)
	case JSONUntaggedTagText:
		payload := v.TextPayload()
		return json.Marshal(payload)
	case JSONUntaggedTagOther:
		payload := v.OtherPayload()
		return json.Marshal(payload)
	default:
		return nil, fmt.Errorf("invalid JSONUntagged JSON tag")
	}
}

func (v JSONUntagged) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONUntaggedTagNumber:
		payload := v.NumberPayload()
		return jsonv2.MarshalEncode(out, payload)
	case JSONUntaggedTagText:
		payload := v.TextPayload()
		return jsonv2.MarshalEncode(out, payload)
	case JSONUntaggedTagOther:
		payload := v.OtherPayload()
		return jsonv2.MarshalEncode(out, payload)
	default:
		return fmt.Errorf("invalid JSONUntagged JSON tag")
	}
}

func (v *JSONUntagged) UnmarshalJSON(data []byte) error {
	{
		var payload JSONUntaggedNumber
		if err := json.Unmarshal(data, &payload); err == nil {
			*v = payload.JSONUntagged()
			return nil
		}
	}
	{
		var payload JSONUntaggedText
		if err := json.Unmarshal(data, &payload); err == nil {
			*v = payload.JSONUntagged()
			return nil
		}
	}
	{
		var payload JSONUntaggedOther
		if err := json.Unmarshal(data, &payload); err == nil {
			*v = payload.JSONUntagged()
			return nil
		}
	}
	return fmt.Errorf("no matching JSONUntagged JSON variant")
}

func (v *JSONUntagged) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	data, err := in.ReadValue()
	if err != nil {
		return err
	}
	return v.UnmarshalJSON(data)
}

// JSONNested requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONNestedTag uint8

const (
	JSONNestedTagNested JSONNestedTag = iota + 1
)

type JSONNested struct {
	tgoTag    JSONNestedTag
	tgoNested JSONNestedNested
}

// Tag returns the active tag.
func (v JSONNested) Tag() JSONNestedTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONNested) UnknownTag() string {
	return fmt.Sprintf("JSONNested: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONNestedNested is the Nested payload.
type JSONNestedNested struct {
	Value JSONExternal `json:"value"`
}

// JSONNested constructs JSONNested. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONNestedNested) JSONNested() JSONNested {
	return JSONNested{tgoTag: JSONNestedTagNested, tgoNested: value}
}

// NestedPayload requires Nested. No tag check.
func (v JSONNested) NestedPayload() JSONNestedNested { return v.tgoNested }

func (v JSONNested) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONNestedTagNested:
		payload := v.NestedPayload()
		return json.Marshal(struct {
			Payload JSONNestedNested `json:"Nested"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid JSONNested JSON tag")
	}
}

func (v JSONNested) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONNestedTagNested:
		payload := v.NestedPayload()
		return tgoJSONExternalExternalJSONTo(out, "Nested", payload)
	default:
		return fmt.Errorf("invalid JSONNested JSON tag")
	}
}

func (v *JSONNested) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one JSONNested JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Nested":
		var payload JSONNestedNested
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.JSONNested()
		return nil
	default:
		return fmt.Errorf("unknown JSONNested JSON variant %q", variant)
	}
}

func (v *JSONNested) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one JSONNested JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Nested":
			current = 1
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return fmt.Errorf("expected one JSONNested JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown JSONNested JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload JSONNestedNested
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.JSONNested()
		return nil
	default:
		return fmt.Errorf("invalid JSONNested JSON tag")
	}
}

// JSONCustom requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONCustomTag uint8

const (
	JSONCustomTagValue JSONCustomTag = iota + 1
)

type JSONCustom struct {
	tgoTag   JSONCustomTag
	tgoValue JSONCustomValue
}

// Tag returns the active tag.
func (v JSONCustom) Tag() JSONCustomTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONCustom) UnknownTag() string {
	return fmt.Sprintf("JSONCustom: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONCustomValue is the Value payload.
type JSONCustomValue struct {
	Value JSONField `json:"value"`
}

// JSONCustom constructs JSONCustom. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONCustomValue) JSONCustom() JSONCustom {
	return JSONCustom{tgoTag: JSONCustomTagValue, tgoValue: value}
}

// ValuePayload requires Value. No tag check.
func (v JSONCustom) ValuePayload() JSONCustomValue { return v.tgoValue }

func (v JSONCustom) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONCustomTagValue:
		payload := v.ValuePayload()
		return json.Marshal(struct {
			Payload JSONCustomValue `json:"Value"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid JSONCustom JSON tag")
	}
}

func (v JSONCustom) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONCustomTagValue:
		payload := v.ValuePayload()
		return tgoJSONExternalExternalJSONTo(out, "Value", payload)
	default:
		return fmt.Errorf("invalid JSONCustom JSON tag")
	}
}

func (v *JSONCustom) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one JSONCustom JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Value":
		var payload JSONCustomValue
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.JSONCustom()
		return nil
	default:
		return fmt.Errorf("unknown JSONCustom JSON variant %q", variant)
	}
}

func (v *JSONCustom) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one JSONCustom JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Value":
			current = 1
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return fmt.Errorf("expected one JSONCustom JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown JSONCustom JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload JSONCustomValue
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.JSONCustom()
		return nil
	default:
		return fmt.Errorf("invalid JSONCustom JSON tag")
	}
}

type JSONPlain struct {
	ID     string    `json:"account_id"`
	Reason string    `json:"reason,omitempty"`
	Custom JSONField `json:"custom,omitempty"`
}

// JSONEscaped requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONEscapedTag uint8

const (
	JSONEscapedTagValue JSONEscapedTag = iota + 1
)

type JSONEscaped struct {
	tgoTag   JSONEscapedTag
	tgoValue JSONEscapedValue
}

// Tag returns the active tag.
func (v JSONEscaped) Tag() JSONEscapedTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONEscaped) UnknownTag() string {
	return fmt.Sprintf("JSONEscaped: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONEscapedValue is the Value payload.
type JSONEscapedValue struct {
	ID string `json:"id,omitempty"`
}

// JSONEscaped constructs JSONEscaped. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONEscapedValue) JSONEscaped() JSONEscaped {
	return JSONEscaped{tgoTag: JSONEscapedTagValue, tgoValue: value}
}

// ValuePayload requires Value. No tag check.
func (v JSONEscaped) ValuePayload() JSONEscapedValue { return v.tgoValue }

func (v JSONEscaped) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONEscapedTagValue:
		payload := v.ValuePayload()
		payloadData, err := json.Marshal(payload)
		if err != nil {
			return nil, err
		}
		if len(payloadData) < 2 || payloadData[0] != '{' || payloadData[len(payloadData)-1] != '}' {
			return nil, fmt.Errorf("expected JSONEscaped JSON payload object")
		}
		if len(payloadData) == 2 {
			return []byte("{\"kind\\u0001\":\"name\\u0001\\\"end\"}"), nil
		}
		result := make([]byte, 0, len(payloadData)+31)
		result = append(result, "{\"kind\\u0001\":\"name\\u0001\\\"end\""...)
		result = append(result, ',')
		result = append(result, payloadData[1:]...)
		return result, nil
	default:
		return nil, fmt.Errorf("invalid JSONEscaped JSON tag")
	}
}

func (v JSONEscaped) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONEscapedTagValue:
		payload := v.ValuePayload()
		_, marshalsJSON := interface{}(payload).(interface{ MarshalJSON() ([]byte, error) })
		_, marshalsText := interface{}(payload).(interface{ MarshalText() ([]byte, error) })
		_, marshalsJSONTo := interface{}(payload).(interface{ MarshalJSONTo(*jsontext.Encoder) error })
		if marshalsJSON || marshalsText || marshalsJSONTo {
			data, err := v.MarshalJSON()
			if err != nil {
				return err
			}
			return out.WriteValue(data)
		}
		return jsonv2.MarshalEncode(out, struct {
			Variant string `json:"kind\x01"`
			JSONEscapedValue
		}{Variant: "name\x01\"end", JSONEscapedValue: payload})
	default:
		return fmt.Errorf("invalid JSONEscaped JSON tag")
	}
}

func (v *JSONEscaped) UnmarshalJSON(data []byte) error {
	var variant string
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	tag, ok := object["kind\x01"]
	if !ok {
		return fmt.Errorf("missing JSONEscaped JSON tag")
	}
	if err := json.Unmarshal(tag, &variant); err != nil {
		return err
	}
	switch variant {
	case "name\x01\"end":
		var payload JSONEscapedValue
		if err := json.Unmarshal(data, &payload); err != nil {
			return err
		}
		*v = payload.JSONEscaped()
		return nil
	default:
		return fmt.Errorf("unknown JSONEscaped JSON variant %q", variant)
	}
}

func (v *JSONEscaped) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	data, err := in.ReadValue()
	if err != nil {
		return err
	}
	return v.UnmarshalJSON(data)
}

// JSONEscapedExternal requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONEscapedExternalTag uint8

const (
	JSONEscapedExternalTagValue JSONEscapedExternalTag = iota + 1
)

type JSONEscapedExternal struct {
	tgoTag   JSONEscapedExternalTag
	tgoValue JSONEscapedExternalValue
}

// Tag returns the active tag.
func (v JSONEscapedExternal) Tag() JSONEscapedExternalTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONEscapedExternal) UnknownTag() string {
	return fmt.Sprintf("JSONEscapedExternal: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONEscapedExternalValue is the Value payload.
type JSONEscapedExternalValue struct {
	ID string `json:"id,omitempty"`
}

// JSONEscapedExternal constructs JSONEscapedExternal. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONEscapedExternalValue) JSONEscapedExternal() JSONEscapedExternal {
	return JSONEscapedExternal{tgoTag: JSONEscapedExternalTagValue, tgoValue: value}
}

// ValuePayload requires Value. No tag check.
func (v JSONEscapedExternal) ValuePayload() JSONEscapedExternalValue { return v.tgoValue }

func (v JSONEscapedExternal) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONEscapedExternalTagValue:
		payload := v.ValuePayload()
		payloadData, err := json.Marshal(payload)
		if err != nil {
			return nil, err
		}
		result := make([]byte, 0, len(payloadData)+20)
		result = append(result, "{\"name\\u0001\\\"end\":"...)
		result = append(result, payloadData...)
		result = append(result, '}')
		return result, nil
	default:
		return nil, fmt.Errorf("invalid JSONEscapedExternal JSON tag")
	}
}

func (v JSONEscapedExternal) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONEscapedExternalTagValue:
		payload := v.ValuePayload()
		return tgoJSONExternalExternalJSONTo(out, "name\x01\"end", payload)
	default:
		return fmt.Errorf("invalid JSONEscapedExternal JSON tag")
	}
}

func (v *JSONEscapedExternal) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one JSONEscapedExternal JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "name\x01\"end":
		var payload JSONEscapedExternalValue
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.JSONEscapedExternal()
		return nil
	default:
		return fmt.Errorf("unknown JSONEscapedExternal JSON variant %q", variant)
	}
}

func (v *JSONEscapedExternal) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one JSONEscapedExternal JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "name\x01\"end":
			current = 1
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return fmt.Errorf("expected one JSONEscapedExternal JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown JSONEscapedExternal JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload JSONEscapedExternalValue
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.JSONEscapedExternal()
		return nil
	default:
		return fmt.Errorf("invalid JSONEscapedExternal JSON tag")
	}
}

// JSONEscapedAdjacent requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONEscapedAdjacentTag uint8

const (
	JSONEscapedAdjacentTagValue JSONEscapedAdjacentTag = iota + 1
)

type JSONEscapedAdjacent struct {
	tgoTag   JSONEscapedAdjacentTag
	tgoValue JSONEscapedAdjacentValue
}

// Tag returns the active tag.
func (v JSONEscapedAdjacent) Tag() JSONEscapedAdjacentTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONEscapedAdjacent) UnknownTag() string {
	return fmt.Sprintf("JSONEscapedAdjacent: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONEscapedAdjacentValue is the Value payload.
type JSONEscapedAdjacentValue struct {
	ID string `json:"id,omitempty"`
}

// JSONEscapedAdjacent constructs JSONEscapedAdjacent. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONEscapedAdjacentValue) JSONEscapedAdjacent() JSONEscapedAdjacent {
	return JSONEscapedAdjacent{tgoTag: JSONEscapedAdjacentTagValue, tgoValue: value}
}

// ValuePayload requires Value. No tag check.
func (v JSONEscapedAdjacent) ValuePayload() JSONEscapedAdjacentValue { return v.tgoValue }

func (v JSONEscapedAdjacent) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONEscapedAdjacentTagValue:
		payload := v.ValuePayload()
		payloadData, err := json.Marshal(payload)
		if err != nil {
			return nil, err
		}
		result := make([]byte, 0, len(payloadData)+46)
		result = append(result, "{\"kind\\u0001\":\"name\\u0001\\\"end\",\"data\\u0002\":"...)
		result = append(result, payloadData...)
		result = append(result, '}')
		return result, nil
	default:
		return nil, fmt.Errorf("invalid JSONEscapedAdjacent JSON tag")
	}
}

func (v JSONEscapedAdjacent) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONEscapedAdjacentTagValue:
		payload := v.ValuePayload()
		return tgoJSONExternalAdjacentJSONTo(out, "kind\x01", "name\x01\"end", "data\x02", payload)
	default:
		return fmt.Errorf("invalid JSONEscapedAdjacent JSON tag")
	}
}

func (v *JSONEscapedAdjacent) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	tag, ok := object["kind\x01"]
	if !ok {
		return fmt.Errorf("missing JSONEscapedAdjacent JSON tag")
	}
	if err := json.Unmarshal(tag, &variant); err != nil {
		return err
	}
	var present bool
	payloadData, present = object["data\x02"]
	if !present {
		return fmt.Errorf("missing JSONEscapedAdjacent JSON content")
	}
	switch variant {
	case "name\x01\"end":
		var payload JSONEscapedAdjacentValue
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.JSONEscapedAdjacent()
		return nil
	default:
		return fmt.Errorf("unknown JSONEscapedAdjacent JSON variant %q", variant)
	}
}

func (v *JSONEscapedAdjacent) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("missing JSONEscapedAdjacent JSON tag")
	}
	var contentData jsontext.Value
	selected := 0
	var unknown string
	contentPresent := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		field := 0
		switch wireName {
		case "kind\x01":
			field = 1
		case "data\x02":
			field = 2
		}
		switch field {
		case 1:
			if in.PeekKind() == 'n' {
				if _, err := in.ReadToken(); err != nil {
					return err
				}
				break
			}
			if in.PeekKind() != '"' {
				var invalid string
				return jsonv2.UnmarshalDecode(in, &invalid)
			}
			tagToken, err := in.ReadToken()
			if err != nil {
				return err
			}
			variantName := tagToken.String()
			selected = 0
			unknown = ""
			switch variantName {
			case "name\x01\"end":
				selected = 1
			default:
				unknown = string(append([]byte(nil), variantName...))
			}
		case 2:
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			contentData = append(contentData[:0], raw...)
			contentPresent = true
		default:
			if err := in.SkipValue(); err != nil {
				return err
			}
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if selected == 0 && unknown == "" {
		return fmt.Errorf("missing JSONEscapedAdjacent JSON tag")
	}
	if !contentPresent {
		return fmt.Errorf("missing JSONEscapedAdjacent JSON content")
	}
	if selected == 0 {
		return fmt.Errorf("unknown JSONEscapedAdjacent JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload JSONEscapedAdjacentValue
		if err := jsonv2.Unmarshal(contentData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.JSONEscapedAdjacent()
		return nil
	default:
		return fmt.Errorf("invalid JSONEscapedAdjacent JSON tag")
	}
}

// JSONStringField requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONStringFieldTag uint8

const (
	JSONStringFieldTagValue JSONStringFieldTag = iota + 1
)

type JSONStringField struct {
	tgoTag   JSONStringFieldTag
	tgoValue JSONStringFieldValue
}

// Tag returns the active tag.
func (v JSONStringField) Tag() JSONStringFieldTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONStringField) UnknownTag() string {
	return fmt.Sprintf("JSONStringField: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONStringFieldValue is the Value payload.
type JSONStringFieldValue struct {
	Count int `json:"count,string"`
}

// JSONStringField constructs JSONStringField. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONStringFieldValue) JSONStringField() JSONStringField {
	return JSONStringField{tgoTag: JSONStringFieldTagValue, tgoValue: value}
}

// ValuePayload requires Value. No tag check.
func (v JSONStringField) ValuePayload() JSONStringFieldValue { return v.tgoValue }

func (v JSONStringField) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONStringFieldTagValue:
		payload := v.ValuePayload()
		return json.Marshal(struct {
			Payload JSONStringFieldValue `json:"Value"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid JSONStringField JSON tag")
	}
}

func (v JSONStringField) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONStringFieldTagValue:
		payload := v.ValuePayload()
		return tgoJSONExternalExternalJSONTo(out, "Value", payload)
	default:
		return fmt.Errorf("invalid JSONStringField JSON tag")
	}
}

func (v *JSONStringField) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one JSONStringField JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Value":
		var payload JSONStringFieldValue
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.JSONStringField()
		return nil
	default:
		return fmt.Errorf("unknown JSONStringField JSON variant %q", variant)
	}
}

func (v *JSONStringField) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one JSONStringField JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Value":
			current = 1
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return fmt.Errorf("expected one JSONStringField JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown JSONStringField JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload JSONStringFieldValue
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = payload.JSONStringField()
		return nil
	default:
		return fmt.Errorf("invalid JSONStringField JSON tag")
	}
}

// JSONInternalPayloadMethod requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONInternalPayloadMethodTag uint8

const (
	JSONInternalPayloadMethodTagValue JSONInternalPayloadMethodTag = iota + 1
)

type JSONInternalPayloadMethod struct {
	tgoTag   JSONInternalPayloadMethodTag
	tgoValue JSONInternalPayloadMethodValue
}

// Tag returns the active tag.
func (v JSONInternalPayloadMethod) Tag() JSONInternalPayloadMethodTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONInternalPayloadMethod) UnknownTag() string {
	return fmt.Sprintf("JSONInternalPayloadMethod: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONInternalPayloadMethodValue is the Value payload.
type JSONInternalPayloadMethodValue struct {
	Seen string `json:"-"`
}

// JSONInternalPayloadMethod constructs JSONInternalPayloadMethod. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONInternalPayloadMethodValue) JSONInternalPayloadMethod() JSONInternalPayloadMethod {
	return JSONInternalPayloadMethod{tgoTag: JSONInternalPayloadMethodTagValue, tgoValue: value}
}

// ValuePayload requires Value. No tag check.
func (v JSONInternalPayloadMethod) ValuePayload() JSONInternalPayloadMethodValue { return v.tgoValue }

func (v JSONInternalPayloadMethod) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONInternalPayloadMethodTagValue:
		payload := v.ValuePayload()
		payloadData, err := json.Marshal(payload)
		if err != nil {
			return nil, err
		}
		if len(payloadData) < 2 || payloadData[0] != '{' || payloadData[len(payloadData)-1] != '}' {
			return nil, fmt.Errorf("expected JSONInternalPayloadMethod JSON payload object")
		}
		if len(payloadData) == 2 {
			return []byte("{\"type\":\"value\"}"), nil
		}
		result := make([]byte, 0, len(payloadData)+15)
		result = append(result, "{\"type\":\"value\""...)
		result = append(result, ',')
		result = append(result, payloadData[1:]...)
		return result, nil
	default:
		return nil, fmt.Errorf("invalid JSONInternalPayloadMethod JSON tag")
	}
}

func (v JSONInternalPayloadMethod) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONInternalPayloadMethodTagValue:
		payload := v.ValuePayload()
		_, marshalsJSON := interface{}(payload).(interface{ MarshalJSON() ([]byte, error) })
		_, marshalsText := interface{}(payload).(interface{ MarshalText() ([]byte, error) })
		_, marshalsJSONTo := interface{}(payload).(interface{ MarshalJSONTo(*jsontext.Encoder) error })
		if marshalsJSON || marshalsText || marshalsJSONTo {
			data, err := v.MarshalJSON()
			if err != nil {
				return err
			}
			return out.WriteValue(data)
		}
		return jsonv2.MarshalEncode(out, struct {
			Variant string `json:"type"`
			JSONInternalPayloadMethodValue
		}{Variant: "value", JSONInternalPayloadMethodValue: payload})
	default:
		return fmt.Errorf("invalid JSONInternalPayloadMethod JSON tag")
	}
}

func (v *JSONInternalPayloadMethod) UnmarshalJSON(data []byte) error {
	var variant string
	var object struct {
		Tag string `json:"type"`
	}
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if object.Tag == "" {
		return fmt.Errorf("missing JSONInternalPayloadMethod JSON tag")
	}
	variant = object.Tag
	switch variant {
	case "value":
		var payload JSONInternalPayloadMethodValue
		if err := json.Unmarshal(data, &payload); err != nil {
			return err
		}
		*v = payload.JSONInternalPayloadMethod()
		return nil
	default:
		return fmt.Errorf("unknown JSONInternalPayloadMethod JSON variant %q", variant)
	}
}

func (v *JSONInternalPayloadMethod) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	data, err := in.ReadValue()
	if err != nil {
		return err
	}
	return v.UnmarshalJSON(data)
}

// JSONInternalPromotedMethod requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONInternalPromotedMethodTag uint8

const (
	JSONInternalPromotedMethodTagValue JSONInternalPromotedMethodTag = iota + 1
)

type JSONInternalPromotedMethod struct {
	tgoTag   JSONInternalPromotedMethodTag
	tgoValue JSONInternalPromotedMethodValue
}

// Tag returns the active tag.
func (v JSONInternalPromotedMethod) Tag() JSONInternalPromotedMethodTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONInternalPromotedMethod) UnknownTag() string {
	return fmt.Sprintf("JSONInternalPromotedMethod: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONInternalPromotedMethodValue is the Value payload.
type JSONInternalPromotedMethodValue struct {
	JSONObject
}

// JSONInternalPromotedMethod constructs JSONInternalPromotedMethod. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONInternalPromotedMethodValue) JSONInternalPromotedMethod() JSONInternalPromotedMethod {
	return JSONInternalPromotedMethod{tgoTag: JSONInternalPromotedMethodTagValue, tgoValue: value}
}

// ValuePayload requires Value. No tag check.
func (v JSONInternalPromotedMethod) ValuePayload() JSONInternalPromotedMethodValue { return v.tgoValue }

func (v JSONInternalPromotedMethod) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONInternalPromotedMethodTagValue:
		payload := v.ValuePayload()
		payloadData, err := json.Marshal(payload)
		if err != nil {
			return nil, err
		}
		if len(payloadData) < 2 || payloadData[0] != '{' || payloadData[len(payloadData)-1] != '}' {
			return nil, fmt.Errorf("expected JSONInternalPromotedMethod JSON payload object")
		}
		if len(payloadData) == 2 {
			return []byte("{\"type\":\"value\"}"), nil
		}
		result := make([]byte, 0, len(payloadData)+15)
		result = append(result, "{\"type\":\"value\""...)
		result = append(result, ',')
		result = append(result, payloadData[1:]...)
		return result, nil
	default:
		return nil, fmt.Errorf("invalid JSONInternalPromotedMethod JSON tag")
	}
}

func (v JSONInternalPromotedMethod) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONInternalPromotedMethodTagValue:
		payload := v.ValuePayload()
		_, marshalsJSON := interface{}(payload).(interface{ MarshalJSON() ([]byte, error) })
		_, marshalsText := interface{}(payload).(interface{ MarshalText() ([]byte, error) })
		_, marshalsJSONTo := interface{}(payload).(interface{ MarshalJSONTo(*jsontext.Encoder) error })
		if marshalsJSON || marshalsText || marshalsJSONTo {
			data, err := v.MarshalJSON()
			if err != nil {
				return err
			}
			return out.WriteValue(data)
		}
		return jsonv2.MarshalEncode(out, struct {
			Variant string `json:"type"`
			JSONInternalPromotedMethodValue
		}{Variant: "value", JSONInternalPromotedMethodValue: payload})
	default:
		return fmt.Errorf("invalid JSONInternalPromotedMethod JSON tag")
	}
}

func (v *JSONInternalPromotedMethod) UnmarshalJSON(data []byte) error {
	var variant string
	var object struct {
		Tag string `json:"type"`
	}
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if object.Tag == "" {
		return fmt.Errorf("missing JSONInternalPromotedMethod JSON tag")
	}
	variant = object.Tag
	switch variant {
	case "value":
		var payload JSONInternalPromotedMethodValue
		if err := json.Unmarshal(data, &payload); err != nil {
			return err
		}
		*v = payload.JSONInternalPromotedMethod()
		return nil
	default:
		return fmt.Errorf("unknown JSONInternalPromotedMethod JSON variant %q", variant)
	}
}

func (v *JSONInternalPromotedMethod) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	data, err := in.ReadValue()
	if err != nil {
		return err
	}
	return v.UnmarshalJSON(data)
}

type JSONNonNilTarget struct {
	Name string `json:"name,omitempty"`
}

type JSONNonNilAlias = *JSONNonNilTarget

type JSONNonNilCustom struct {
	Value *JSONNonNilTarget
}

// JSONNonNilExternal requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONNonNilExternalTag uint8

const (
	JSONNonNilExternalTagValue JSONNonNilExternalTag = iota + 1
)

type JSONNonNilExternal struct {
	tgoTag   JSONNonNilExternalTag
	tgoValue JSONNonNilExternalValue
}

// Tag returns the active tag.
func (v JSONNonNilExternal) Tag() JSONNonNilExternalTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONNonNilExternal) UnknownTag() string {
	return fmt.Sprintf("JSONNonNilExternal: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONNonNilExternalValue is the Value payload.
type JSONNonNilExternalValue struct {
	Direct *JSONNonNilTarget
	Alias  JSONNonNilAlias
	Nested struct {
		Array    [1]*JSONNonNilTarget
		Slice    []*JSONNonNilTarget
		Map      map[string]*JSONNonNilTarget
		Optional *struct{ Value *JSONNonNilTarget }
	}
	Custom JSONNonNilCustom
}

// JSONNonNilExternal constructs JSONNonNilExternal. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONNonNilExternalValue) JSONNonNilExternal() JSONNonNilExternal {
	return JSONNonNilExternal{tgoTag: JSONNonNilExternalTagValue, tgoValue: value}
}

// ValuePayload requires Value. No tag check.
func (v JSONNonNilExternal) ValuePayload() JSONNonNilExternalValue { return v.tgoValue }

func (v JSONNonNilExternal) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONNonNilExternalTagValue:
		payload := v.ValuePayload()
		return json.Marshal(struct {
			Payload JSONNonNilExternalValue `json:"Value"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid JSONNonNilExternal JSON tag")
	}
}

func (v JSONNonNilExternal) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONNonNilExternalTagValue:
		payload := v.ValuePayload()
		return tgoJSONExternalExternalJSONTo(out, "Value", payload)
	default:
		return fmt.Errorf("invalid JSONNonNilExternal JSON tag")
	}
}

func (v *JSONNonNilExternal) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one JSONNonNilExternal JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Value":
		var payload JSONNonNilExternalValue
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		if payload.Direct == nil {
			return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Direct must not be nil")
		}
		if payload.Alias == nil {
			return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Alias must not be nil")
		}
		for _, tgoJSONValue0 := range payload.Nested.Array {
			if tgoJSONValue0 == nil {
				return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Nested.Array[] must not be nil")
			}
		}
		for _, tgoJSONValue1 := range payload.Nested.Slice {
			if tgoJSONValue1 == nil {
				return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Nested.Slice[] must not be nil")
			}
		}
		for _, tgoJSONValue2 := range payload.Nested.Map {
			if tgoJSONValue2 == nil {
				return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Nested.Map[] must not be nil")
			}
		}
		if payload.Nested.Optional != nil {
			if (*payload.Nested.Optional).Value == nil {
				return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Nested.Optional.Value must not be nil")
			}
		}
		if payload.Custom.Value == nil {
			return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Custom.Value must not be nil")
		}

		*v = payload.JSONNonNilExternal()
		return nil
	default:
		return fmt.Errorf("unknown JSONNonNilExternal JSON variant %q", variant)
	}
}

func (v *JSONNonNilExternal) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one JSONNonNilExternal JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Value":
			current = 1
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return fmt.Errorf("expected one JSONNonNilExternal JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown JSONNonNilExternal JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload JSONNonNilExternalValue
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		if payload.Direct == nil {
			return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Direct must not be nil")
		}
		if payload.Alias == nil {
			return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Alias must not be nil")
		}
		for _, tgoJSONValue0 := range payload.Nested.Array {
			if tgoJSONValue0 == nil {
				return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Nested.Array[] must not be nil")
			}
		}
		for _, tgoJSONValue1 := range payload.Nested.Slice {
			if tgoJSONValue1 == nil {
				return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Nested.Slice[] must not be nil")
			}
		}
		for _, tgoJSONValue2 := range payload.Nested.Map {
			if tgoJSONValue2 == nil {
				return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Nested.Map[] must not be nil")
			}
		}
		if payload.Nested.Optional != nil {
			if (*payload.Nested.Optional).Value == nil {
				return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Nested.Optional.Value must not be nil")
			}
		}
		if payload.Custom.Value == nil {
			return fmt.Errorf("invalid JSONNonNilExternal.Value JSON payload: Custom.Value must not be nil")
		}

		*v = payload.JSONNonNilExternal()
		return nil
	default:
		return fmt.Errorf("invalid JSONNonNilExternal JSON tag")
	}
}

// JSONNonNilInternal requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONNonNilInternalTag uint8

const (
	JSONNonNilInternalTagValue JSONNonNilInternalTag = iota + 1
)

type JSONNonNilInternal struct {
	tgoTag   JSONNonNilInternalTag
	tgoValue JSONNonNilInternalValue
}

// Tag returns the active tag.
func (v JSONNonNilInternal) Tag() JSONNonNilInternalTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONNonNilInternal) UnknownTag() string {
	return fmt.Sprintf("JSONNonNilInternal: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONNonNilInternalValue is the Value payload.
type JSONNonNilInternalValue struct {
	Required *JSONNonNilTarget
}

// JSONNonNilInternal constructs JSONNonNilInternal. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONNonNilInternalValue) JSONNonNilInternal() JSONNonNilInternal {
	return JSONNonNilInternal{tgoTag: JSONNonNilInternalTagValue, tgoValue: value}
}

// ValuePayload requires Value. No tag check.
func (v JSONNonNilInternal) ValuePayload() JSONNonNilInternalValue { return v.tgoValue }

func (v JSONNonNilInternal) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONNonNilInternalTagValue:
		payload := v.ValuePayload()
		payloadData, err := json.Marshal(payload)
		if err != nil {
			return nil, err
		}
		if len(payloadData) < 2 || payloadData[0] != '{' || payloadData[len(payloadData)-1] != '}' {
			return nil, fmt.Errorf("expected JSONNonNilInternal JSON payload object")
		}
		if len(payloadData) == 2 {
			return []byte("{\"type\":\"value\"}"), nil
		}
		result := make([]byte, 0, len(payloadData)+15)
		result = append(result, "{\"type\":\"value\""...)
		result = append(result, ',')
		result = append(result, payloadData[1:]...)
		return result, nil
	default:
		return nil, fmt.Errorf("invalid JSONNonNilInternal JSON tag")
	}
}

func (v JSONNonNilInternal) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONNonNilInternalTagValue:
		payload := v.ValuePayload()
		_, marshalsJSON := interface{}(payload).(interface{ MarshalJSON() ([]byte, error) })
		_, marshalsText := interface{}(payload).(interface{ MarshalText() ([]byte, error) })
		_, marshalsJSONTo := interface{}(payload).(interface{ MarshalJSONTo(*jsontext.Encoder) error })
		if marshalsJSON || marshalsText || marshalsJSONTo {
			data, err := v.MarshalJSON()
			if err != nil {
				return err
			}
			return out.WriteValue(data)
		}
		return jsonv2.MarshalEncode(out, struct {
			Variant string `json:"type"`
			JSONNonNilInternalValue
		}{Variant: "value", JSONNonNilInternalValue: payload})
	default:
		return fmt.Errorf("invalid JSONNonNilInternal JSON tag")
	}
}

func (v *JSONNonNilInternal) UnmarshalJSON(data []byte) error {
	var variant string
	var object struct {
		Tag string `json:"type"`
	}
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if object.Tag == "" {
		return fmt.Errorf("missing JSONNonNilInternal JSON tag")
	}
	variant = object.Tag
	switch variant {
	case "value":
		var payload JSONNonNilInternalValue
		if err := json.Unmarshal(data, &payload); err != nil {
			return err
		}
		if payload.Required == nil {
			return fmt.Errorf("invalid JSONNonNilInternal.Value JSON payload: Required must not be nil")
		}

		*v = payload.JSONNonNilInternal()
		return nil
	default:
		return fmt.Errorf("unknown JSONNonNilInternal JSON variant %q", variant)
	}
}

func (v *JSONNonNilInternal) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	data, err := in.ReadValue()
	if err != nil {
		return err
	}
	return v.UnmarshalJSON(data)
}

// JSONNonNilAdjacent requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONNonNilAdjacentTag uint8

const (
	JSONNonNilAdjacentTagValue JSONNonNilAdjacentTag = iota + 1
)

type JSONNonNilAdjacent struct {
	tgoTag   JSONNonNilAdjacentTag
	tgoValue JSONNonNilAdjacentValue
}

// Tag returns the active tag.
func (v JSONNonNilAdjacent) Tag() JSONNonNilAdjacentTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONNonNilAdjacent) UnknownTag() string {
	return fmt.Sprintf("JSONNonNilAdjacent: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONNonNilAdjacentValue is the Value payload.
type JSONNonNilAdjacentValue struct {
	Required *JSONNonNilTarget
}

// JSONNonNilAdjacent constructs JSONNonNilAdjacent. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONNonNilAdjacentValue) JSONNonNilAdjacent() JSONNonNilAdjacent {
	return JSONNonNilAdjacent{tgoTag: JSONNonNilAdjacentTagValue, tgoValue: value}
}

// ValuePayload requires Value. No tag check.
func (v JSONNonNilAdjacent) ValuePayload() JSONNonNilAdjacentValue { return v.tgoValue }

func (v JSONNonNilAdjacent) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONNonNilAdjacentTagValue:
		payload := v.ValuePayload()
		return json.Marshal(struct {
			Variant string                  `json:"type"`
			Payload JSONNonNilAdjacentValue `json:"data"`
		}{Variant: "value", Payload: payload})
	default:
		return nil, fmt.Errorf("invalid JSONNonNilAdjacent JSON tag")
	}
}

func (v JSONNonNilAdjacent) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONNonNilAdjacentTagValue:
		payload := v.ValuePayload()
		return tgoJSONExternalAdjacentJSONTo(out, "type", "value", "data", payload)
	default:
		return fmt.Errorf("invalid JSONNonNilAdjacent JSON tag")
	}
}

func (v *JSONNonNilAdjacent) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object struct {
		Tag     string          `json:"type"`
		Content json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if object.Tag == "" {
		return fmt.Errorf("missing JSONNonNilAdjacent JSON tag")
	}
	variant = object.Tag
	payloadData = object.Content
	if payloadData == nil {
		return fmt.Errorf("missing JSONNonNilAdjacent JSON content")
	}
	switch variant {
	case "value":
		var payload JSONNonNilAdjacentValue
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		if payload.Required == nil {
			return fmt.Errorf("invalid JSONNonNilAdjacent.Value JSON payload: Required must not be nil")
		}

		*v = payload.JSONNonNilAdjacent()
		return nil
	default:
		return fmt.Errorf("unknown JSONNonNilAdjacent JSON variant %q", variant)
	}
}

func (v *JSONNonNilAdjacent) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("missing JSONNonNilAdjacent JSON tag")
	}
	var contentData jsontext.Value
	selected := 0
	var unknown string
	contentPresent := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		field := 0
		switch {
		case wireName == "type":
			field = 1
		case wireName == "data":
			field = 2
		case strings.EqualFold(wireName, "type"):
			field = 1
		case strings.EqualFold(wireName, "data"):
			field = 2
		}
		switch field {
		case 1:
			if in.PeekKind() == 'n' {
				if _, err := in.ReadToken(); err != nil {
					return err
				}
				break
			}
			if in.PeekKind() != '"' {
				var invalid string
				return jsonv2.UnmarshalDecode(in, &invalid)
			}
			tagToken, err := in.ReadToken()
			if err != nil {
				return err
			}
			variantName := tagToken.String()
			selected = 0
			unknown = ""
			switch variantName {
			case "value":
				selected = 1
			default:
				unknown = string(append([]byte(nil), variantName...))
			}
		case 2:
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			contentData = append(contentData[:0], raw...)
			contentPresent = true
		default:
			if err := in.SkipValue(); err != nil {
				return err
			}
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if selected == 0 && unknown == "" {
		return fmt.Errorf("missing JSONNonNilAdjacent JSON tag")
	}
	if !contentPresent {
		return fmt.Errorf("missing JSONNonNilAdjacent JSON content")
	}
	if selected == 0 {
		return fmt.Errorf("unknown JSONNonNilAdjacent JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload JSONNonNilAdjacentValue
		if err := jsonv2.Unmarshal(contentData, &payload, in.Options()); err != nil {
			return err
		}
		if payload.Required == nil {
			return fmt.Errorf("invalid JSONNonNilAdjacent.Value JSON payload: Required must not be nil")
		}

		*v = payload.JSONNonNilAdjacent()
		return nil
	default:
		return fmt.Errorf("invalid JSONNonNilAdjacent JSON tag")
	}
}

// JSONNonNilUntagged requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONNonNilUntaggedTag uint8

const (
	JSONNonNilUntaggedTagFirst JSONNonNilUntaggedTag = iota + 1
	JSONNonNilUntaggedTagSecond
)

type JSONNonNilUntagged struct {
	tgoTag    JSONNonNilUntaggedTag
	tgoFirst  JSONNonNilUntaggedFirst
	tgoSecond JSONNonNilUntaggedSecond
}

// Tag returns the active tag.
func (v JSONNonNilUntagged) Tag() JSONNonNilUntaggedTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONNonNilUntagged) UnknownTag() string {
	return fmt.Sprintf("JSONNonNilUntagged: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONNonNilUntaggedFirst is the First payload.
type JSONNonNilUntaggedFirst struct {
	Required *JSONNonNilTarget
}

// JSONNonNilUntagged constructs JSONNonNilUntagged. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONNonNilUntaggedFirst) JSONNonNilUntagged() JSONNonNilUntagged {
	return JSONNonNilUntagged{tgoTag: JSONNonNilUntaggedTagFirst, tgoFirst: value}
}

// FirstPayload requires First. No tag check.
func (v JSONNonNilUntagged) FirstPayload() JSONNonNilUntaggedFirst { return v.tgoFirst }

// JSONNonNilUntaggedSecond is the Second payload.
type JSONNonNilUntaggedSecond struct {
	Count int
}

// JSONNonNilUntagged constructs JSONNonNilUntagged. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONNonNilUntaggedSecond) JSONNonNilUntagged() JSONNonNilUntagged {
	return JSONNonNilUntagged{tgoTag: JSONNonNilUntaggedTagSecond, tgoSecond: value}
}

// SecondPayload requires Second. No tag check.
func (v JSONNonNilUntagged) SecondPayload() JSONNonNilUntaggedSecond { return v.tgoSecond }

func (v JSONNonNilUntagged) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONNonNilUntaggedTagFirst:
		payload := v.FirstPayload()
		return json.Marshal(payload)
	case JSONNonNilUntaggedTagSecond:
		payload := v.SecondPayload()
		return json.Marshal(payload)
	default:
		return nil, fmt.Errorf("invalid JSONNonNilUntagged JSON tag")
	}
}

func (v JSONNonNilUntagged) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONNonNilUntaggedTagFirst:
		payload := v.FirstPayload()
		return jsonv2.MarshalEncode(out, payload)
	case JSONNonNilUntaggedTagSecond:
		payload := v.SecondPayload()
		return jsonv2.MarshalEncode(out, payload)
	default:
		return fmt.Errorf("invalid JSONNonNilUntagged JSON tag")
	}
}

func (v *JSONNonNilUntagged) UnmarshalJSON(data []byte) error {
	var tgoJSONNonNilError error
	{
		var payload JSONNonNilUntaggedFirst
		if err := json.Unmarshal(data, &payload); err == nil {
			if tgoJSONError := func() error {
				if payload.Required == nil {
					return fmt.Errorf("invalid JSONNonNilUntagged.First JSON payload: Required must not be nil")
				}
				return nil
			}(); tgoJSONError == nil {

				*v = payload.JSONNonNilUntagged()
				return nil
			} else if tgoJSONNonNilError == nil {
				tgoJSONNonNilError = tgoJSONError
			}
		}
	}
	{
		var payload JSONNonNilUntaggedSecond
		if err := json.Unmarshal(data, &payload); err == nil {
			*v = payload.JSONNonNilUntagged()
			return nil
		}
	}
	if tgoJSONNonNilError != nil {
		return tgoJSONNonNilError
	}
	return fmt.Errorf("no matching JSONNonNilUntagged JSON variant")
}

func (v *JSONNonNilUntagged) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	data, err := in.ReadValue()
	if err != nil {
		return err
	}
	return v.UnmarshalJSON(data)
}

type JSONNonNilRecursive struct {
	Next     *JSONNonNilRecursive
	Required *JSONNonNilTarget
}

type JSONNonNilRequired struct {
	Item *JSONNonNilTarget
}

type JSONNonNilBox[T any] struct{ Value T }

// JSONNonNilAdvanced requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type JSONNonNilAdvancedTag uint8

const (
	JSONNonNilAdvancedTagValue JSONNonNilAdvancedTag = iota + 1
)

type JSONNonNilAdvanced struct {
	tgoTag   JSONNonNilAdvancedTag
	tgoValue JSONNonNilAdvancedValue
}

// Tag returns the active tag.
func (v JSONNonNilAdvanced) Tag() JSONNonNilAdvancedTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v JSONNonNilAdvanced) UnknownTag() string {
	return fmt.Sprintf("JSONNonNilAdvanced: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// JSONNonNilAdvancedValue is the Value payload.
type JSONNonNilAdvancedValue struct {
	Recursive JSONNonNilRecursive
	Generic   JSONNonNilBox[JSONNonNilRequired]
}

// JSONNonNilAdvanced constructs JSONNonNilAdvanced. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value JSONNonNilAdvancedValue) JSONNonNilAdvanced() JSONNonNilAdvanced {
	return JSONNonNilAdvanced{tgoTag: JSONNonNilAdvancedTagValue, tgoValue: value}
}

// ValuePayload requires Value. No tag check.
func (v JSONNonNilAdvanced) ValuePayload() JSONNonNilAdvancedValue { return v.tgoValue }

func (v JSONNonNilAdvanced) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case JSONNonNilAdvancedTagValue:
		payload := v.ValuePayload()
		return json.Marshal(struct {
			Payload JSONNonNilAdvancedValue `json:"Value"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid JSONNonNilAdvanced JSON tag")
	}
}

func (v JSONNonNilAdvanced) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case JSONNonNilAdvancedTagValue:
		payload := v.ValuePayload()
		return tgoJSONExternalExternalJSONTo(out, "Value", payload)
	default:
		return fmt.Errorf("invalid JSONNonNilAdvanced JSON tag")
	}
}

func (v *JSONNonNilAdvanced) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one JSONNonNilAdvanced JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Value":
		var payload JSONNonNilAdvancedValue
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		tgoJSONVisited := make(map[uintptr]bool)
		var (
			tgoJSONValidate0 func(reflect.Value, string) error
		)
		tgoJSONValidate0 = func(tgoJSONValue reflect.Value, tgoJSONPath string) error {
			if tgoJSONValue.CanAddr() {
				tgoJSONPointer := tgoJSONValue.Addr().Pointer()
				if tgoJSONVisited[tgoJSONPointer] {
					return nil
				}
				tgoJSONVisited[tgoJSONPointer] = true
			}
			if !tgoJSONValue.Field(0).IsNil() {
				if err := tgoJSONValidate0(tgoJSONValue.Field(0).Elem(), tgoJSONPath+".Next"); err != nil {
					return err
				}
			}
			if tgoJSONValue.Field(1).IsNil() {
				return fmt.Errorf("invalid JSONNonNilAdvanced.Value JSON payload: %s must not be nil", tgoJSONPath+".Required")
			}
			return nil
		}
		if payload.Recursive.Next != nil {
			if err := tgoJSONValidate0(reflect.ValueOf(&(*payload.Recursive.Next)).Elem(), "Recursive.Next"); err != nil {
				return err
			}
		}
		if payload.Recursive.Required == nil {
			return fmt.Errorf("invalid JSONNonNilAdvanced.Value JSON payload: Recursive.Required must not be nil")
		}
		if payload.Generic.Value.Item == nil {
			return fmt.Errorf("invalid JSONNonNilAdvanced.Value JSON payload: Generic.Value.Item must not be nil")
		}

		*v = payload.JSONNonNilAdvanced()
		return nil
	default:
		return fmt.Errorf("unknown JSONNonNilAdvanced JSON variant %q", variant)
	}
}

func (v *JSONNonNilAdvanced) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one JSONNonNilAdvanced JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Value":
			current = 1
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return fmt.Errorf("expected one JSONNonNilAdvanced JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown JSONNonNilAdvanced JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload JSONNonNilAdvancedValue
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		tgoJSONVisited := make(map[uintptr]bool)
		var (
			tgoJSONValidate0 func(reflect.Value, string) error
		)
		tgoJSONValidate0 = func(tgoJSONValue reflect.Value, tgoJSONPath string) error {
			if tgoJSONValue.CanAddr() {
				tgoJSONPointer := tgoJSONValue.Addr().Pointer()
				if tgoJSONVisited[tgoJSONPointer] {
					return nil
				}
				tgoJSONVisited[tgoJSONPointer] = true
			}
			if !tgoJSONValue.Field(0).IsNil() {
				if err := tgoJSONValidate0(tgoJSONValue.Field(0).Elem(), tgoJSONPath+".Next"); err != nil {
					return err
				}
			}
			if tgoJSONValue.Field(1).IsNil() {
				return fmt.Errorf("invalid JSONNonNilAdvanced.Value JSON payload: %s must not be nil", tgoJSONPath+".Required")
			}
			return nil
		}
		if payload.Recursive.Next != nil {
			if err := tgoJSONValidate0(reflect.ValueOf(&(*payload.Recursive.Next)).Elem(), "Recursive.Next"); err != nil {
				return err
			}
		}
		if payload.Recursive.Required == nil {
			return fmt.Errorf("invalid JSONNonNilAdvanced.Value JSON payload: Recursive.Required must not be nil")
		}
		if payload.Generic.Value.Item == nil {
			return fmt.Errorf("invalid JSONNonNilAdvanced.Value JSON payload: Generic.Value.Item must not be nil")
		}

		*v = payload.JSONNonNilAdvanced()
		return nil
	default:
		return fmt.Errorf("invalid JSONNonNilAdvanced JSON tag")
	}
}
