// Code generated by tgo. DO NOT EDIT.
//tgo:v2 "layout.tgo"

package model

import __tgo_json "encoding/json"
import __tgo_fmt "fmt"

// Large requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type LargeTag uint8

const (
	LargeTagFirst LargeTag = iota + 1
	LargeTagSecond
	LargeTagEmpty
)

type Large struct {
	tgoTag     LargeTag
	tgoPayload interface{}
}

// Tag returns the active tag.
func (v Large) Tag() LargeTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v Large) UnknownTag() string {
	return __tgo_fmt.Sprintf("Large: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// LargeFirst holds the variant fields. Supply every field.
type LargeFirst struct {
	Data [64]byte
}

// Large constructs Large. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value LargeFirst) Large() Large {
	return Large{tgoTag: LargeTagFirst, tgoPayload: value}
}

// FirstPayload requires First. No tag check.
func (v Large) FirstPayload() LargeFirst {
	return v.tgoPayload.(LargeFirst)
}

// LargeSecond holds the variant fields. Supply every field.
type LargeSecond struct {
	Data [64]byte
}

// Large constructs Large. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value LargeSecond) Large() Large {
	return Large{tgoTag: LargeTagSecond, tgoPayload: value}
}

// SecondPayload requires Second. No tag check.
func (v Large) SecondPayload() LargeSecond {
	return v.tgoPayload.(LargeSecond)
}

// LargeEmpty holds the variant fields. Supply every field.
type LargeEmpty struct {
}

// Large constructs Large. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value LargeEmpty) Large() Large {
	return Large{tgoTag: LargeTagEmpty}
}

// EmptyPayload requires Empty. No tag check.
func (v Large) EmptyPayload() LargeEmpty {
	return LargeEmpty{}
}
func (v Large) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case LargeTagFirst:
		payload := v.FirstPayload()
		return __tgo_json.Marshal(struct {
			Payload LargeFirst `json:"First"`
		}{Payload: payload})
	case LargeTagSecond:
		payload := v.SecondPayload()
		return __tgo_json.Marshal(struct {
			Payload LargeSecond `json:"Second"`
		}{Payload: payload})
	case LargeTagEmpty:
		payload := v.EmptyPayload()
		return __tgo_json.Marshal(struct {
			Payload LargeEmpty `json:"Empty"`
		}{Payload: payload})
	default:
		return nil, __tgo_fmt.Errorf("invalid Large JSON tag")
	}
}
func (v *Large) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]__tgo_json.RawMessage
	if err := __tgo_json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return __tgo_fmt.Errorf("expected one Large JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "First":
		var payload LargeFirst
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.Large()
		return nil
	case "Second":
		var payload LargeSecond
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.Large()
		return nil
	case "Empty":
		var payload LargeEmpty
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.Large()
		return nil
	default:
		return __tgo_fmt.Errorf("unknown Large JSON variant %q", variant)
	}
}

// Equal requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type EqualTag uint8

const (
	EqualTagFirst EqualTag = iota + 1
	EqualTagSecond
)

type Equal struct {
	tgoTag     EqualTag
	tgoSecond  EqualSecond
	tgoPayload interface{}
}

// Tag returns the active tag.
func (v Equal) Tag() EqualTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v Equal) UnknownTag() string {
	return __tgo_fmt.Sprintf("Equal: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// EqualFirst holds the variant fields. Supply every field.
type EqualFirst struct {
	Data [40]byte
}

// Equal constructs Equal. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value EqualFirst) Equal() Equal {
	return Equal{tgoTag: EqualTagFirst, tgoPayload: value}
}

// FirstPayload requires First. No tag check.
func (v Equal) FirstPayload() EqualFirst {
	return v.tgoPayload.(EqualFirst)
}

// EqualSecond holds the variant fields. Supply every field.
type EqualSecond struct {
	Data [40]byte
}

// Equal constructs Equal. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value EqualSecond) Equal() Equal {
	return Equal{tgoTag: EqualTagSecond, tgoSecond: value}
}

// SecondPayload requires Second. No tag check.
func (v Equal) SecondPayload() EqualSecond {
	return v.tgoSecond
}
func (v Equal) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case EqualTagFirst:
		payload := v.FirstPayload()
		return __tgo_json.Marshal(struct {
			Payload EqualFirst `json:"First"`
		}{Payload: payload})
	case EqualTagSecond:
		payload := v.SecondPayload()
		return __tgo_json.Marshal(struct {
			Payload EqualSecond `json:"Second"`
		}{Payload: payload})
	default:
		return nil, __tgo_fmt.Errorf("invalid Equal JSON tag")
	}
}
func (v *Equal) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]__tgo_json.RawMessage
	if err := __tgo_json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return __tgo_fmt.Errorf("expected one Equal JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "First":
		var payload EqualFirst
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.Equal()
		return nil
	case "Second":
		var payload EqualSecond
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.Equal()
		return nil
	default:
		return __tgo_fmt.Errorf("unknown Equal JSON variant %q", variant)
	}
}

// NamedZero requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type NamedZeroTag uint8

const (
	NamedZeroTagZero NamedZeroTag = iota + 1
	NamedZeroTagOther
)

type NamedZero struct {
	tgoTag NamedZeroTag
}

// Tag returns the active tag.
func (v NamedZero) Tag() NamedZeroTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v NamedZero) UnknownTag() string {
	return __tgo_fmt.Sprintf("NamedZero: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// NamedZeroZero holds the variant fields. Supply every field.
type NamedZeroZero struct {
}

// NamedZero constructs NamedZero. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value NamedZeroZero) NamedZero() NamedZero {
	return NamedZero{tgoTag: NamedZeroTagZero}
}

// ZeroPayload requires Zero. No tag check.
func (v NamedZero) ZeroPayload() NamedZeroZero {
	return NamedZeroZero{}
}

// NamedZeroOther holds the variant fields. Supply every field.
type NamedZeroOther struct {
}

// NamedZero constructs NamedZero. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func (value NamedZeroOther) NamedZero() NamedZero {
	return NamedZero{tgoTag: NamedZeroTagOther}
}

// OtherPayload requires Other. No tag check.
func (v NamedZero) OtherPayload() NamedZeroOther {
	return NamedZeroOther{}
}
func (v NamedZero) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case NamedZeroTagZero:
		payload := v.ZeroPayload()
		return __tgo_json.Marshal(struct {
			Payload NamedZeroZero `json:"Zero"`
		}{Payload: payload})
	case NamedZeroTagOther:
		payload := v.OtherPayload()
		return __tgo_json.Marshal(struct {
			Payload NamedZeroOther `json:"Other"`
		}{Payload: payload})
	default:
		return nil, __tgo_fmt.Errorf("invalid NamedZero JSON tag")
	}
}
func (v *NamedZero) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]__tgo_json.RawMessage
	if err := __tgo_json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return __tgo_fmt.Errorf("expected one NamedZero JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Zero":
		var payload NamedZeroZero
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.NamedZero()
		return nil
	case "Other":
		var payload NamedZeroOther
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = payload.NamedZero()
		return nil
	default:
		return __tgo_fmt.Errorf("unknown NamedZero JSON variant %q", variant)
	}
}
