// Code generated by tgo. DO NOT EDIT.

package lib

import "encoding/json"
import jsonv2 "encoding/json/v2"
import "encoding/json/jsontext"
import "fmt"

const Limit = 10

var DefaultName = "default"

type Record struct {
	Name string
}

type Printer interface {
	Print() string
}

func (value Record) Text() string {
	return value.Name
}

func Target(value Record) string {
	return value.Text()
}

func tgoAccountExternalJSONTo[T interface{}](out *jsontext.Encoder, name string, payload T) error {
	if err := out.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := out.WriteToken(jsontext.String(name)); err != nil {
		return err
	}
	if err := jsonv2.MarshalEncode(out, payload); err != nil {
		return err
	}
	return out.WriteToken(jsontext.EndObject)
}

// Account requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type AccountTag uint8

const (
	AccountTagPersonal AccountTag = iota + 1
	AccountTagBusiness
)

type Account struct {
	tgoTag      AccountTag
	tgoPersonal AccountPersonal
	tgoBusiness AccountBusiness
}

// Tag returns the active tag.
func (v Account) Tag() AccountTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v Account) UnknownTag() string {
	return fmt.Sprintf("Account: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// AccountPersonal is the Personal payload.
type AccountPersonal struct {
	Name string
}
type TgoAccountPersonalInput struct {
	FieldName string
}

// NewAccountPersonal constructs Account. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewAccountPersonal(Name string) Account {
	tgoValue := AccountPersonal{Name}
	return Account{tgoTag: AccountTagPersonal, tgoPersonal: tgoValue}
}

// PersonalPayload requires Personal. No tag check.
func (v Account) PersonalPayload() AccountPersonal { return v.tgoPersonal }

// AccountBusiness is the Business payload.
type AccountBusiness struct {
	Company string
}
type TgoAccountBusinessInput struct {
	FieldCompany string
}

// NewAccountBusiness constructs Account. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewAccountBusiness(Company string) Account {
	tgoValue := AccountBusiness{Company}
	return Account{tgoTag: AccountTagBusiness, tgoBusiness: tgoValue}
}

// BusinessPayload requires Business. No tag check.
func (v Account) BusinessPayload() AccountBusiness { return v.tgoBusiness }

func (v Account) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case AccountTagPersonal:
		payload := v.PersonalPayload()
		return json.Marshal(struct {
			Payload AccountPersonal `json:"Personal"`
		}{Payload: payload})
	case AccountTagBusiness:
		payload := v.BusinessPayload()
		return json.Marshal(struct {
			Payload AccountBusiness `json:"Business"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid Account JSON tag")
	}
}

func (v Account) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case AccountTagPersonal:
		payload := v.PersonalPayload()
		return tgoAccountExternalJSONTo(out, "Personal", payload)
	case AccountTagBusiness:
		payload := v.BusinessPayload()
		return tgoAccountExternalJSONTo(out, "Business", payload)
	default:
		return fmt.Errorf("invalid Account JSON tag")
	}
}

func (v *Account) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one Account JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Personal":
		var payload AccountPersonal
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = NewAccountPersonal(payload.Name)
		return nil
	case "Business":
		var payload AccountBusiness
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = NewAccountBusiness(payload.Company)
		return nil
	default:
		return fmt.Errorf("unknown Account JSON variant %q", variant)
	}
}

func (v *Account) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one Account JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Personal":
			current = 1
		case "Business":
			current = 2
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return fmt.Errorf("expected one Account JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown Account JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload AccountPersonal
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = NewAccountPersonal(payload.Name)
		return nil
	case 2:
		var payload AccountBusiness
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = NewAccountBusiness(payload.Company)
		return nil
	default:
		return fmt.Errorf("invalid Account JSON tag")
	}
}

func AccountName(value Account) string {
	switch value.Tag() {
	case AccountTagPersonal:
		return value.PersonalPayload().Name
	case AccountTagBusiness:
		return value.BusinessPayload().Company
	default:
		panic(value.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func PersonalName(value Account) string {
	switch value.Tag() {
	case AccountTagPersonal:
		return value.PersonalPayload().Name
	case AccountTagBusiness:
		return ""
	default:
		panic(value.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func MakeAccount() Account {
	return func(input TgoAccountPersonalInput) Account {
		return NewAccountPersonal(input.FieldName)
	}(TgoAccountPersonalInput{FieldName: "person"})
}

type UserID struct {
	value int
}
type TgoUserIDInput struct {
	FieldValue int
}

// NewUserID constructs and checks UserID.
func NewUserID(value int) (UserID, error) {
	return UserID{value}.check()
}

type userIDError struct {
}

func (userIDError) Error() string { return "invalid UserID" }

func (value UserID) check() (UserID, error) {
	if value.value < 1 {
		return UserID{}, userIDError{}
	}
	return value, nil
}

func (value UserID) Value() int { return value.value }

func ReadID(value UserID) int {
	return value.Value()
}

func MakeID() (UserID, error) {
	return func(tgoInput TgoUserIDInput) (UserID, error) {
		return NewUserID(tgoInput.FieldValue)
	}(TgoUserIDInput{FieldValue: 1})
}
