// Code generated by tgo. DO NOT EDIT.

// Package navigation indexes typed TGo source for read-only code navigation.
package navigation

import (
	"context"
	"fmt"
	"go/token"
	"go/types"
	"net/url"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"

	"tgo/internal/driver"
	"tgo/pkg/syntax"
)

// Location is one exact byte range in a source file URI.

type Location struct {
	URI   string `json:"uri"`
	Start int    `json:"start"`
	End   int    `json:"end"`
}

// Symbol is one named source declaration.

type Symbol struct {
	Name      string   `json:"name"`
	Kind      string   `json:"kind"`
	Container string   `json:"container,omitempty"`
	Range     Location `json:"range"`
	Selection Location `json:"selection"`
}

// Hover is type information for one source identifier.

type Hover struct {
	Contents string   `json:"contents"`
	Range    Location `json:"range"`
}

type occurrence struct {
	location Location
	key      string
}

type sourcePosition struct {
	file   string
	line   int
	column int
}

type workspaceIndex struct {
	occurrences []occurrence
	definitions map[string]Location
	hovers      map[string]string
	references  map[string][]Location
	symbols     []Symbol
}

// DocumentSymbols returns all declarations in one TGo source file.
func (e *Engine) DocumentSymbols(
	ctx context.Context,
	uri string,
) ([]Symbol, error) {
	index, err := e.load(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]Symbol, 0)
	for _, symbol := range index.symbols {
		if symbol.Range.URI == uri {
			result = append(result, symbol)
		}
	}
	return result, nil
}

// WorkspaceSymbols returns declarations whose names contain the query.
func (e *Engine) WorkspaceSymbols(
	ctx context.Context,
	query string,
) ([]Symbol, error) {
	index, err := e.load(ctx)
	if err != nil {
		return nil, err
	}
	query = strings.ToLower(query)
	result := make([]Symbol, 0)
	for _, symbol := range index.symbols {
		if query == "" || strings.Contains(strings.ToLower(symbol.Name), query) {
			result = append(result, symbol)
		}
	}
	return result, nil
}

// Engine owns one invalidatable workspace index.

type Engine struct {
	root       string
	mu         *sync.Mutex
	index      *workspaceIndex
	generation uint64
	building   bool
	ready      chan struct{}
}

// New makes an engine for one workspace directory.
func New(root string) (*Engine, error) {
	absolute, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	return &Engine{
		root: absolute, mu: new(sync.Mutex), index: nil, generation: 0,
		building: false, ready: nil,
	}, nil

}

// Invalidate removes all cached facts after a source or module change.
func (e *Engine) Invalidate() {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.index = nil
	e.generation++
}

// Definition returns the exact declaration for the name at a byte offset.
func (e *Engine) Definition(
	ctx context.Context,
	uri string,
	offset int,
) ([]Location, error) {
	index, err := e.load(ctx)
	if err != nil {
		return nil, err
	}
	for _, item := range index.occurrences {
		if item.location.URI == uri && item.location.Start <= offset &&
			offset < item.location.End {
			definition, ok := index.definitions[item.key]
			if !ok {
				return nil, nil
			}
			return []Location{definition}, nil
		}
	}
	return nil, nil
}

// Hover returns type information for the name at a byte offset.
func (e *Engine) Hover(
	ctx context.Context,
	uri string,
	offset int,
) (*Hover, error) {
	index, err := e.load(ctx)
	if err != nil {
		return nil, err
	}
	for _, item := range index.occurrences {
		if item.location.URI == uri && item.location.Start <= offset &&
			offset < item.location.End {
			contents, ok := index.hovers[item.key]
			if !ok {
				return nil, nil
			}
			return &Hover{Contents: contents, Range: item.location}, nil
		}
	}
	return nil, nil
}

// References returns all exact uses of the name at a byte offset.
func (e *Engine) References(
	ctx context.Context,
	uri string,
	offset int,
	includeDeclaration bool,
) ([]Location, error) {
	index, err := e.load(ctx)
	if err != nil {
		return nil, err
	}
	for _, item := range index.occurrences {
		if item.location.URI != uri || offset < item.location.Start ||
			item.location.End <= offset {
			continue
		}
		result := make([]Location, 0, len(index.references[item.key]))
		definition, hasDefinition := index.definitions[item.key]
		seen := make(map[Location]bool)
		for _, location := range index.references[item.key] {
			if hasDefinition && location == definition {
				continue
			}
			result = append(result, location)
			seen[location] = true
		}
		if includeDeclaration && hasDefinition && !seen[definition] {
			result = append(result, definition)
		}
		sort.Slice(result, func(left, right int) bool {
			if result[left].URI != result[right].URI {
				return result[left].URI < result[right].URI
			}
			return result[left].Start < result[right].Start
		})
		return result, nil
	}
	return nil, nil
}

func (e *Engine) load(ctx context.Context) (*workspaceIndex, error) {
	for {
		e.mu.Lock()
		if e.index != nil {
			index := e.index
			e.mu.Unlock()
			return index, nil
		}
		generation := e.generation
		if e.building {
			ready := e.ready
			e.mu.Unlock()
			select {
			case <-ctx.Done():
				return nil, ctx.Err()
			case <-ready:
			}
			continue
		}
		e.building = true
		e.ready = make(chan struct{})
		e.mu.Unlock()
		index, err := e.buildIndex(ctx)
		e.mu.Lock()
		current := err == nil && generation == e.generation
		if current {
			e.index = index
		}
		e.building = false
		close(e.ready)
		e.ready = nil
		e.mu.Unlock()
		if err != nil {
			return nil, err
		}
		if current {
			return index, nil
		}
	}
}

func (e *Engine) buildIndex(ctx context.Context) (*workspaceIndex, error) {
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	default:
	}
	packages, err := driver.AnalyzeWorkspaceContext(ctx, e.root)
	if err != nil {
		return nil, err
	}
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	default:
	}
	index := &workspaceIndex{
		occurrences: nil,
		definitions: make(map[string]Location),
		hovers:      make(map[string]string),
		references:  make(map[string][]Location),
		symbols:     nil,
	}
	for _, pkg := range packages {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		default:
		}
		keys := newObjectKeys(pkg.Package)
		ownerLocations := make(map[token.Pos]Location)
		generatedUses := make(map[sourcePosition]types.Object)
		for position, object := range pkg.GeneratedUses {
			generatedUses[positionKey(pkg.Files.Position(position))] = object
		}
		for _, source := range pkg.Sources {
			fileURI, tgoErr := pathURI(source.Path)
			if tgoErr != nil {
				return nil, tgoErr
			}
			syntax.Inspect(source.Syntax, func(node *syntax.Node) bool {
				identifier, ok := syntax.IdentifierOf(node)
				if !ok || identifier == nil {
					return true
				}
				start := pkg.Files.Position(identifier.Start).Offset
				end := pkg.Files.Position(identifier.Stop).Offset
				if start < 0 || end <= start {
					return true
				}
				location := Location{URI: fileURI, Start: start, End: end}
				ownerLocations[identifier.Start] = location
				object, definition := pkg.Facts.IdentifierFact(source.Syntax, node)
				if object == nil {
					object = generatedUses[positionKey(pkg.Files.Position(identifier.Start))]
				}
				if object == nil {
					return true
				}
				key := keys.key(object)
				qualifier := types.RelativeTo(object.Pkg())
				contents := types.ObjectString(object, qualifier)
				if function, ok := object.(*types.Func); ok {
					signature := function.Type().(*types.Signature)
					if receiver := signature.Recv(); receiver != nil {
						contents = "func (" + types.TypeString(
							receiver.Type(), qualifier,
						) + ") " + function.Name() + strings.TrimPrefix(
							types.TypeString(signature, qualifier), "func",
						)
					}
				}
				index.hovers[key] = contents
				index.occurrences = append(index.occurrences, occurrence{
					location: location, key: key,
				})
				index.references[key] = append(index.references[key], location)
				if definition {
					index.definitions[key] = location
				}
				return true
			})
			index.symbols = append(
				index.symbols,
				sourceSymbols(pkg, source, fileURI)...,
			)
		}
		for object, position := range pkg.Owners {
			location, ok := ownerLocations[position]
			if ok {
				index.definitions[keys.key(object)] = location
			}
		}
	}
	sort.Slice(index.symbols, func(left, right int) bool {
		if index.symbols[left].Selection.URI != index.symbols[right].Selection.URI {
			return index.symbols[left].Selection.URI < index.symbols[right].Selection.URI
		}
		return index.symbols[left].Selection.Start < index.symbols[right].Selection.Start
	})
	return index, nil
}

func positionKey(position token.Position) sourcePosition {
	return sourcePosition{
		file: position.Filename, line: position.Line, column: position.Column,
	}
}

type objectKeys struct {
	known map[types.Object]string
	next  int
}

func newObjectKeys(root *types.Package) *objectKeys {
	keys := &objectKeys{known: make(map[types.Object]string), next: 0}
	keys.addPackage(root, make(map[*types.Package]bool))
	return keys
}

func (k *objectKeys) addPackage(pkg *types.Package, seen map[*types.Package]bool) {
	if pkg == nil || seen[pkg] {
		return
	}
	seen[pkg] = true
	scope := pkg.Scope()
	for _, name := range scope.Names() {
		object := scope.Lookup(name)
		prefix := "package:" + pkg.Path() + ":" + name
		k.known[object] = prefix
		typeName, ok := object.(*types.TypeName)
		if !ok {
			continue
		}
		named, ok := types.Unalias(typeName.Type()).(*types.Named)
		if !ok {
			continue
		}
		k.addNamed(prefix, named)
	}
	for _, imported := range pkg.Imports() {
		k.addPackage(imported, seen)
	}
}

func (k *objectKeys) addNamed(prefix string, named *types.Named) {
	origin := named.Origin()
	for index := 0; index < origin.NumMethods(); index++ {
		method := origin.Method(index)
		k.known[method] = prefix + ":method:" + method.Name()
	}
	switch value := origin.Underlying().(type) {
	case *types.Struct:
		for index := 0; index < value.NumFields(); index++ {
			field := value.Field(index)
			k.known[field] = prefix + ":field:" + strconv.Itoa(index)
		}
	case *types.Interface:
		value.Complete()
		for index := 0; index < value.NumExplicitMethods(); index++ {
			method := value.ExplicitMethod(index)
			k.known[method] = prefix + ":method:" + method.Name()
		}
	}
}

func (k *objectKeys) key(object types.Object) string {
	if key := k.known[object]; key != "" {
		return key
	}
	packagePath := "universe"
	if object.Pkg() != nil {
		packagePath = object.Pkg().Path()
	}
	k.next++
	key := fmt.Sprintf("local:%s:%d", packagePath, k.next)
	k.known[object] = key
	return key
}

func pathURI(path string) (string, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	return pathURIValue(absolute, filepath.VolumeName(absolute)), nil
}

func pathURIValue(absolute string, volume string) string {
	slashPath := filepath.ToSlash(absolute)
	slashVolume := filepath.ToSlash(volume)
	value := new(url.URL)
	value.Scheme = "file"
	if strings.HasPrefix(slashVolume, "//") {
		authority := strings.TrimPrefix(slashVolume, "//")
		separator := strings.IndexByte(authority, '/')
		if separator >= 0 {
			value.Host = authority[:separator]
			value.Path = "/" + authority[separator+1:] +
				strings.TrimPrefix(slashPath, slashVolume)
			return value.String()
		}
	}
	if slashVolume != "" && !strings.HasPrefix(slashPath, "/") {
		slashPath = "/" + slashPath
	}
	value.Path = slashPath
	return value.String()
}
