// Code generated by tgo. DO NOT EDIT.

// Package navigation indexes typed TGo source for read-only code navigation.
package navigation

import "encoding/json"
import jsonv2 "encoding/json/v2"
import "encoding/json/jsontext"

import (
	"context"
	"fmt"
	"go/token"
	"go/types"
	"net/url"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"

	"tgo/internal/sourceanalysis"
	"tgo/pkg/syntax"
)

// Location is one exact byte range in a source file URI.

type Location struct {
	URI   string `json:"uri"`
	Start int    `json:"start"`
	End   int    `json:"end"`
}

// SymbolKind identifies one closed class of source declaration.
func tgoSymbolKindExternalJSONTo[T interface{}](out *jsontext.Encoder, name string, payload T) error {
	{
		err := out.WriteToken(jsontext.BeginObject)
		if err != nil {
			return err
		}
	}
	{
		err := out.WriteToken(jsontext.String(name))
		if err != nil {
			return err
		}
	}
	{
		err := jsonv2.MarshalEncode(out, payload)
		if err != nil {
			return err
		}
	}
	return out.WriteToken(jsontext.EndObject)
}

// SymbolKind requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type SymbolKindTag uint8

const (
	SymbolKindTagPackage SymbolKindTag = iota + 1
	SymbolKindTagType
	SymbolKindTagStruct
	SymbolKindTagInterface
	SymbolKindTagFunction
	SymbolKindTagMethod
	SymbolKindTagField
	SymbolKindTagEnum
	SymbolKindTagEnumMember
	SymbolKindTagConstant
	SymbolKindTagVariable
)

type SymbolKind struct {
	tgoTag SymbolKindTag
}

// Tag returns the active tag.
func (v SymbolKind) Tag() SymbolKindTag { return v.tgoTag }

// GobEncode returns the stable four-byte enum tag.
func (v SymbolKind) GobEncode() ([]byte, error) {
	operand := v.tgoTag < SymbolKindTagPackage
	if !operand {
		operand = v.tgoTag > SymbolKindTagVariable
	}
	if operand {
		return nil, fmt.Errorf("SymbolKind: cannot gob encode invalid tag %d", v.tgoTag)
	}
	tag := uint32(v.tgoTag)
	return []byte{byte(tag >> 24), byte(tag >> 16), byte(tag >> 8), byte(tag)}, nil
}

// GobDecode replaces the value with a valid four-byte enum tag.
func (v *SymbolKind) GobDecode(data []byte) error {
	if len(data) != 4 {
		return fmt.Errorf("SymbolKind: invalid gob data length %d", len(data))
	}
	number := uint32(data[0])<<24 | uint32(data[1])<<16 | uint32(data[2])<<8 | uint32(data[3])
	tag := SymbolKindTag(number)
	operand := uint32(tag) != number
	if !operand {
		operand = tag < SymbolKindTagPackage
	}
	operand_1 := operand
	if !operand_1 {
		operand_1 = tag > SymbolKindTagVariable
	}
	if operand_1 {
		return fmt.Errorf("SymbolKind: cannot gob decode unknown tag %d", number)
	}
	switch tag {
	case SymbolKindTagPackage:
		*v = NewSymbolKindPackage()
	case SymbolKindTagType:
		*v = NewSymbolKindType()
	case SymbolKindTagStruct:
		*v = NewSymbolKindStruct()
	case SymbolKindTagInterface:
		*v = NewSymbolKindInterface()
	case SymbolKindTagFunction:
		*v = NewSymbolKindFunction()
	case SymbolKindTagMethod:
		*v = NewSymbolKindMethod()
	case SymbolKindTagField:
		*v = NewSymbolKindField()
	case SymbolKindTagEnum:
		*v = NewSymbolKindEnum()
	case SymbolKindTagEnumMember:
		*v = NewSymbolKindEnumMember()
	case SymbolKindTagConstant:
		*v = NewSymbolKindConstant()
	case SymbolKindTagVariable:
		*v = NewSymbolKindVariable()
	}
	return nil
}

// SymbolKindPackage is the Package payload.
type SymbolKindPackage struct{}

// NewSymbolKindPackage constructs SymbolKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewSymbolKindPackage() SymbolKind {
	return SymbolKind{tgoTag: SymbolKindTagPackage}
}

// PackagePayload requires Package. No tag check.
func (SymbolKind) PackagePayload() SymbolKindPackage { return SymbolKindPackage{} }

// SymbolKindType is the Type payload.
type SymbolKindType struct{}

// NewSymbolKindType constructs SymbolKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewSymbolKindType() SymbolKind {
	return SymbolKind{tgoTag: SymbolKindTagType}
}

// TypePayload requires Type. No tag check.
func (SymbolKind) TypePayload() SymbolKindType { return SymbolKindType{} }

// SymbolKindStruct is the Struct payload.
type SymbolKindStruct struct{}

// NewSymbolKindStruct constructs SymbolKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewSymbolKindStruct() SymbolKind {
	return SymbolKind{tgoTag: SymbolKindTagStruct}
}

// StructPayload requires Struct. No tag check.
func (SymbolKind) StructPayload() SymbolKindStruct { return SymbolKindStruct{} }

// SymbolKindInterface is the Interface payload.
type SymbolKindInterface struct{}

// NewSymbolKindInterface constructs SymbolKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewSymbolKindInterface() SymbolKind {
	return SymbolKind{tgoTag: SymbolKindTagInterface}
}

// InterfacePayload requires Interface. No tag check.
func (SymbolKind) InterfacePayload() SymbolKindInterface { return SymbolKindInterface{} }

// SymbolKindFunction is the Function payload.
type SymbolKindFunction struct{}

// NewSymbolKindFunction constructs SymbolKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewSymbolKindFunction() SymbolKind {
	return SymbolKind{tgoTag: SymbolKindTagFunction}
}

// FunctionPayload requires Function. No tag check.
func (SymbolKind) FunctionPayload() SymbolKindFunction { return SymbolKindFunction{} }

// SymbolKindMethod is the Method payload.
type SymbolKindMethod struct{}

// NewSymbolKindMethod constructs SymbolKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewSymbolKindMethod() SymbolKind {
	return SymbolKind{tgoTag: SymbolKindTagMethod}
}

// MethodPayload requires Method. No tag check.
func (SymbolKind) MethodPayload() SymbolKindMethod { return SymbolKindMethod{} }

// SymbolKindField is the Field payload.
type SymbolKindField struct{}

// NewSymbolKindField constructs SymbolKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewSymbolKindField() SymbolKind {
	return SymbolKind{tgoTag: SymbolKindTagField}
}

// FieldPayload requires Field. No tag check.
func (SymbolKind) FieldPayload() SymbolKindField { return SymbolKindField{} }

// SymbolKindEnum is the Enum payload.
type SymbolKindEnum struct{}

// NewSymbolKindEnum constructs SymbolKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewSymbolKindEnum() SymbolKind {
	return SymbolKind{tgoTag: SymbolKindTagEnum}
}

// EnumPayload requires Enum. No tag check.
func (SymbolKind) EnumPayload() SymbolKindEnum { return SymbolKindEnum{} }

// SymbolKindEnumMember is the EnumMember payload.
type SymbolKindEnumMember struct{}

// NewSymbolKindEnumMember constructs SymbolKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewSymbolKindEnumMember() SymbolKind {
	return SymbolKind{tgoTag: SymbolKindTagEnumMember}
}

// EnumMemberPayload requires EnumMember. No tag check.
func (SymbolKind) EnumMemberPayload() SymbolKindEnumMember { return SymbolKindEnumMember{} }

// SymbolKindConstant is the Constant payload.
type SymbolKindConstant struct{}

// NewSymbolKindConstant constructs SymbolKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewSymbolKindConstant() SymbolKind {
	return SymbolKind{tgoTag: SymbolKindTagConstant}
}

// ConstantPayload requires Constant. No tag check.
func (SymbolKind) ConstantPayload() SymbolKindConstant { return SymbolKindConstant{} }

// SymbolKindVariable is the Variable payload.
type SymbolKindVariable struct{}

// NewSymbolKindVariable constructs SymbolKind. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewSymbolKindVariable() SymbolKind {
	return SymbolKind{tgoTag: SymbolKindTagVariable}
}

// VariablePayload requires Variable. No tag check.
func (SymbolKind) VariablePayload() SymbolKindVariable { return SymbolKindVariable{} }

func (v SymbolKind) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case SymbolKindTagPackage:
		payload := v.PackagePayload()
		return json.Marshal(struct {
			Payload SymbolKindPackage `json:"Package"`
		}{Payload: payload})
	case SymbolKindTagType:
		payload := v.TypePayload()
		return json.Marshal(struct {
			Payload SymbolKindType `json:"Type"`
		}{Payload: payload})
	case SymbolKindTagStruct:
		payload := v.StructPayload()
		return json.Marshal(struct {
			Payload SymbolKindStruct `json:"Struct"`
		}{Payload: payload})
	case SymbolKindTagInterface:
		payload := v.InterfacePayload()
		return json.Marshal(struct {
			Payload SymbolKindInterface `json:"Interface"`
		}{Payload: payload})
	case SymbolKindTagFunction:
		payload := v.FunctionPayload()
		return json.Marshal(struct {
			Payload SymbolKindFunction `json:"Function"`
		}{Payload: payload})
	case SymbolKindTagMethod:
		payload := v.MethodPayload()
		return json.Marshal(struct {
			Payload SymbolKindMethod `json:"Method"`
		}{Payload: payload})
	case SymbolKindTagField:
		payload := v.FieldPayload()
		return json.Marshal(struct {
			Payload SymbolKindField `json:"Field"`
		}{Payload: payload})
	case SymbolKindTagEnum:
		payload := v.EnumPayload()
		return json.Marshal(struct {
			Payload SymbolKindEnum `json:"Enum"`
		}{Payload: payload})
	case SymbolKindTagEnumMember:
		payload := v.EnumMemberPayload()
		return json.Marshal(struct {
			Payload SymbolKindEnumMember `json:"EnumMember"`
		}{Payload: payload})
	case SymbolKindTagConstant:
		payload := v.ConstantPayload()
		return json.Marshal(struct {
			Payload SymbolKindConstant `json:"Constant"`
		}{Payload: payload})
	case SymbolKindTagVariable:
		payload := v.VariablePayload()
		return json.Marshal(struct {
			Payload SymbolKindVariable `json:"Variable"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid SymbolKind JSON tag")
	}
}

func (v SymbolKind) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case SymbolKindTagPackage:
		payload := v.PackagePayload()
		return tgoSymbolKindExternalJSONTo(out, "Package", payload)
	case SymbolKindTagType:
		payload := v.TypePayload()
		return tgoSymbolKindExternalJSONTo(out, "Type", payload)
	case SymbolKindTagStruct:
		payload := v.StructPayload()
		return tgoSymbolKindExternalJSONTo(out, "Struct", payload)
	case SymbolKindTagInterface:
		payload := v.InterfacePayload()
		return tgoSymbolKindExternalJSONTo(out, "Interface", payload)
	case SymbolKindTagFunction:
		payload := v.FunctionPayload()
		return tgoSymbolKindExternalJSONTo(out, "Function", payload)
	case SymbolKindTagMethod:
		payload := v.MethodPayload()
		return tgoSymbolKindExternalJSONTo(out, "Method", payload)
	case SymbolKindTagField:
		payload := v.FieldPayload()
		return tgoSymbolKindExternalJSONTo(out, "Field", payload)
	case SymbolKindTagEnum:
		payload := v.EnumPayload()
		return tgoSymbolKindExternalJSONTo(out, "Enum", payload)
	case SymbolKindTagEnumMember:
		payload := v.EnumMemberPayload()
		return tgoSymbolKindExternalJSONTo(out, "EnumMember", payload)
	case SymbolKindTagConstant:
		payload := v.ConstantPayload()
		return tgoSymbolKindExternalJSONTo(out, "Constant", payload)
	case SymbolKindTagVariable:
		payload := v.VariablePayload()
		return tgoSymbolKindExternalJSONTo(out, "Variable", payload)
	default:
		return fmt.Errorf("invalid SymbolKind JSON tag")
	}
}

func (v *SymbolKind) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	{
		err := json.Unmarshal(data, &object)
		if err != nil {
			return err
		}
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one SymbolKind JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Package":
		var payload SymbolKindPackage
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindPackage()
		return nil
	case "Type":
		var payload SymbolKindType
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindType()
		return nil
	case "Struct":
		var payload SymbolKindStruct
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindStruct()
		return nil
	case "Interface":
		var payload SymbolKindInterface
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindInterface()
		return nil
	case "Function":
		var payload SymbolKindFunction
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindFunction()
		return nil
	case "Method":
		var payload SymbolKindMethod
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindMethod()
		return nil
	case "Field":
		var payload SymbolKindField
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindField()
		return nil
	case "Enum":
		var payload SymbolKindEnum
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindEnum()
		return nil
	case "EnumMember":
		var payload SymbolKindEnumMember
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindEnumMember()
		return nil
	case "Constant":
		var payload SymbolKindConstant
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindConstant()
		return nil
	case "Variable":
		var payload SymbolKindVariable
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindVariable()
		return nil
	default:
		return fmt.Errorf("unknown SymbolKind JSON variant %q", variant)
	}
}

func (v *SymbolKind) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one SymbolKind JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Package":
			current = 1
		case "Type":
			current = 2
		case "Struct":
			current = 3
		case "Interface":
			current = 4
		case "Function":
			current = 5
		case "Method":
			current = 6
		case "Field":
			current = 7
		case "Enum":
			current = 8
		case "EnumMember":
			current = 9
		case "Constant":
			current = 10
		case "Variable":
			current = 11
		}
		same := haveName
		if same {
			same = current == selected
		}
		operand := same
		if operand {
			operand = current == 0
		}
		if operand {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		operand_1 := !multiple
		if operand_1 {
			operand_1 = current > 0
		}
		var operand_2 bool = operand_1
		if operand_2 {
			operand_2 = current == selected
		}
		if operand_2 {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else {
			err := in.SkipValue()
			if err != nil {
				return err
			}
		}
	}
	{
		_, err := in.ReadToken()
		if err != nil {
			return err
		}
	}
	operand_3 := !haveName
	if !operand_3 {
		operand_3 = multiple
	}
	if operand_3 {
		return fmt.Errorf("expected one SymbolKind JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown SymbolKind JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload SymbolKindPackage
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindPackage()
		return nil
	case 2:
		var payload SymbolKindType
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindType()
		return nil
	case 3:
		var payload SymbolKindStruct
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindStruct()
		return nil
	case 4:
		var payload SymbolKindInterface
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindInterface()
		return nil
	case 5:
		var payload SymbolKindFunction
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindFunction()
		return nil
	case 6:
		var payload SymbolKindMethod
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindMethod()
		return nil
	case 7:
		var payload SymbolKindField
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindField()
		return nil
	case 8:
		var payload SymbolKindEnum
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindEnum()
		return nil
	case 9:
		var payload SymbolKindEnumMember
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindEnumMember()
		return nil
	case 10:
		var payload SymbolKindConstant
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindConstant()
		return nil
	case 11:
		var payload SymbolKindVariable
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewSymbolKindVariable()
		return nil
	default:
		return fmt.Errorf("invalid SymbolKind JSON tag")
	}
}

// Symbol is one named source declaration.

type Symbol struct {
	Name      string `json:"name"`
	Kind      SymbolKind
	Container string   `json:"container,omitempty"`
	Range     Location `json:"range"`
	Selection Location `json:"selection"`
}

// Hover is type information for one source identifier.

type Hover struct {
	Contents string   `json:"contents"`
	Range    Location `json:"range"`
}

type occurrence struct {
	location Location
	key      string
	hover    string
}

type sourcePosition struct {
	file   string
	line   int
	column int
}

type workspaceIndex struct {
	occurrences []occurrence
	definitions map[string]Location
	references  map[string][]Location
	symbols     []Symbol
}

// DocumentSymbols returns all declarations in one TGo source file.
func (e *Engine) DocumentSymbols(
	ctx context.Context,
	uri string,
) ([]Symbol, error) {
	index, err := e.load(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]Symbol, 0)
	for _, symbol := range index.symbols {
		if symbol.Range.URI == uri {
			result = append(result, symbol)
		}
	}
	return result, nil
}

// WorkspaceSymbols returns declarations whose names contain the query.
func (e *Engine) WorkspaceSymbols(
	ctx context.Context,
	query string,
) ([]Symbol, error) {
	index, err := e.load(ctx)
	if err != nil {
		return nil, err
	}

	query = strings.ToLower(query)
	result := make([]Symbol, 0)
	for _, symbol := range index.symbols {
		var operand bool = query == ""
		if !operand {
			operand = strings.Contains(strings.ToLower(symbol.Name), query)
		}
		if operand {
			result = append(result, symbol)
		}
	}
	return result, nil
}

// Engine owns one invalidatable workspace index.

type Engine struct {
	root       string
	mu         *sync.Mutex
	index      *workspaceIndex
	generation uint64
	building   bool
	ready      chan struct{}
}

// New makes an engine for one workspace directory.
func New(root string) (*Engine, error) {
	absolute, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}

	return &Engine{
		root: absolute, mu: new(sync.Mutex), index: nil, generation: 0,
		building: false, ready: nil,
	}, nil

}

// Invalidate removes all cached facts after a source or module change.
func (e *Engine) Invalidate() {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.index = nil
	e.generation++
}

// Definition returns the exact declaration for the name at a byte offset.
func (e *Engine) Definition(
	ctx context.Context,
	uri string,
	offset int,
) ([]Location, error) {
	index, err := e.load(ctx)
	if err != nil {
		return nil, err
	}

	for _, item := range index.occurrences {
		var operand bool = item.location.URI == uri
		if operand {
			operand = item.location.Start <= offset
		}
		var operand_1 bool = operand
		if operand_1 {
			operand_1 = offset < item.location.End
		}
		if operand_1 {
			definition, ok := index.definitions[item.key]
			if !ok {
				return nil, nil
			}
			return []Location{definition}, nil
		}
	}
	return nil, nil
}

// Hover returns type information for the name at a byte offset.
func (e *Engine) Hover(
	ctx context.Context,
	uri string,
	offset int,
) (*Hover, error) {
	index, err := e.load(ctx)
	if err != nil {
		return nil, err
	}

	for _, item := range index.occurrences {
		var operand bool = item.location.URI == uri
		if operand {
			operand = item.location.Start <= offset
		}
		var operand_1 bool = operand
		if operand_1 {
			operand_1 = offset < item.location.End
		}
		if operand_1 {
			return &Hover{Contents: item.hover, Range: item.location}, nil
		}
	}
	return nil, nil
}

// References returns all exact uses of the name at a byte offset.
func (e *Engine) References(
	ctx context.Context,
	uri string,
	offset int,
	includeDeclaration bool,
) ([]Location, error) {
	index, err := e.load(ctx)
	if err != nil {
		return nil, err
	}

	for _, item := range index.occurrences {
		var operand bool = item.location.URI != uri
		if !operand {
			operand = offset < item.location.Start
		}
		var operand_1 bool = operand
		if !operand_1 {
			operand_1 = item.location.End <= offset
		}
		if operand_1 {
			continue
		}
		result := make([]Location, 0, len(index.references[item.key]))
		definition, hasDefinition := index.definitions[item.key]
		seen := make(map[Location]bool)
		for _, location := range index.references[item.key] {
			operand_2 := hasDefinition
			if operand_2 {
				operand_2 = location == definition
			}
			if operand_2 {
				continue
			}
			result = append(result, location)
			seen[location] = true
		}
		operand_3 := includeDeclaration
		if operand_3 {
			operand_3 = hasDefinition
		}
		var operand_4 bool = operand_3
		if operand_4 {
			operand_4 = !seen[definition]
		}
		if operand_4 {
			result = append(result, definition)
		}
		sort.Slice(result, func(left, right int) bool {
			if result[left].URI != result[right].URI {
				return result[left].URI < result[right].URI
			}
			return result[left].Start < result[right].Start
		})
		return result, nil
	}
	return nil, nil
}

func (e *Engine) load(ctx context.Context) (*workspaceIndex, error) {
	for {
		e.mu.Lock()
		if e.index != nil {
			index := e.index
			e.mu.Unlock()
			return index, nil
		}
		generation := e.generation
		if e.building {
			ready := e.ready
			e.mu.Unlock()
			{
				operand := ctx.Done()
				operand_1 := ready
				select {
				case <-operand:
					return nil, ctx.Err()
				case <-operand_1:
				}
			}
			continue
		}
		e.building = true
		e.ready = make(chan struct{})
		e.mu.Unlock()
		index, err := e.buildIndex(ctx)
		e.mu.Lock()
		var current bool = err == nil
		if current {
			current = generation == e.generation
		}
		if current {
			e.index = index
		}
		e.building = false
		close(e.ready)
		e.ready = nil
		e.mu.Unlock()
		if err != nil {
			return nil, err
		}
		if current {
			return index, nil
		}
	}
}

func (e *Engine) buildIndex(ctx context.Context) (*workspaceIndex, error) {
	{
		operand := ctx.Done()
		select {
		case <-operand:
			return nil, ctx.Err()
		default:
		}
	}
	packages, err := sourceanalysis.AnalyzeAvailableWorkspaceContext(ctx, e.root)
	if err != nil {
		return nil, err
	}
	{
		operand_1 := ctx.Done()
		select {
		case <-operand_1:
			return nil, ctx.Err()
		default:
		}
	}
	index := &workspaceIndex{
		occurrences: nil,
		definitions: make(map[string]Location),
		references:  make(map[string][]Location),
		symbols:     nil,
	}
	for view, pkg := range packages {
		{
			operand_2 := ctx.Done()
			select {
			case <-operand_2:
				return nil, ctx.Err()
			default:
			}
		}
		keys := newObjectKeys(pkg.Package, view)
		ownerLocations := make(map[token.Pos]Location)
		generatedUses := make(map[sourcePosition]types.Object)
		for position, object := range pkg.GeneratedUses {
			generatedUses[positionKey(pkg.Files.Position(position))] = object
		}
		for _, source := range pkg.Sources {
			fileURI, err_1 := pathURI(source.Path)
			if err_1 != nil {
				return nil, err_1
			}

			syntax.Inspect(source.Syntax, func(node *syntax.Node) bool {
				identifier, ok := syntax.IdentifierOf(node)
				operand := !ok
				if !operand {
					operand = identifier == nil
				}
				if operand {
					return true
				}
				start := pkg.Files.Position(identifier.Start).Offset
				end := pkg.Files.Position(identifier.Stop).Offset
				var operand_1 bool = start < 0
				if !operand_1 {
					operand_1 = end <= start
				}
				if operand_1 {
					return true
				}
				location := Location{URI: fileURI, Start: start, End: end}
				ownerLocations[identifier.Start] = location
				object, definition := pkg.Facts.IdentifierFact(source.Syntax, node)
				if object == nil {
					object = generatedUses[positionKey(pkg.Files.Position(identifier.Start))]
				}
				if object == nil {
					return true
				}
				key := keys.key(object)
				qualifier := types.RelativeTo(object.Pkg())
				contents := pkg.OwnerHovers[object]
				if contents == "" {
					contents = types.ObjectString(object, qualifier)
				}
				{
					function, ok := object.(*types.Func)
					operand_2 := ok
					if operand_2 {
						operand_2 = pkg.OwnerHovers[object] == ""
					}
					if operand_2 {
						signature := function.Type().(*types.Signature)
						{
							receiver := signature.Recv()
							if receiver != nil {
								contents = "func (" + types.TypeString(
									receiver.Type(), qualifier,
								) + ") " + function.Name() + strings.TrimPrefix(
									types.TypeString(signature, qualifier), "func",
								)
							}
						}
					}
				}
				index.occurrences = append(index.occurrences, occurrence{
					location: location, key: key, hover: contents,
				})
				index.references[key] = append(index.references[key], location)
				if definition {
					index.definitions[key] = location
				}
				return true
			})
			index.symbols = append(
				index.symbols,
				sourceSymbols(pkg, source, fileURI)...,
			)
		}
		for object, position := range pkg.Owners {
			location, ok := ownerLocations[position]
			if ok {
				index.definitions[keys.key(object)] = location
			}
		}
	}
	sort.Slice(index.symbols, func(left, right int) bool {
		if index.symbols[left].Selection.URI != index.symbols[right].Selection.URI {
			return index.symbols[left].Selection.URI < index.symbols[right].Selection.URI
		}
		return index.symbols[left].Selection.Start < index.symbols[right].Selection.Start
	})
	return index, nil
}

func positionKey(position token.Position) sourcePosition {
	return sourcePosition{
		file: position.Filename, line: position.Line, column: position.Column,
	}
}

type objectKeys struct {
	known map[types.Object]string
	view  int
	next  int
}

func newObjectKeys(root *types.Package, view int) *objectKeys {
	keys := &objectKeys{known: make(map[types.Object]string), view: view, next: 0}
	keys.addPackage(root, make(map[*types.Package]bool))
	return keys
}

func (k *objectKeys) addPackage(pkg *types.Package, seen map[*types.Package]bool) {
	var operand bool = pkg == nil
	if !operand {
		operand = seen[pkg]
	}
	if operand {
		return
	}
	seen[pkg] = true
	scope := pkg.Scope()
	for _, name := range scope.Names() {
		object := scope.Lookup(name)
		prefix := "package:" + pkg.Path() + ":" + name
		k.known[object] = prefix
		typeName, ok := object.(*types.TypeName)
		if !ok {
			continue
		}
		named, ok := types.Unalias(typeName.Type()).(*types.Named)
		if !ok {
			continue
		}
		k.addNamed(prefix, named)
	}
	for _, imported := range pkg.Imports() {
		k.addPackage(imported, seen)
	}
}

func (k *objectKeys) addNamed(prefix string, named *types.Named) {
	origin := named.Origin()
	for index := 0; index < origin.NumMethods(); index++ {
		method := origin.Method(index)
		k.known[method] = prefix + ":method:" + method.Name()
	}
	switch value := origin.Underlying().(type) {
	case *types.Struct:
		for index := 0; index < value.NumFields(); index++ {
			field := value.Field(index)
			k.known[field] = prefix + ":field:" + strconv.Itoa(index)
		}
	case *types.Interface:
		value.Complete()
		for index := 0; index < value.NumExplicitMethods(); index++ {
			method := value.ExplicitMethod(index)
			k.known[method] = prefix + ":method:" + method.Name()
		}
	}
}

func (k *objectKeys) key(object types.Object) string {
	switch value := object.(type) {
	case *types.Func:
		object = value.Origin()
	case *types.Var:
		object = value.Origin()
	}
	{
		key := k.known[object]
		if key != "" {
			return key
		}
	}
	packagePath := "universe"
	if object.Pkg() != nil {
		packagePath = object.Pkg().Path()
	}
	k.next++
	key := fmt.Sprintf("local:%s:%d:%d", packagePath, k.view, k.next)
	k.known[object] = key
	return key
}

func pathURI(path string) (string, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}

	return pathURIValue(absolute, filepath.VolumeName(absolute)), nil
}

func pathURIValue(absolute string, volume string) string {
	slashPath := filepath.ToSlash(absolute)
	slashVolume := filepath.ToSlash(volume)
	value := new(url.URL)
	value.Scheme = "file"
	if strings.HasPrefix(slashVolume, "//") {
		authority := strings.TrimPrefix(slashVolume, "//")
		separator := strings.IndexByte(authority, '/')
		if separator >= 0 {
			value.Host = authority[:separator]
			value.Path = "/" + authority[separator+1:] +
				strings.TrimPrefix(slashPath, slashVolume)
			return value.String()
		}
	}
	var operand bool = slashVolume != ""
	if operand {
		operand = !strings.HasPrefix(slashPath, "/")
	}
	if operand {
		slashPath = "/" + slashPath
	}
	value.Path = slashPath
	return value.String()
}
