// Code generated by tgo. DO NOT EDIT.

package comprehensionnil

type item struct {
}

type holder struct {
	Body []*item
}

func copyItems(groups [][]*item) {
	__tgo_source := groups[0]
	__tgo_result := make([]*item, len(__tgo_source))
	for __tgo_index, value := range __tgo_source {
		__tgo_result[__tgo_index] = copyItem(value)
	}
	result := holder{
		Body: __tgo_result,
	}
	_ = result
	for _, value := range groups[0] {
		requireItem(value)
	}
}

func copyItem(value *item) *item {
	_ = value
	return &item{}
}

func requireItem(value *item) { _ = value }
