// Code generated by tgo. DO NOT EDIT.

package driver

import (
	"errors"
	"fmt"
	"go/build"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"tgo/internal/compiler"
	"tgo/internal/outputname"
	"tgo/internal/packagelanguage"
	"tgo/pkg/syntax"
)

type packageUnit struct {
	Dir               string
	Path              string
	Module            string
	Sources           []compiler.File
	Files             []*syntax.File
	Imports           map[string]*packageUnit
	sourcePaths       []string
	testSourcePaths   []string
	matchingPaths     []string
	matchingTestPaths []string
	generatedPaths    []string
	context           *build.Context
	usesC             bool
	sourcesMatched    bool
	testsMatched      bool
	loaded            bool
	languageMatched   bool
	language          packagelanguage.Language
	matchError        error
	loadError         error
	fs                *token.FileSet
	compiled          *compiler.CompiledPackage
}

type packageTests struct {
	Sources []compiler.File
	Files   []*syntax.File
	UsesC   bool
}

// outputPath returns the Go output path while preserving target suffixes.
func (p *packageUnit) outputPath(sourcePath string) string {
	return outputname.Path(sourcePath)
}

// discover indexes possible build packages without parsing their source.
func discover(
	root string,
	module string,
	context *build.Context,
) (map[string]*packageUnit, error) {
	discovery := packageDiscovery{
		root:     root,
		module:   module,
		context:  context,
		packages: make(map[string]*packageUnit),
	}
	operand := filepath.WalkDir(root, discovery.visit)
	if operand != nil {
		return nil, operand
	}

	for _, unit := range discovery.packages {
		unit.Imports = discovery.packages
	}
	return discovery.packages, nil
}

type packageDiscovery struct {
	root     string
	module   string
	context  *build.Context
	packages map[string]*packageUnit
}

// visit adds source candidates and skips directories outside the active module.
func (d *packageDiscovery) visit(path string, entry fs.DirEntry, walkErr error) error {
	if walkErr != nil {
		return walkErr
	}
	if entry.IsDir() {
		return d.visitDirectory(path, entry.Name())
	}
	switch {
	case strings.HasSuffix(entry.Name(), ".tgo"):
		if strings.HasSuffix(entry.Name(), "_test.tgo") {
			return d.addTestSource(path)
		}
		return d.addSource(path)
	case outputname.Reserved(entry.Name()):
		return d.addGeneratedCandidate(path)
	case strings.HasSuffix(entry.Name(), ".go"):
		return d.addGoCandidate(path)
	default:
		return nil
	}
}

// addGoCandidate records one package that can be a Go-only build root.
func (d *packageDiscovery) addGoCandidate(path string) error {
	_, err := d.packageFor(filepath.Dir(path))
	return err
}

// addTestSource records one possible TGo test source file.
func (d *packageDiscovery) addTestSource(path string) error {
	unit, err := d.packageFor(filepath.Dir(path))
	if err != nil {
		return err
	}

	unit.testSourcePaths = append(unit.testSourcePaths, path)
	return nil
}

// visitDirectory skips hidden, vendor, and nested module directories.
func (d *packageDiscovery) visitDirectory(path, name string) error {
	if path == d.root {
		return nil
	}
	operand := strings.HasPrefix(name, ".")
	if !operand {
		operand = strings.HasPrefix(name, "_")
	}
	var operand_1 bool = operand
	if !operand_1 {
		operand_1 = name == "testdata"
	}
	var operand_2 bool = operand_1
	if !operand_2 {
		operand_2 = name == "vendor"
	}
	if operand_2 {
		return filepath.SkipDir
	}
	{
		_, err := os.Stat(filepath.Join(path, "go.mod"))
		if err == nil {
			return filepath.SkipDir
		} else if !errors.Is(err, os.ErrNotExist) {
			return err
		}
	}
	return nil
}

// addSource records one possible tgo source file.
func (d *packageDiscovery) addSource(path string) error {
	unit, err := d.packageFor(filepath.Dir(path))
	if err != nil {
		return err
	}

	unit.sourcePaths = append(unit.sourcePaths, path)
	return nil
}

// addGeneratedCandidate records an output that can keep an orphan package visible.
func (d *packageDiscovery) addGeneratedCandidate(path string) error {
	unit, err := d.packageFor(filepath.Dir(path))
	if err != nil {
		return err
	}

	unit.generatedPaths = append(unit.generatedPaths, path)
	return nil
}

// packageFor returns the indexed package for one directory.
func (d *packageDiscovery) packageFor(directory string) (*packageUnit, error) {
	importPath, err := d.importPath(directory)
	if err != nil {
		return nil, err
	}

	unit := d.packages[importPath]
	if unit == nil {
		unit = &packageUnit{
			Dir:               directory,
			Path:              importPath,
			Module:            d.module,
			Sources:           nil,
			Files:             nil,
			Imports:           nil,
			sourcePaths:       nil,
			testSourcePaths:   nil,
			matchingPaths:     nil,
			matchingTestPaths: nil,
			generatedPaths:    nil,
			context:           d.context,
			usesC:             false,
			sourcesMatched:    false,
			testsMatched:      false,
			loaded:            false,
			languageMatched:   false,
			language:          packagelanguage.Unknown,
			matchError:        nil,
			loadError:         nil,
			fs:                token.NewFileSet(),
			compiled:          nil,
		}
		d.packages[importPath] = unit
	}
	return unit, nil
}

// matchingTestSources returns test files enabled for the current Go target.
func (p *packageUnit) matchingTestSources() ([]string, error) {
	if p.testsMatched {
		return p.matchingTestPaths, p.matchError
	}
	p.testsMatched = true
	for _, path := range p.testSourcePaths {
		match, err := packagelanguage.MatchFile(
			p.context, path, packagelanguage.TGo,
		)
		if err != nil {
			p.matchError = err
			return nil, err
		}
		if !match {
			continue
		}
		cgo, err := fileImportsC(path)
		if err != nil {
			p.matchError = err
			return nil, err
		}
		operand := cgo
		if operand {
			operand = !p.context.CgoEnabled
		}
		if operand {
			continue
		}
		p.matchingTestPaths = append(p.matchingTestPaths, path)
	}
	return p.matchingTestPaths, nil
}

// importPath maps a package directory to its module import path.
func (d *packageDiscovery) importPath(directory string) (string, error) {
	relative, err := filepath.Rel(d.root, directory)
	if err != nil {
		return "", err
	}

	if relative == "." {
		return d.module, nil
	}
	return d.module + "/" + filepath.ToSlash(relative), nil
}

// readSource loads one TGo source and its imports.
func (p *packageUnit) readSource(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	file, err_1 := syntax.ParseFile(token.NewFileSet(), path, data, 0)
	if err_1 != nil {
		return err_1
	}

	p.Sources = append(p.Sources, compiler.File{Name: path, Data: data})
	p.Files = append(p.Files, file)
	return nil
}

// readTests groups active tests by their Go test package.
func (p *packageUnit) readTests() (packageTests, packageTests, error) {
	internal := packageTests{Sources: nil, Files: nil, UsesC: false}
	external := packageTests{Sources: nil, Files: nil, UsesC: false}
	paths, err := p.matchingTestSources()
	if err != nil {
		return packageTests{}, packageTests{}, err
	}

	if len(paths) == 0 {
		return internal, external, nil
	}
	packageName := p.Files[0].Name.Name
	for _, path := range paths {
		data, err_1 := os.ReadFile(path)
		if err_1 != nil {
			return packageTests{}, packageTests{}, err_1
		}
		file, err_2 := syntax.ParseFile(token.NewFileSet(), path, data, 0)
		if err_2 != nil {
			return packageTests{}, packageTests{}, err_2
		}

		cgo := importsC(file)
		operand := cgo
		if operand {
			operand = !p.context.CgoEnabled
		}
		if operand {
			continue
		}
		tests := &internal
		if file.Name.Name == packageName+"_test" {
			tests = &external
		} else if file.Name.Name != packageName {
			return packageTests{}, packageTests{},

				fmt.Errorf(
					"%s: package %s, want %s or %s_test",
					path, file.Name.Name, packageName, packageName,
				)
		}
		tests.Sources = append(tests.Sources, compiler.File{Name: path, Data: data})
		tests.Files = append(tests.Files, file)
		operand_1 := tests
		operand_2 := tests.UsesC
		if !operand_2 {
			operand_2 = cgo
		}
		(*operand_1).UsesC = operand_2
	}
	return internal, external, nil
}

// matchingSources returns source files enabled for the current Go target.
func (p *packageUnit) matchingSources() ([]string, error) {
	if p.sourcesMatched {
		return p.matchingPaths, p.matchError
	}
	p.sourcesMatched = true
	for _, path := range p.sourcePaths {
		match, err := packagelanguage.MatchFile(
			p.context, path, packagelanguage.TGo,
		)
		if err != nil {
			p.matchError = err
			return nil, err
		}
		if !match {
			continue
		}
		cgo, err := fileImportsC(path)
		if err != nil {
			p.matchError = err
			return nil, err
		}
		operand := cgo
		if operand {
			operand = !p.context.CgoEnabled
		}
		if operand {
			continue
		}
		operand_1 := p
		operand_2 := p.usesC
		if !operand_2 {
			operand_2 = cgo
		}
		(*operand_1).usesC = operand_2
		p.matchingPaths = append(p.matchingPaths, path)
	}
	return p.matchingPaths, nil
}

// available reports whether this package has active source or orphan output.
func (p *packageUnit) available() (bool, error) {
	result, err := p.packageLanguage()
	if err != nil {
		return false, err
	}

	_ = result
	paths, err_1 := p.matchingSources()
	if err_1 != nil {
		return false, err_1
	}

	if len(paths) > 0 {
		return true, nil
	}
	tests, err_2 := p.matchingTestSources()
	if err_2 != nil {
		return false, err_2
	}

	if len(tests) > 0 {
		return false, fmt.Errorf(
			"%s: active TGo test needs active TGo production source",
			tests[0],
		)
	}
	for _, path := range p.generatedPaths {
		owned, err_3 := generatedFile(path)
		if err_3 != nil {
			return false, err_3
		}
		operand := owned
		if operand {
			operand = !p.sourceOwnsOutput(path)
		}
		if operand {
			return true, nil
		}
	}
	return false, nil
}

// packageLanguage returns the active handwritten package language.
func (p *packageUnit) packageLanguage() (packagelanguage.Language, error) {
	if p.languageMatched {
		return p.language, p.matchError
	}
	p.languageMatched = true
	context := packagelanguage.ContextFromBuild(p.context)
	p.language, p.matchError = packagelanguage.Classify(context, p.Dir)
	return p.language, p.matchError
}

// sourceOwnsOutput reports whether a current source owns one generated path.
func (p *packageUnit) sourceOwnsOutput(path string) bool {
	for _, sourcePath := range p.sourcePaths {
		if p.outputPath(sourcePath) == path {
			return true
		}
	}
	for _, sourcePath := range p.testSourcePaths {
		if p.outputPath(sourcePath) == path {
			return true
		}
	}
	return false
}

// load parses one selected package and its active TGo files.
func (p *packageUnit) load() error {
	if p.loaded {
		return p.loadError
	}
	p.loaded = true
	{
		_, err := p.packageLanguage()
		if err != nil {
			p.loadError = err
			return err
		}
	}
	paths, err := p.matchingSources()
	if err != nil {
		p.loadError = err
		return err
	}
	for _, path := range paths {
		{
			err := p.readSource(path)
			if err != nil {
				p.loadError = err
				return err
			}
		}
	}
	return p.loadError
}

// generatedFile reports whether a reserved output is a regular file.
func generatedFile(path string) (bool, error) {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if !info.Mode().IsRegular() {
		return false, fmt.Errorf("refusing non-regular output %s", path)
	}
	return true, nil
}

// selectPackages expands command patterns to tgo package paths.
func selectPackages(
	directory string,
	patterns []string,
	packages map[string]*packageUnit,
) ([]string, error) {
	if len(patterns) == 0 {
		patterns = []string{"."}
	}
	selected := make(map[string]bool)
	for _, pattern := range patterns {
		target, recursive := packagePattern(directory, pattern)
		matched := false
		for _, path := range sortedPackagePaths(packages) {
			unit := packages[path]
			if !packageMatches(unit, path, pattern, target, recursive) {
				continue
			}
			available, err := unit.available()
			if err != nil {
				return nil, err
			}

			if !available {
				language, err_1 := unit.packageLanguage()
				if err_1 != nil {
					return nil, err_1
				}

				if language != packagelanguage.Go {
					continue
				}
			}
			selected[path] = true
			matched = true
		}
		if !matched {
			return nil, fmt.Errorf("%s: no tgo packages", pattern)
		}
	}
	paths := make([]string, 0, len(selected))
	for path := range selected {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths, nil
}

// sortedPackagePaths returns stable package map keys.
func sortedPackagePaths(packages map[string]*packageUnit) []string {
	paths := make([]string, 0, len(packages))
	for path := range packages {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths
}

// sortedTGoPackagePaths returns stable paths found by TGo discovery.
func sortedTGoPackagePaths(packages map[string]*packageUnit) []string {
	paths := make([]string, 0, len(packages))
	for path, unit := range packages {
		if unit.tgoCandidate() {
			paths = append(paths, path)
		}
	}
	sort.Strings(paths)
	return paths
}

// tgoCandidate reports whether discovery found TGo source or reserved output.
func (p *packageUnit) tgoCandidate() bool {
	var operand bool = len(p.sourcePaths) > 0
	if !operand {
		operand = len(p.testSourcePaths) > 0
	}
	var operand_1 bool = operand
	if !operand_1 {

		// packagePattern returns the directory and recursion rule for a pattern.
		operand_1 = len(p.generatedPaths) > 0
	}
	return operand_1

}

func packagePattern(directory, pattern string) (string, bool) {
	recursive := strings.HasSuffix(pattern, "/...")
	if !recursive {
		recursive = pattern == "..."
	}
	target := strings.TrimSuffix(pattern, "/...")
	if target == "..." {
		target = "."
	}
	if !filepath.IsAbs(target) {
		target = filepath.Join(directory, target)
	}
	return filepath.Clean(target), recursive
}

// packageMatches reports whether a package matches one command pattern.
func packageMatches(
	unit *packageUnit,
	path string,
	pattern string,
	target string,
	recursive bool,
) bool {
	operand := path == pattern
	if !operand {
		operand = unit.Dir == target
	}
	if operand {
		return true
	}
	childPrefix := target + string(filepath.Separator)
	operand_1 := recursive
	if operand_1 {
		operand_1 = strings.HasPrefix(unit.Dir, childPrefix)
	}
	return operand_1
}
