// Code generated by tgo. DO NOT EDIT.

package switchpackagepanicbad

import "encoding/json"
import jsonv2 "encoding/json/v2"
import "encoding/json/jsontext"
import "fmt"

func tgoResultExternalJSONTo[T interface{}](out *jsontext.Encoder, name string, payload T) error {
	{
		err := out.WriteToken(jsontext.BeginObject)
		if err != nil {
			return err
		}
	}
	{
		err := out.WriteToken(jsontext.String(name))
		if err != nil {
			return err
		}
	}
	{
		err := jsonv2.MarshalEncode(out, payload)
		if err != nil {
			return err
		}
	}
	return out.WriteToken(jsontext.EndObject)
}

// Result requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type ResultTag uint8

const (
	ResultTagSuccess ResultTag = iota + 1
	ResultTagFailure
)

type Result struct {
	tgoTag ResultTag
}

// Tag returns the active tag.
func (v Result) Tag() ResultTag { return v.tgoTag }

// GobEncode returns the stable four-byte enum tag.
func (v Result) GobEncode() ([]byte, error) {
	operand := v.tgoTag < ResultTagSuccess
	if !operand {
		operand = v.tgoTag > ResultTagFailure
	}
	if operand {
		return nil, fmt.Errorf("Result: cannot gob encode invalid tag %d", v.tgoTag)
	}
	tag := uint32(v.tgoTag)
	return []byte{byte(tag >> 24), byte(tag >> 16), byte(tag >> 8), byte(tag)}, nil
}

// GobDecode replaces the value with a valid four-byte enum tag.
func (v *Result) GobDecode(data []byte) error {
	if len(data) != 4 {
		return fmt.Errorf("Result: invalid gob data length %d", len(data))
	}
	number := uint32(data[0])<<24 | uint32(data[1])<<16 | uint32(data[2])<<8 | uint32(data[3])
	tag := ResultTag(number)
	operand := uint32(tag) != number
	if !operand {
		operand = tag < ResultTagSuccess
	}
	operand_1 := operand
	if !operand_1 {
		operand_1 = tag > ResultTagFailure
	}
	if operand_1 {
		return fmt.Errorf("Result: cannot gob decode unknown tag %d", number)
	}
	switch tag {
	case ResultTagSuccess:
		*v = NewResultSuccess()
	case ResultTagFailure:
		*v = NewResultFailure()
	}
	return nil
}

// ResultSuccess is the Success payload.
type ResultSuccess struct{}

// NewResultSuccess constructs Result. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewResultSuccess() Result {
	return Result{tgoTag: ResultTagSuccess}
}

// SuccessPayload requires Success. No tag check.
func (Result) SuccessPayload() ResultSuccess { return ResultSuccess{} }

// ResultFailure is the Failure payload.
type ResultFailure struct{}

// NewResultFailure constructs Result. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewResultFailure() Result {
	return Result{tgoTag: ResultTagFailure}
}

// FailurePayload requires Failure. No tag check.
func (Result) FailurePayload() ResultFailure { return ResultFailure{} }

func (v Result) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case ResultTagSuccess:
		payload := v.SuccessPayload()
		return json.Marshal(struct {
			Payload ResultSuccess `json:"Success"`
		}{Payload: payload})
	case ResultTagFailure:
		payload := v.FailurePayload()
		return json.Marshal(struct {
			Payload ResultFailure `json:"Failure"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid Result JSON tag")
	}
}

func (v Result) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case ResultTagSuccess:
		payload := v.SuccessPayload()
		return tgoResultExternalJSONTo(out, "Success", payload)
	case ResultTagFailure:
		payload := v.FailurePayload()
		return tgoResultExternalJSONTo(out, "Failure", payload)
	default:
		return fmt.Errorf("invalid Result JSON tag")
	}
}

func (v *Result) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	{
		err := json.Unmarshal(data, &object)
		if err != nil {
			return err
		}
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one Result JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Success":
		var payload ResultSuccess
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewResultSuccess()
		return nil
	case "Failure":
		var payload ResultFailure
		{
			err := json.Unmarshal(payloadData, &payload)
			if err != nil {
				return err
			}
		}
		*v = NewResultFailure()
		return nil
	default:
		return fmt.Errorf("unknown Result JSON variant %q", variant)
	}
}

func (v *Result) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one Result JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Success":
			current = 1
		case "Failure":
			current = 2
		}
		operand := haveName
		if operand {
			operand = current == selected
		}
		same := operand
		operand_1 := same
		if operand_1 {
			operand_1 = current == 0
		}
		if operand_1 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		operand_2 := !multiple
		if operand_2 {
			operand_2 = current > 0
		}
		var operand_3 bool = operand_2
		if operand_3 {
			operand_3 = current == selected
		}
		if operand_3 {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else {
			err := in.SkipValue()
			if err != nil {
				return err
			}
		}
	}
	{
		_, err := in.ReadToken()
		if err != nil {
			return err
		}
	}
	operand_4 := !haveName
	if !operand_4 {
		operand_4 = multiple
	}
	if operand_4 {
		return fmt.Errorf("expected one Result JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown Result JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload ResultSuccess
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewResultSuccess()
		return nil
	case 2:
		var payload ResultFailure
		{
			err := jsonv2.Unmarshal(payloadData, &payload, in.Options())
			if err != nil {
				return err
			}
		}
		*v = NewResultFailure()
		return nil
	default:
		return fmt.Errorf("invalid Result JSON tag")
	}
}

func use(value Result) {
	switch value.Tag() {
	case ResultTagSuccess:
		return
	case ResultTagFailure:
		return
	default:
		panic("invalid Result tag") // unreachable: tgolint requires a case per tag
	}
}
