// Code generated by tgo. DO NOT EDIT.
//tgo:v1 "walk.tgo" cd86b78391a858db6e74513bf548f23d07abe9c6252f27b0b2a9fa63ad9469f6

package syntax

import (
	"go/ast"
	"go/token"
	"reflect"
	"slices"
)

// Visitor is called for each Go and tgo node in a file.
type Visitor interface {
	Visit(Node) Visitor
}

// Children returns the direct source children of a node in a read-only tree.
func Children(file *File, node Node) []Node {
	if file == nil || node == nil {
		return nil
	}
	return append([]Node(nil), file.children[node]...)
}

// Parent returns the direct source parent of a node.
func Parent(file *File, node Node) Node {
	if file == nil || node == nil {
		return nil
	}
	return file.parents[node]
}

// Extensions returns all tgo nodes in source order.
func Extensions(file *File) []Extension {
	if file == nil {
		return nil
	}
	return append([]Extension(nil), file.extensions...)
}

// ExtensionAt returns the smallest tgo node that contains a position.
func ExtensionAt(file *File, position token.Pos) Extension {
	if file == nil {
		return nil
	}
	var found Extension = nil
	for _, extension := range file.extensions {
		if extension.Pos() <= position && position < extension.End() &&
			(found == nil || extension.End()-extension.Pos() < found.End()-found.Pos()) {
			found = extension
		}
	}
	return found
}

// AttachedComments returns leading and trailing comments for a node.
func AttachedComments(file *File, node Node) []*ast.CommentGroup {
	if file == nil || node == nil {
		return nil
	}
	return append([]*ast.CommentGroup(nil), file.attached[node]...)
}

// Walk visits the complete source tree.
func Walk(visitor Visitor, file *File) {
	if visitor == nil || file == nil {
		return
	}
	walkNode(visitor, file, file)
}

func walkNode(visitor Visitor, file *File, node Node) {
	next := visitor.Visit(node)
	if next == nil {
		return
	}
	for _, child := range file.children[node] {
		walkNode(next, file, child)
	}
	next.Visit(nil)
}

// Inspect calls visit for each node. A false result skips that node's children.
func Inspect(file *File, visit func(Node) bool) {
	if file == nil || visit == nil {
		return
	}
	walkNode(inspector(visit), file, file)
}

type inspector func(Node) bool

func (inspect inspector) Visit(node Node) Visitor {
	if node == nil || inspect(node) {
		return inspect
	}
	return nil
}

//nolint:gocognit,cyclop // This function enforces one parent for each node.
func buildIndex(file *File, anchors map[Node]Node) {
	file.children = make(map[Node][]Node)
	file.parents = make(map[Node]Node)
	file.extensions = nil
	for child, parent := range anchors {
		if nodePresent(child) && nodePresent(parent) {
			file.parents[child] = parent
		}
	}
	visited := make(map[Node]bool)
	var add func(Node) = nil
	add = func(node Node) {
		if node == nil || visited[node] {
			return
		}
		visited[node] = true
		children := syntaxChildren(file, node)
		for child, parent := range anchors {
			if parent == node {
				children = append(children, child)
			}
		}
		filtered := children[:0]
		seenChild := make(map[Node]bool)
		for _, child := range children {
			if !nodePresent(child) || seenChild[child] {
				continue
			}
			if parent := file.parents[child]; parent == nil || parent == node {
				filtered = append(filtered, child)
				seenChild[child] = true
			}
		}
		children = filtered
		slices.SortStableFunc(children, compareNodes)
		file.children[node] = children
		if extension, ok := node.(Extension); ok {
			file.extensions = append(file.extensions, extension)
		}
		for _, child := range children {
			if file.parents[child] == nil {
				file.parents[child] = node
			}
			add(child)
		}
	}
	add(file)
	slices.SortStableFunc(file.extensions, compareExtensions)
}

//nolint:gocognit,cyclop // This type switch defines the public tree shape.
func syntaxChildren(file *File, node Node) []Node {
	children := []Node(nil)
	switch node := node.(type) {
	case *File:
		children = []Node{node.Name}
		children = append(children, node.Decls...)
		owned := make(map[*ast.CommentGroup]bool)
		for owner, comments := range file.attached {
			if owner == file {
				continue
			}
			for _, comment := range comments {
				owned[comment] = true
			}
		}
		for _, comment := range node.Comments {
			if !owned[comment] {
				children = append(children, comment)
			}
		}
	case *EnumDecl:
		children = make([]Node, 1, 1+len(node.Variants))
		children[0] = node.Name
		for _, variant := range node.Variants {
			children = append(children, variant)
		}
	case *VariantDecl:
		children = make([]Node, 1, 1+len(node.Fields))
		children[0] = node.Name
		for _, field := range node.Fields {
			children = append(children, field)
		}
	case *StructDecl:
		children = make([]Node, 1, 1+len(node.Fields))
		children[0] = node.Name
		for _, field := range node.Fields {
			children = append(children, field)
		}
	case *CheckedDecl:
		children = []Node{node.Name, node.Base, node.Predicate}
	case *FieldDecl:
		children = []Node{node.Field, node.Default}
	case *LabeledStmt:
		children = []Node{node.Label, node.Stmt}
	case *MatchStmt:
		children = make([]Node, 1, 1+len(node.Cases))
		children[0] = node.Subject
		for _, matchCase := range node.Cases {
			children = append(children, matchCase)
		}
	case *MatchCase:
		children = make([]Node, 2, 2+len(node.Body))
		children[0] = node.Variant
		children[1] = node.Binding
		children = append(children, node.Body...)
	case *DefaultMarker:
		children = nil
	case *VariantLiteral:
		children = []Node{node.Literal}
	default:
		if goNode, ok := node.(ast.Node); ok {
			children = directGoChildren(goNode)
		}
	}
	if _, isFile := node.(*File); !isFile {
		for _, comment := range file.attached[node] {
			children = append(children, comment)
		}
	}
	return children
}

func directGoChildren(node ast.Node) []Node {
	value := reflect.ValueOf(node)
	if !value.IsValid() || value.IsNil() {
		return nil
	}
	return nodeValues(value.Elem())
}

func nodeValues(value reflect.Value) []Node {
	result := []Node(nil)
	for index := 0; index < value.NumField(); index++ {
		field := value.Field(index)
		switch field.Kind() {
		case reflect.Interface, reflect.Pointer:
			if node := reflectedNode(field); node != nil {
				result = append(result, node)
			}
		case reflect.Slice:
			for item := 0; item < field.Len(); item++ {
				if node := reflectedNode(field.Index(item)); node != nil {
					result = append(result, node)
				}
			}
		}
	}
	return result
}

func reflectedNode(value reflect.Value) Node {
	if !value.IsValid() ||
		((value.Kind() == reflect.Interface || value.Kind() == reflect.Pointer) &&
			value.IsNil()) {
		return nil
	}
	if value.Kind() == reflect.Interface {
		value = value.Elem()
	}
	if !value.CanInterface() {
		return nil
	}
	node, ok := value.Interface().(ast.Node)
	if !ok {
		return nil
	}
	if _, comment := node.(*ast.CommentGroup); comment {
		return nil
	}
	if _, comment := node.(*ast.Comment); comment {
		return nil
	}
	return node
}

func compareNodes(left Node, right Node) int {
	if !nodePresent(left) {
		return 1
	}
	if !nodePresent(right) {
		return -1
	}
	if left.Pos() != right.Pos() {
		return int(left.Pos() - right.Pos())
	}
	return int(right.End() - left.End())
}

func nodePresent(node Node) bool {
	if node == nil {
		return false
	}
	value := reflect.ValueOf(node)
	return value.Kind() != reflect.Pointer || !value.IsNil()
}

func compareExtensions(left Extension, right Extension) int {
	return compareNodes(left, right)
}
