// Code generated by tgo. DO NOT EDIT.

package app

import (
	"example.com/business/model"
	"fmt"
	"slices"
)

type LocalAccountAlias = model.Account
type LocalRequestAlias = model.Request

type ValidationEnvelope struct {
	Root *model.ValidationNode
}

type ValidationSharing struct {
	Numbers  chan int
	Callback func() int
}

type ValidationModelChannel struct {
	Accounts chan model.Account
}

type validationAccountChannel = chan model.Account
type validationAccountCallback = func() model.Account

type ValidationModelAliases struct {
	Callback validationAccountCallback
}

type ValidationModelChannelAlias struct {
	Accounts validationAccountChannel
}

type ValidationDynamicSharing struct {
	Values   chan any
	Callback func() any
}

type ValidationOpaqueEnvelope struct {
	Value validationOpaque
}

type ValidationOpaqueNumberEnvelope struct {
	Value validationOpaqueNumber
}

func Summary(name string) string {
	account := model.AccountPersonal{Name: name}.Account()
	switch enumValue1 := account; enumValue1.Tag() {
	case model.AccountTagPersonal:
		person := enumValue1.PersonalPayload()
		return fmt.Sprintf("person %s", person.Name)
	case model.AccountTagBusiness:
		company := enumValue1.BusinessPayload()
		return company.Company
	default:
		panic(enumValue1.UnknownTag()) // unreachable: tgolint requires a case per tag
	}
}

func Request(id string) model.Request {
	return model.Request{ID: id, Tags: model.TgoDefaultRequestTags()}
}

func Notice(body string) model.Notice {
	return model.NoticeText{Body: body, Labels: model.TgoDefaultNoticeTextLabels()}.Notice()
}

func Sorted(values []int) []int {
	result := slices.Clone(values)
	slices.Sort(result)
	return result
}

func ImportedAlias(name string) model.Account {
	return model.AccountPersonal{Name: name}.Account()
}

func LocalImportedAlias(name string) model.Account {
	return model.AccountPersonal{Name: name}.Account()
}

func LocalImportedRequest(id string) model.Request {
	return LocalRequestAlias{ID: id, Tags: model.TgoDefaultRequestTags()}
}
