// Code generated by tgo. DO NOT EDIT.

package app

import (
	"example.com/business/model"
	"fmt"
	"slices"
)

type LocalAccountAlias = model.Account
type LocalRequestAlias = model.Request

type ValidationEnvelope struct {
	Root *model.ValidationNode
}

type ValidationSharing struct {
	Numbers  chan int
	Callback func() int
}

type ValidationModelChannel struct {
	Accounts chan model.Account
}

type validationAccountChannel = chan model.Account
type validationAccountCallback = func() model.Account

type ValidationModelAliases struct {
	Callback validationAccountCallback
}

type ValidationModelChannelAlias struct {
	Accounts validationAccountChannel
}

type ValidationDynamicSharing struct {
	Values   chan any
	Callback func() any
}

type ValidationOpaqueEnvelope struct {
	Value validationOpaque
}

type ValidationOpaqueNumberEnvelope struct {
	Value validationOpaqueNumber
}

func Summary(name string) string {
	account := func(input model.TgoAccountPersonalInput) model.Account {
		return model.NewAccountPersonal(input.FieldName)
	}(model.TgoAccountPersonalInput{FieldName: name})
	switch enumValue1 := account; enumValue1.Tag() {
	case model.AccountTagPersonal:
		person := enumValue1.PersonalPayload()
		return fmt.Sprintf("person %s", person.Name)
	case model.AccountTagBusiness:
		company := enumValue1.BusinessPayload()
		return company.Company
	default:
		panic("invalid Account tag") // unreachable: tgolint requires a case per tag
	}
}

func Request(id string) model.Request {
	return model.Request{ID: id, Tags: model.TgoDefaultRequestTags()}
}

func Notice(body string) model.Notice {
	return func(input model.TgoNoticeTextInput) model.Notice {
		return model.NewNoticeText(input.FieldBody, input.FieldLabels)
	}(model.TgoNoticeTextInput{FieldBody: body, FieldLabels: model.TgoDefaultNoticeTextLabels()})
}

func Sorted(values []int) []int {
	result := slices.Clone(values)
	slices.Sort(result)
	return result
}

func ImportedAlias(name string) model.Account {
	return func(input model.TgoAccountPersonalInput) model.Account {
		return model.NewAccountPersonal(input.FieldName)
	}(model.TgoAccountPersonalInput{FieldName: name})
}

func LocalImportedAlias(name string) model.Account {
	return func(input model.TgoAccountPersonalInput) model.Account {
		return model.NewAccountPersonal(input.FieldName)
	}(model.TgoAccountPersonalInput{FieldName: name})
}

func ImportedPrivateChoice(text string) model.PrivateChoice {
	return func(input model.TgoPrivateChoiceValueInput) model.PrivateChoice {
		return model.NewPrivateChoiceValue(input.FieldText, input.FieldPointer, input.FieldValues)
	}(model.TgoPrivateChoiceValueInput{FieldText: text, FieldPointer: nil, FieldValues: model.TgoDefaultPrivateChoiceValuevalues()})
}

func LocalImportedRequest(id string) model.Request {
	return LocalRequestAlias{ID: id, Tags: model.TgoDefaultRequestTags()}
}
