// Code generated by tgo. DO NOT EDIT.
//tgo:v1 "complete.tgo" a1cc56d4919f29379ddcf757b86d8828f2b060c2950ec5c00d8c05d48de7aeca

package app

import "example.com/business/bridge"

func CompleteReexportedRequest(id string) any {
	return bridge.Request{ID: id, Tags: map[string]string{}}
}
