// Code generated by tgo. DO NOT EDIT.

package app

import (
	_ "example.com/business/bridge"
	"example.com/business/model"
)

func OnlyReexportedAccount(name string) any {
	return func(input model.TgoAccountPersonalInput) model.Account {
		return model.NewAccountPersonal(input.FieldName)
	}(model.TgoAccountPersonalInput{FieldName: name})
}
