// Code generated by tgo. DO NOT EDIT.
//tgo:v1 "reexport.tgo" 78625a7e21e8c9aea4b1b6914101be7f959c561bdfcd66840237b35a1e74b5e0

package app

import (
	"example.com/business/bridge"
	__tgo_import_2 "example.com/business/model"
)

func ReexportedAccount(name string) any {
	return __tgo_import_2.AccountPersonal{Name: name}.Account()
}

func ReexportedRequest(id string) any {
	return bridge.Request{ID: id, Tags: __tgo_import_2.TgoDefaultRequestTags()}
}
