// Code generated by tgo. DO NOT EDIT.

package app

import (
	"strings"
	"testing"
)

func TestPropagationSwitchCaseOrderAndErrors(t *testing.T) {
	events := []string{}
	result, err := PropagationSwitchCaseOrder(&events, 0, false)
	if result != "second" || err != nil || strings.Join(events, ",") != "tag,first" {
		t.Fatalf("early result=%q error=%v events=%v", result, err, events)
	}
	events = nil
	result, err = PropagationSwitchCaseOrder(&events, 2, false)
	if result != "second" || err != nil || strings.Join(events, ",") != "tag,first,second" {
		t.Fatalf("match result=%q error=%v events=%v", result, err, events)
	}
	events = nil
	result, err = PropagationSwitchCaseOrder(&events, 3, false)
	if result != "third" || err != nil || strings.Join(events, ",") != "tag,first,second,third" {
		t.Fatalf("late result=%q error=%v events=%v", result, err, events)
	}
	events = nil
	result, err = PropagationSwitchCaseOrder(&events, 2, true)
	if result != "" || err != errSwitchCase || strings.Join(events, ",") != "tag,first,second" {
		t.Fatalf("failure result=%q error=%v events=%v", result, err, events)
	}
	events = nil
	err = PropagationSwitchCaseWrapped(&events)
	if err == nil || err == errSwitchCase || err.Error() != "switchCaseValue: switch case failure" {
		t.Fatalf("wrapped error=%v", err)
	}
}

func TestPropagationSwitchCaseControlFlow(t *testing.T) {
	tests := []struct {
		name string
		run  func(*[]string) error
		want string
	}{
		{name: "default fallthrough", run: PropagationSwitchCaseDefaultFallthrough, want: "tag,case,default,fallthrough"},
		{name: "goto break", run: PropagationSwitchCaseGotoBreak, want: "case,body,done"},
		{name: "continue", run: PropagationSwitchCaseContinue, want: "case,body,case,body"},
		{name: "tagless", run: PropagationSwitchCaseTagless, want: "first,second,body"},
		{name: "initializer", run: PropagationSwitchCaseInitializer, want: "init,tag,case,body"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			events := []string{}
			err := test.run(&events)
			if err != nil || strings.Join(events, ",") != test.want {
				t.Fatalf("error=%v events=%v", err, events)
			}
		})
	}
}
