// Code generated by tgo. DO NOT EDIT.
//tgo:v2 "comprehension.tgo"

package comprehensionnilbad

type item struct {
}

type holder struct {
	Body []*item
}

func copyItems(values []*item) holder {

	__tgo_result := make([]*item, len(values))
	copy(__tgo_result, values)
	return holder{
		Body: __tgo_result,
	}
}
