// Code generated by tgo. DO NOT EDIT.
//tgo:v2 "local.tgo"

package localbad

import __tgo_json "encoding/json"
import __tgo_fmt "fmt"

// Count requires NewCount success. Zero is invalid.
// Shared data keeps Go aliases. Callers must keep the rule.
type Count struct{ value int }
type tgoCountError struct{}

func (tgoCountError) Error() string { return "invalid Count" }

// NewCount checks the rule. Check the error before use.
func NewCount(value int) (Count, error) {
	if !(value > 0) {
		return Count{}, tgoCountError{}
	}
	return Count{value: value}, nil
}

// Value requires construction success. Shared data keeps its aliases.
func (v Count) Value() int { return v.value }

// Event requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type Event struct {
	tgoTag     uint8
	tgoStarted EventStarted
	tgoStopped EventStopped
}

// TgoTag returns the tag. Use only on a constructed value.
func (v Event) TgoTag() uint8 { return v.tgoTag }

// EventStarted is the Started payload.
type EventStarted struct {
	ID string
}

// NewEventStarted constructs Event. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewEventStarted(value EventStarted) Event {
	return Event{tgoTag: 1, tgoStarted: value}
}

// TgoStarted returns the Started payload. Check TgoTag first.
func (v Event) TgoStarted() EventStarted { return v.tgoStarted }

// EventStopped is the Stopped payload.
type EventStopped struct {
	Reason string
}

// NewEventStopped constructs Event. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewEventStopped(value EventStopped) Event {
	return Event{tgoTag: 2, tgoStopped: value}
}

// TgoStopped returns the Stopped payload. Check TgoTag first.
func (v Event) TgoStopped() EventStopped { return v.tgoStopped }

func (v Event) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case 1:
		payload := v.TgoStarted()
		return __tgo_json.Marshal(struct {
			Payload EventStarted `json:"Started"`
		}{Payload: payload})
	case 2:
		payload := v.TgoStopped()
		return __tgo_json.Marshal(struct {
			Payload EventStopped `json:"Stopped"`
		}{Payload: payload})
	default:
		return nil, __tgo_fmt.Errorf("invalid Event JSON tag")
	}
}

func (v *Event) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]__tgo_json.RawMessage
	if err := __tgo_json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return __tgo_fmt.Errorf("expected one Event JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Started":
		var payload EventStarted
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = NewEventStarted(payload)
		return nil
	case "Stopped":
		var payload EventStopped
		if err := __tgo_json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = NewEventStopped(payload)
		return nil
	default:
		return __tgo_fmt.Errorf("unknown Event JSON variant %q", variant)
	}
}
