// Code generated by tgo. DO NOT EDIT.

// Package cfg builds control-flow graphs from TGo syntax ADTs.
package cfg

import "tgo/pkg/syntax"

// CFG is the control-flow graph of one function body.

type CFG struct {
	Blocks []*Block
}

// Block is one basic block.

type Block struct {
	Nodes   []syntax.Node
	Succs   []*Block
	Index   int32
	Live    bool
	Kind    BlockKind
	Stmt    *syntax.Statement
	returns bool
	succs   [2]*Block
}

// BlockKind identifies a block's role.
type BlockKind uint8

// BlockKind values identify control-flow block roles.
const (
	KindInvalid         BlockKind = 0
	KindUnreachable     BlockKind = 1
	KindBody            BlockKind = 2
	KindForBody         BlockKind = 3
	KindForDone         BlockKind = 4
	KindForLoop         BlockKind = 5
	KindForPost         BlockKind = 6
	KindIfDone          BlockKind = 7
	KindIfElse          BlockKind = 8
	KindIfThen          BlockKind = 9
	KindLabel           BlockKind = 10
	KindRangeBody       BlockKind = 11
	KindRangeDone       BlockKind = 12
	KindRangeLoop       BlockKind = 13
	KindSelectCaseBody  BlockKind = 14
	KindSelectDone      BlockKind = 15
	KindSelectAfterCase BlockKind = 16
	KindSwitchCaseBody  BlockKind = 17
	KindSwitchDone      BlockKind = 18
	KindSwitchNextCase  BlockKind = 19
)

// New builds a control-flow graph from one syntax block.
func New(body *syntax.BlockStatement, mayReturn func(*syntax.Expression) bool) *CFG {
	builder := graphBuilder{mayReturn: mayReturn}
	bodyNode := func(input syntax.TgoStatementBlockInput) syntax.Statement {
		return syntax.NewStatementBlock(input.FieldValue)
	}(syntax.TgoStatementBlockInput{FieldValue: body})
	builder.current = builder.newBlock(KindBody, &bodyNode)
	builder.statement(&bodyNode)

	queue := make([]*Block, 0, len(builder.blocks))
	queue = append(queue, builder.blocks[0])
	for len(queue) > 0 {
		block := queue[len(queue)-1]
		queue = queue[:len(queue)-1]
		if !block.Live {
			block.Live = true
			queue = append(queue, block.Succs...)
		}
	}
	return &CFG{Blocks: builder.blocks}
}
