// Code generated by tgo. DO NOT EDIT.

package main

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunWritesAndListsFiles(t *testing.T) {
	directory := t.TempDir()
	path := filepath.Join(directory, "sample.tgo")
	input := []byte("package sample\nfunc value()int{return 1}\n")
	if err := os.WriteFile(path, input, 0o640); err != nil {
		t.Fatal(err)
	}
	output := new(bytes.Buffer)
	err := run([]string{path}, false, true, strings.NewReader(""), output)
	if err != nil {
		t.Fatal(err)
	}
	if output.String() != path+"\n" {
		t.Fatalf("listed files = %q, want %q", output.String(), path+"\n")
	}
	if err := run([]string{path}, true, false, strings.NewReader(""), output); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "package sample\n\nfunc value() int { return 1 }\n"
	if string(got) != want {
		t.Fatalf("written source:\n%s\nwant:\n%s", got, want)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o640 {
		t.Fatalf("written mode = %v, want 0640", info.Mode().Perm())
	}
	backups, err := filepath.Glob(filepath.Join(directory, ".sample.tgo.tgofmt-*"))
	if err != nil {
		t.Fatal(err)
	}
	if len(backups) != 0 {
		t.Fatalf("successful write kept backups: %v", backups)
	}
}

func TestRunFormatsStandardInput(t *testing.T) {
	t.Parallel()
	input := "package sample\nfunc value()int{return 1}\n"
	output := new(bytes.Buffer)
	if err := run(nil, false, false, strings.NewReader(input), output); err != nil {
		t.Fatal(err)
	}
	want := "package sample\n\nfunc value() int { return 1 }\n"
	if output.String() != want {
		t.Fatalf("standard output:\n%s\nwant:\n%s", output.String(), want)
	}
}

func TestRunListsChangedStandardInput(t *testing.T) {
	t.Parallel()
	output := new(bytes.Buffer)
	input := strings.NewReader("package   sample\n")
	if err := run(nil, false, true, input, output); err != nil {
		t.Fatal(err)
	}
	if output.String() != "<standard input>\n" {
		t.Fatalf("listed input = %q", output.String())
	}
}

func TestRunDoesNotWriteMalformedFile(t *testing.T) {
	t.Parallel()
	directory := t.TempDir()
	path := filepath.Join(directory, "bad.tgo")
	input := []byte("package sample\nfunc {")
	if err := os.WriteFile(path, input, 0o600); err != nil {
		t.Fatal(err)
	}
	err := run([]string{path}, true, false, strings.NewReader(""), new(bytes.Buffer))
	if err == nil {
		t.Fatal("write accepted malformed input")
	}
	got, readErr := os.ReadFile(path)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if !bytes.Equal(got, input) {
		t.Fatalf("malformed file changed to %q", got)
	}
}

func TestRunRejectsWriteForStandardInput(t *testing.T) {
	t.Parallel()
	err := run(nil, true, false, strings.NewReader("package sample\n"), new(bytes.Buffer))
	if err == nil {
		t.Fatal("write accepted standard input")
	}
}

func TestRunWritePreservesHardLink(t *testing.T) {
	t.Parallel()
	directory := t.TempDir()
	original := filepath.Join(directory, "source.tgo")
	linked := filepath.Join(directory, "linked.tgo")
	source := []byte("package sample\nfunc value()int{return 1}\n")
	if err := os.WriteFile(original, source, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Link(original, linked); err != nil {
		t.Skipf("hard links are unavailable: %v", err)
	}
	input := strings.NewReader("")
	if err := run([]string{linked}, true, false, input, new(bytes.Buffer)); err != nil {
		t.Fatal(err)
	}
	originalInfo, err := os.Stat(original)
	if err != nil {
		t.Fatal(err)
	}
	linkedInfo, err := os.Stat(linked)
	if err != nil {
		t.Fatal(err)
	}
	if !os.SameFile(originalInfo, linkedInfo) {
		t.Fatal("formatter replaced the linked inode")
	}
	want := "package sample\n\nfunc value() int { return 1 }\n"
	got, err := os.ReadFile(original)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != want {
		t.Fatalf("linked source:\n%s\nwant:\n%s", got, want)
	}
}

func TestReplaceContentsRestoresAfterPartialWrite(t *testing.T) {
	t.Parallel()
	original := []byte("original source")
	target := &failingRewriteTarget{
		data:      append([]byte(nil), original...),
		failAfter: 4,
		failed:    false,
	}
	restored, err := replaceContents(target, original, []byte("formatted source"))
	if !errors.Is(err, errInjectedWrite) {
		t.Fatalf("replace error = %v, want injected write error", err)
	}
	if !restored {
		t.Fatal("replace did not report a restored source")
	}
	if !bytes.Equal(target.data, original) {
		t.Fatalf("restored source = %q, want %q", target.data, original)
	}
}

var errInjectedWrite = errors.New("injected write failure")

type failingRewriteTarget struct {
	data      []byte
	failAfter int
	failed    bool
}

func (f *failingRewriteTarget) Write(data []byte) (int, error) {
	if f.failed {
		return 0, errInjectedWrite
	}
	f.failed = true
	written := min(f.failAfter, len(data))
	copy(f.data, data[:written])
	return written, errInjectedWrite
}

func (f *failingRewriteTarget) WriteAt(data []byte, offset int64) (int, error) {
	stop := int(offset) + len(data)
	if stop > len(f.data) {
		f.data = append(f.data, make([]byte, stop-len(f.data))...)
	}
	return copy(f.data[int(offset):], data), nil
}

func (f *failingRewriteTarget) Truncate(size int64) error {
	if size <= int64(len(f.data)) {
		f.data = f.data[:size]
		return nil
	}
	f.data = append(f.data, make([]byte, int(size)-len(f.data))...)
	return nil
}
