// Code generated by tgo. DO NOT EDIT.

package sourcepolicybad

import "encoding/json"
import jsonv2 "encoding/json/v2"
import "encoding/json/jsontext"
import "fmt"

import "example.com/tgolint/model"

func tgoLocalExternalJSONTo[T interface{}](out *jsontext.Encoder, name string, payload T) error {
	if err := out.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := out.WriteToken(jsontext.String(name)); err != nil {
		return err
	}
	if err := jsonv2.MarshalEncode(out, payload); err != nil {
		return err
	}
	return out.WriteToken(jsontext.EndObject)
}

// Local requires a variant constructor. Its zero value is invalid.
// Shared data keeps Go aliases. Callers must keep model values valid.
type LocalTag uint8

const (
	LocalTagReady LocalTag = iota + 1
)

type Local struct {
	tgoTag   LocalTag
	tgoReady LocalReady
}

// Tag returns the active tag.
func (v Local) Tag() LocalTag { return v.tgoTag }

// UnknownTag describes an invalid tag.
func (v Local) UnknownTag() string {
	return fmt.Sprintf("Local: unknown tag %d — tgolint proves every tag has a case, so this is unreachable", v.tgoTag)
}

// LocalReady is the Ready payload.
type LocalReady struct {
	ID string
}
type TgoLocalReadyInput struct {
	FieldID string
}

// NewLocalReady constructs Local. Model fields must be valid.
// Shared fields keep their aliases and caller duties.
func NewLocalReady(ID string) Local {
	tgoValue := LocalReady{ID}
	return Local{tgoTag: LocalTagReady, tgoReady: tgoValue}
}

// ReadyPayload requires Ready. No tag check.
func (v Local) ReadyPayload() LocalReady { return v.tgoReady }

func (v Local) MarshalJSON() ([]byte, error) {
	switch v.tgoTag {
	case LocalTagReady:
		payload := v.ReadyPayload()
		return json.Marshal(struct {
			Payload LocalReady `json:"Ready"`
		}{Payload: payload})
	default:
		return nil, fmt.Errorf("invalid Local JSON tag")
	}
}

func (v Local) MarshalJSONTo(out *jsontext.Encoder) error {
	switch v.tgoTag {
	case LocalTagReady:
		payload := v.ReadyPayload()
		return tgoLocalExternalJSONTo(out, "Ready", payload)
	default:
		return fmt.Errorf("invalid Local JSON tag")
	}
}

func (v *Local) UnmarshalJSON(data []byte) error {
	var variant string
	var payloadData []byte
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}
	if len(object) != 1 {
		return fmt.Errorf("expected one Local JSON variant")
	}
	for key, value := range object {
		variant = key
		payloadData = value
	}
	switch variant {
	case "Ready":
		var payload LocalReady
		if err := json.Unmarshal(payloadData, &payload); err != nil {
			return err
		}
		*v = NewLocalReady(payload.ID)
		return nil
	default:
		return fmt.Errorf("unknown Local JSON variant %q", variant)
	}
}

func (v *Local) UnmarshalJSONFrom(in *jsontext.Decoder) error {
	token, err := in.ReadToken()
	if err != nil {
		return err
	}
	if token.Kind() != '{' {
		return fmt.Errorf("expected one Local JSON variant")
	}
	var payloadData jsontext.Value
	var unknown string
	selected := 0
	haveName := false
	multiple := false
	for in.PeekKind() != '}' {
		nameToken, err := in.ReadToken()
		if err != nil {
			return err
		}
		wireName := nameToken.String()
		current := 0
		switch wireName {
		case "Ready":
			current = 1
		}
		same := haveName && current == selected
		if same && current == 0 {
			same = wireName == unknown
		}
		if !haveName {
			haveName = true
			selected = current
			if current == 0 {
				unknown = string(append([]byte(nil), wireName...))
			}
		} else if !same {
			multiple = true
		}
		if !multiple && current > 0 && current == selected {
			raw, err := in.ReadValue()
			if err != nil {
				return err
			}
			payloadData = append(payloadData[:0], raw...)
		} else if err := in.SkipValue(); err != nil {
			return err
		}
	}
	if _, err := in.ReadToken(); err != nil {
		return err
	}
	if !haveName || multiple {
		return fmt.Errorf("expected one Local JSON variant")
	}
	if selected == 0 {
		return fmt.Errorf("unknown Local JSON variant %q", unknown)
	}
	switch selected {
	case 1:
		var payload LocalReady
		if err := jsonv2.Unmarshal(payloadData, &payload, in.Options()); err != nil {
			return err
		}
		*v = NewLocalReady(payload.ID)
		return nil
	default:
		return fmt.Errorf("invalid Local JSON tag")
	}
}

type Port struct {
	number int
}
type TgoPortInput struct {
	FieldNumber int
}

// NewPort constructs and checks Port.
func NewPort(number int) (Port, error) {
	return Port{number}.check()
}

func (value Port) check() (Port, error) {
	value.number = 1
	other := value
	other.number = 2
	{
		value := Port{}
		value.number = 3
		_ = value
	}
	return value, nil
}

type LocalLayout struct {
	tgoTag   LocalTag
	tgoReady LocalReady
}

type DirectLocal Local
type DirectImported model.Event

type LocalTypes interface {
	Local
	Tag() LocalTag
	UnknownTag() string
	ReadyPayload() LocalReady
}

func localLiteral() Local {
	return Local{}
}

func localConstruction(value LocalLayout) Local {
	return Local(value)
}

func localExposure(value Local) LocalLayout {
	return LocalLayout(value)
}

func pointerExposure(value *Local) *LocalLayout {
	return (*LocalLayout)(value)
}

func genericConstruction[T LocalTypes](value LocalLayout) T {
	return T(value)
}

func genericExposure[T LocalTypes](value T) LocalLayout {
	return LocalLayout(value)
}

func anonymousExposure(value Local) LocalReady {
	var exposed struct {
		tgoTag   LocalTag
		tgoReady LocalReady
	} = value
	return exposed.tgoReady
}

type Embedded struct {
	Local
}

func promotedRepresentation(value Embedded) LocalTag {
	return value.tgoTag
}

func change(value Port) {
	value.number = 2
	value.number++
	_ = &value.number
	for value.number = range []int{1} {
	}
}

type mutableDetails struct {
	number int
}

type nestedDetails struct {
	number      int
	values      [2]int
	pointer     *mutableDetails
	slice       []int
	mapping     map[string]int
	valueMiddle valueMiddle
	valueArray  [1]valueMiddle
}

type promotedLeaf struct {
	number int
}

type valueMiddle struct {
	promotedLeaf
}

type NestedPort struct {
	nestedDetails
}
type TgoNestedPortInput struct {
	Field0 nestedDetails
}

// NewNestedPort constructs and checks NestedPort.
func NewNestedPort(tgoField0 nestedDetails) (NestedPort, error) {
	return NestedPort{tgoField0}.check()
}

func (value NestedPort) check() (NestedPort, error) { return value, nil }

func changeNested(value *NestedPort) {
	value.number = 1
	value.nestedDetails.number = 2
	value.values[0] = 3
	value.nestedDetails.values[1]++
	value.values[:][0] = 4
	for value.values[0] = range []int{4} {
	}
	_ = &value.nestedDetails.number
	_ = &value.values[1]
	value.pointer = nil
	value.valueMiddle.number = 5
	value.valueArray[0].number = 6
}

var localConstructor = NewPort
var localCarrier = TgoPortInput{FieldNumber: 0}
var importedConstructor = model.NewCount
var importedCarrier = model.TgoCountInput{FieldValue: 0}
var localEnumConstructor = NewLocalReady
var importedEnumConstructor = model.NewEventStarted

func generatedEnumTypes(
	localPayload LocalReady,
	localCarrier TgoLocalReadyInput,
	importedPayload model.EventStarted,
	importedCarrier model.TgoEventStartedInput,
) {
}

func importedLiteral() model.Event {
	return model.Event{}
}

func validChecked(number int) (Port, error) {
	return func(tgoInput TgoPortInput) (Port, error) {
		return NewPort(tgoInput.FieldNumber)
	}(TgoPortInput{FieldNumber: number})
}

func validVariant(id string) Local {
	return func(input TgoLocalReadyInput) Local {
		return NewLocalReady(input.FieldID)
	}(TgoLocalReadyInput{FieldID: id})
}

func (value LocalReady) Label() string { return value.ID }

func (value *LocalReady) Clear() { value.ID = "" }

type LocalAlias = Local
