// Code generated by tgo. DO NOT EDIT.

package source

import (
	"testing"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/analysistest"
)

func TestParseUsesAnalysisSource(t *testing.T) {
	analyzer := new(analysis.Analyzer)
	analyzer.Name = "sourceparse"
	analyzer.Doc = "test source parsing"
	analyzer.Run = func(pass *analysis.Pass) (any, error) {
		parsed, err := Parse(pass)
		if err != nil {
			return nil, err
		}
		if len(parsed) != 1 || parsed[0].Name.Name != "sourceparse" {
			t.Fatalf("Parse() = %v, want one sourceparse package file", parsed)
		}
		return nil, nil
	}
	analysistest.Run(t, analysistest.TestData(), analyzer, "sourceparse")
}
