name: VS Code CI

on:
  workflow_dispatch:
  schedule:
    - cron: "23 4 * * 1"

permissions:
  contents: read

jobs:
  vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: editors/vscode/package-lock.json
      - run: make vscode-test
